// Legal Pages Content - Terms, Privacy, Disclaimers, About, Contact
// Original content for YMYL compliance and AdSense approval

const LegalPages = (function() {

  // STEP 1A: Terms of Service
  const TERMS_OF_SERVICE = `
    <div class="legal-page">
      <h1>Terms of Service</h1>
      <p class="legal-meta">Last Updated: July 26, 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing and using CalcProMaster ("the Service"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.</p>

      <h2>2. Use of Calculators</h2>
      <p>CalcProMaster provides free online calculators for informational and educational purposes. You agree to:</p>
      <ul>
        <li>Use the calculators for lawful purposes only</li>
        <li>Not attempt to disrupt, hack, or abuse the Service</li>
        <li>Not use automated tools to scrape or download content in bulk</li>
        <li>Not misrepresent calculation results as professional advice</li>
      </ul>

      <h2>3. No Warranty - Calculation Accuracy</h2>
      <p><strong>IMPORTANT:</strong> CalcProMaster calculators are provided "AS IS" without warranty of any kind. While we strive for accuracy, calculation results may contain errors or may not be suitable for your specific situation. We make no guarantee that:</p>
      <ul>
        <li>Calculations are accurate, complete, or error-free</li>
        <li>Results are appropriate for your specific use case</li>
        <li>The Service will be uninterrupted or error-free</li>
        <li>Any errors will be corrected</li>
      </ul>

      <h2>4. Limitation of Liability</h2>
      <p>To the maximum extent permitted by law, CalcProMaster and its creators shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from:</p>
      <ul>
        <li>Your use of or inability to use the Service</li>
        <li>Calculation errors or inaccuracies</li>
        <li>Financial losses resulting from reliance on calculation results</li>
        <li>Any decisions made based on calculator outputs</li>
      </ul>
      <p><strong>You use CalcProMaster calculators at your own risk.</strong> Always verify important calculations independently and consult qualified professionals before making significant decisions.</p>

      <h2>5. Intellectual Property</h2>
      <p>All content, design, code, and calculation formulas on CalcProMaster are owned by CalcProMaster or licensed to us. You may:</p>
      <ul>
        <li>Use the calculators for personal or commercial purposes</li>
        <li>Share individual calculation results</li>
        <li>Link to CalcProMaster from your website</li>
      </ul>
      <p>You may NOT:</p>
      <ul>
        <li>Copy, reproduce, or redistribute the calculator code or design</li>
        <li>Remove copyright notices or attributions</li>
        <li>Claim the calculators as your own work</li>
      </ul>

      <h2>6. Third-Party Services</h2>
      <p>CalcProMaster uses third-party services including:</p>
      <ul>
        <li>Currency exchange rate API (open.er-api.com)</li>
        <li>Google Analytics (if you consent)</li>
        <li>Google AdSense (if you consent)</li>
      </ul>
      <p>Your use of these services is subject to their respective terms and privacy policies.</p>

      <h2>7. Changes to Terms</h2>
      <p>We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Your continued use of CalcProMaster after changes constitutes acceptance of the new Terms.</p>

      <h2>8. Governing Law</h2>
      <!-- MANUAL ACTION: apne country/state ka naam yahan daal do (e.g. Pakistan,
           India, USA — jahan aap registered ho). Abhi neutral placeholder hai. -->
      <p>These Terms are governed by the laws of the country/state in which CalcProMaster is based. Any disputes shall be resolved in the courts of that jurisdiction.</p>

      <h2>9. Contact</h2>
      <p>Questions about these Terms? Contact us at: <strong>calpromaster@gmail.com</strong></p>
    </div>
  `;

  // STEP 1B: Financial Disclaimer
  const FINANCIAL_DISCLAIMER = `
    <div class="legal-page">
      <h1>Financial Disclaimer</h1>
      <p class="legal-meta">Last Updated: July 26, 2026</p>

      <h2>Important Notice</h2>
      <p><strong>CalcProMaster financial calculators provide estimates for informational and educational purposes only. They do NOT constitute financial, investment, tax, or legal advice.</strong></p>

      <h2>Not Financial Advice</h2>
      <p>The results generated by CalcProMaster calculators should not be used as the sole basis for any financial decision. Always consult with a qualified financial advisor, tax professional, or legal counsel before:</p>
      <ul>
        <li>Taking out a loan or mortgage</li>
        <li>Making investment decisions</li>
        <li>Planning retirement strategies</li>
        <li>Filing taxes or claiming deductions</li>
        <li>Making major purchases or financial commitments</li>
      </ul>

      <h2>Accuracy Limitations</h2>
      <p>Financial calculations depend on many factors that our calculators cannot fully account for, including:</p>
      <ul>
        <li>Your specific financial situation and credit profile</li>
        <li>Current and changing market conditions</li>
        <li>Lender-specific fees, policies, and terms</li>
        <li>Local, state, and federal regulations</li>
        <li>Tax law changes and individual tax circumstances</li>
      </ul>

      <h2>No Guarantee of Results</h2>
      <p>Past performance or calculated projections do not guarantee future results. Actual loan payments, investment returns, tax obligations, and other financial outcomes may differ significantly from calculator estimates.</p>

      <h2>How Our Financial Calculations Work (Methodology)</h2>
      <p>Every calculator shows its formula, a worked example with default inputs, and the assumptions behind the math — visible on the page, not hidden behind scripts. Results are computed in your browser from the values you enter, using standard published formulas (for example, standard amortization for loans and compound-interest math for savings). Where a real-world outcome depends on factors no calculator can know — your lender's exact fee schedule, your tax situation, market movements — the calculator's limitations section says so explicitly. Each calculator is covered by an automated formula QA contract with independently verified expected results before it is promoted into the sitemap.</p>

      <h2>Your Responsibility</h2>
        <li>Understanding the limitations of each calculator</li>
        <li>Seeking professional advice before acting on results</li>
        <li>Any financial decisions you make</li>
      </ul>

      <p class="legal-warning">⚠️ <strong>Always consult a qualified financial advisor before making financial decisions.</strong></p>
    </div>
  `;

  // STEP 1C: Health Disclaimer
  const HEALTH_DISCLAIMER = `
    <div class="legal-page">
      <h1>Health & Medical Disclaimer</h1>
      <p class="legal-meta">Last Updated: July 26, 2026</p>

      <h2>Important Notice</h2>
      <p><strong>CalcProMaster health calculators provide general estimates for informational purposes only. They are NOT a substitute for professional medical advice, diagnosis, or treatment.</strong></p>

      <h2>Not Medical Advice</h2>
      <p>The results generated by CalcProMaster health calculators should never be used to self-diagnose or make medical decisions. Always consult with a qualified healthcare provider before:</p>
      <ul>
        <li>Starting any diet, exercise, or weight loss program</li>
        <li>Making changes to your medication or treatment</li>
        <li>Diagnosing or treating any medical condition</li>
        <li>Making decisions about your health or fitness</li>
      </ul>

      <h2>General Estimates Only</h2>
      <p>Health calculators use standardized formulas that may not be accurate for:</p>
      <ul>
        <li>Individuals with medical conditions</li>
        <li>Pregnant or breastfeeding women</li>
        <li>Children and adolescents</li>
        <li>Athletes or highly active individuals</li>
        <li>Elderly individuals</li>
        <li>People with unique body compositions</li>
      </ul>

      <h2>No Substitute for Professional Care</h2>
      <p>CalcProMaster calculators cannot:</p>
      <ul>
        <li>Diagnose medical conditions</li>
        <li>Recommend specific treatments or medications</li>
        <li>Replace blood tests, medical imaging, or clinical assessments</li>
        <li>Account for your individual medical history</li>
      </ul>

      <h2>Emergency Situations</h2>
      <p><strong>If you are experiencing a medical emergency, call emergency services immediately. Do not rely on any online calculator.</strong></p>

      <h2>How Our Health Calculations Work (Methodology)</h2>
      <p>Our health tools use formulas published in peer-reviewed research and clinical practice — for example, Mifflin-St Jeor for basal metabolic rate, the standard BMI weight/height ratio, and established heart-rate zone percentages. Each calculator displays its formula, a worked example, and its assumptions on the page, and states its limits: the population ranges a formula was derived from, what activity multipliers assume, and when a result should be discussed with a clinician. All calculations run entirely in your browser — no health data is sent anywhere.</p>

      <h2>Your Responsibility</h2>
      <p>You are solely responsible for:</p>
      <ul>
        <li>Consulting your doctor or healthcare provider</li>
        <li>Following professional medical advice</li>
        <li>Any health decisions you make</li>
      </ul>

      <p class="legal-warning">⚠️ <strong>Always consult a doctor or qualified healthcare provider for medical advice.</strong></p>
    </div>
  `;

  // STEP 1D: Privacy Policy
  const PRIVACY_POLICY = `
    <div class="legal-page">
      <h1>Privacy Policy</h1>
      <p class="legal-meta">Last Updated: July 26, 2026</p>

      <h2>Overview</h2>
      <p>CalcProMaster is committed to protecting your privacy. This policy explains what data we collect, how we use it, and your rights.</p>

      <h2>What Data We Collect</h2>

      <h3>Data We DO Collect:</h3>
      <ul>
        <li><strong>localStorage data (browser-side only):</strong> Your calculation history, favorites, preferences, and settings are stored in your browser's localStorage. This data never leaves your device.</li>
        <li><strong>Anonymous usage statistics (with consent):</strong> If you consent, we use Google Analytics to collect anonymous data about page visits, popular calculators, and general usage patterns. No personal information is collected.</li>
        <li><strong>Currency exchange rates:</strong> When using currency calculators, we fetch real-time rates from a third-party API (open.er-api.com). No personal data is sent.</li>
      </ul>

      <h3>Data We DO NOT Collect:</h3>
      <ul>
        <li>No user accounts or registration</li>
        <li>No personally identifiable information (name, email, address)</li>
        <li>No server-side storage of your calculations</li>
        <li>No tracking across websites</li>
        <li>No selling of data to third parties</li>
      </ul>

      <h2>How We Use Data</h2>
      <ul>
        <li><strong>localStorage:</strong> To provide features like history, favorites, and saved presets. This data is stored only in your browser.</li>
        <li><strong>Analytics (optional):</strong> To understand which calculators are most popular and improve the service. You can opt out via the cookie banner.</li>
        <li><strong>AdSense (optional):</strong> If you consent, Google AdSense may show ads. You can opt out via the cookie banner.</li>
      </ul>

      <h2>Third-Party Services</h2>
      <p>CalcProMaster uses the following third-party services:</p>
      <ul>
        <li><strong>Google Analytics:</strong> Anonymous usage statistics (only if you consent). <a href="https://policies.google.com/privacy" target="_blank">Google Privacy Policy</a></li>
        <li><strong>Google AdSense:</strong> Advertising (only if you consent). <a href="https://policies.google.com/technologies/ads" target="_blank">Google Ads Policy</a></li>
        <li><strong>open.er-api.com:</strong> Currency exchange rates. <a href="https://www.exchangerate-api.com/terms" target="_blank">Exchange Rate API Terms</a></li>
      </ul>
      <p>These services may use cookies. You control consent via the cookie banner on first visit.</p>

      <h2>Your Rights</h2>
      <p>You have the right to:</p>
      <ul>
        <li><strong>Clear your data:</strong> Delete your browser's localStorage at any time via browser settings or CalcProMaster's "Clear History" button.</li>
        <li><strong>Opt out of analytics:</strong> Reject non-essential cookies via the cookie banner.</li>
        <li><strong>Opt out of ads:</strong> Reject non-essential cookies or use an ad blocker.</li>
      </ul>

      <h2>Data Security</h2>
      <p>Since all calculations run in your browser and no data is sent to our servers, your data is as secure as your device. We recommend:</p>
      <ul>
        <li>Using a secure, up-to-date browser</li>
        <li>Not using CalcProMaster on shared/public computers if you save sensitive calculations</li>
        <li>Clearing your browser data if you share your device</li>
      </ul>

      <h2>GDPR & International Users</h2>
      <p>CalcProMaster complies with GDPR principles:</p>
      <ul>
        <li>Consent is freely given via our cookie banner</li>
        <li>Data collection is minimal and purpose-specific</li>
        <li>You can withdraw consent or delete data at any time</li>
      </ul>

      <h2>Changes to This Policy</h2>
      <p>We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated "Last Updated" date.</p>

      <h2>Contact Us</h2>
      <p>Questions about privacy? Contact us at: <strong>calpromaster@gmail.com</strong></p>
    </div>
  `;

  // STEP 1E: General Disclaimer
  const GENERAL_DISCLAIMER = `
    <div class="legal-page">
      <h1>General Disclaimer</h1>
      <p class="legal-meta">Last Updated: July 26, 2026</p>

      <h2>Use at Your Own Risk</h2>
      <p>CalcProMaster provides free online calculators for general informational and educational purposes. All calculators and results are provided "AS IS" without any warranties or guarantees of accuracy, completeness, or suitability for any particular purpose.</p>

      <h2>No Professional Advice</h2>
      <p>CalcProMaster calculators do NOT provide:</p>
      <ul>
        <li>Financial, investment, or tax advice</li>
        <li>Medical, health, or fitness advice</li>
        <li>Legal or regulatory advice</li>
        <li>Engineering or construction advice</li>
        <li>Professional consulting of any kind</li>
      </ul>
      <p><strong>Always consult qualified professionals</strong> in the relevant field before making important decisions based on calculator results.</p>

      <h2>Accuracy Limitations</h2>
      <p>While we strive for accuracy, calculation results may be affected by:</p>
      <ul>
        <li>Incorrect or incomplete input data</li>
        <li>Simplified formulas that don't account for all variables</li>
        <li>Rounding errors in complex calculations</li>
        <li>Changes in laws, regulations, or standards</li>
        <li>Regional variations and local requirements</li>
        <li>Software bugs or errors</li>
      </ul>

      <h2>User Responsibility</h2>
      <p>You are solely responsible for:</p>
      <ul>
        <li>Verifying all inputs and outputs</li>
        <li>Independently confirming important calculations</li>
        <li>Understanding the limitations of each calculator</li>
        <li>Seeking professional advice when needed</li>
        <li>Any decisions or actions based on calculator results</li>
      </ul>

      <h2>No Liability</h2>
      <p>CalcProMaster and its creators are not liable for any losses, damages, or consequences arising from the use of these calculators, including but not limited to:</p>
      <ul>
        <li>Financial losses from incorrect calculations</li>
        <li>Business losses from poor decisions</li>
        <li>Health issues from following calculator suggestions</li>
        <li>Legal issues from non-compliance</li>
        <li>Any other direct or indirect damages</li>
      </ul>

      <h2>Changes and Updates</h2>
      <p>Calculator formulas, assumptions, and features may change without notice. We are not responsible for keeping calculators updated with the latest regulations, rates, or best practices in every field.</p>

      <p class="legal-warning">⚠️ <strong>Bottom line: Use CalcProMaster as a helpful starting point, but always verify important calculations and consult professionals before making significant decisions.</strong></p>
    </div>
  `;

  // STEP 1F-a: Editorial Policy Page (E-E-A-T: linked from every tool page's
  // review block — this page must exist or 1,300+ pages link to a 404)
  const EDITORIAL_POLICY = `
    <div class="legal-page">
      <h1>Editorial Policy</h1>
      <p class="legal-meta">Last updated: September 2026</p>

      <h2>Scope</h2>
      <p>This policy describes how calculator content on CalcProMaster is written, verified, and corrected. It applies to every calculator page, guide, and blog post on this site.</p>

      <h2>How Content Is Written</h2>
      <p>Each calculator page states the standard, publicly documented formula it implements, walks through a worked example with expected values, and explains the assumptions and limitations of the method. Financial, health, and regional-tax content follows conventions from authoritative sources — national statistical agencies, standards bodies, and published clinical or financial formulas — cited on the page where a specific source supports a specific figure.</p>

      <h2>How Content Is Verified</h2>
      <ol>
        <li><strong>Formula check.</strong> The implemented formula is compared against its published definition before a calculator ships.</li>
        <li><strong>Hand-verified examples.</strong> Each page's worked example is computed by hand and must reproduce exactly in the tool.</li>
        <li><strong>Automated regression tests.</strong> Every calculator is covered by a QA contract with independently computed expected results; the suite runs on every build, and a failing tool is not promoted to the sitemap. The current matrix is public on the <a href="/qa-dashboard.html" target="_blank" rel="noopener">QA dashboard</a>.</li>
      </ol>

      <h2>Who Writes and Reviews It</h2>
      <p>CalcProMaster is built and maintained by its developer, whose background spans mathematics and software engineering. Content is written and reviewed by the same person who maintains the calculation engine and its test suite — not by external contributors. The developer is not a licensed financial advisor or medical professional; finance and health pages carry explicit disclaimers stating this, and results are presented as math education, not professional advice.</p>

      <h2>Corrections</h2>
      <p>Found an error in a formula, example, or explanation? Email <a href="mailto:calpromaster@gmail.com">calpromaster@gmail.com</a> with the page URL and what you expected. Confirmed errors are fixed and re-tested before the next build; we aim to respond within 2-3 business days.</p>

      <h2>Updates</h2>
      <p>When a formula, default rate, or convention changes, the affected pages are regenerated and re-tested. Pages are not redated cosmetically — a page's review date changes only when its content actually changes.</p>

      <h2>Advertising &amp; Independence</h2>
      <p>Ads and affiliate links never determine calculation results, formulas, or recommendations. Any sponsored placement is labeled. See our <a href="/privacy">Privacy Policy</a> for data practices — calculations run entirely in your browser.</p>
    </div>
  `;

  // STEP 1F: About Page
  const ABOUT_PAGE = `
    <div class="legal-page">
      <h1>About CalcProMaster</h1>

      <h2>Our Mission</h2>
      <p>CalcProMaster provides free, fast, and accurate online calculators for everyday life, finance, health, math, science, and more. Our goal is to make complex calculations simple and accessible to everyone.</p>

      <h2>What Makes CalcProMaster Different</h2>
      <ul>
        <li><strong>1201+ calculators:</strong> From mortgages to BMI, loan payoffs to unit conversions—everything in one place</li>
        <li><strong>Step-by-Step Solutions:</strong> Understand the math behind the results</li>
        <li><strong>No Sign-Up Required:</strong> Use any calculator instantly, no account needed</li>
        <li><strong>Privacy-First:</strong> All calculations run in your browser, nothing stored on our servers</li>
        <li><strong>100% Free:</strong> No hidden fees, paywalls, or premium tiers</li>
        <li><strong>Mobile-Friendly:</strong> Works perfectly on phones, tablets, and desktops</li>
        <li><strong>Offline-Capable:</strong> Install as a PWA and use without internet</li>
      </ul>

      <h2>Who We Are</h2>
      <!-- MANUAL ACTION (optional): apna naam/credentials yahan add karo jab chaaho —
           niche ek professional generic bio hai jo launch ke liye ready hai -->
      <p>CalcProMaster is built by a dedicated developer with a strong background in mathematics, software engineering, and data accuracy. What started as a small collection of personal calculation tools grew into a public library of <strong>1201+ free online calculators</strong> spanning finance, health, science, engineering, education, and everyday life.</p>\n      <p>Every calculator page is held to a documented standard: the formula, a worked example, and the assumptions appear beside each result. Our <a href=\"/editorial-policy\">editorial policy</a> governs how content is written and corrected, each page carries a visible <em>Last reviewed</em> stamp showing when its formulas and explanations were last verified, and a public formula QA dashboard documents how results are tested. Found an error? The <a href=\"/contact\">contact page</a> reaches the maintainer directly — corrections are applied and re-reviewed, not just acknowledged.</p>
      <p>Every calculator on this site is designed with the same standards: verified formulas, transparent step-by-step explanations, and rigorous testing against real-world scenarios. We believe a calculator is only as good as its accuracy — which is why each tool documents its assumptions and limitations openly, and why our finance and health calculators always carry clear disclaimers.</p>
      <p>CalcProMaster runs entirely in your browser. No accounts, no hidden costs — just fast, honest calculation tools that anyone can use, from students checking homework to families planning budgets. Calculations run locally; optional analytics and advertising only activate if you consent via our cookie banner.</p>

      <h2>Our Commitment to Quality</h2>
      <p>Every calculator on CalcProMaster is built with:</p>
      <ul>
        <li>Verified formulas from authoritative sources</li>
        <li>Thorough testing with edge cases</li>
        <li>Clear explanations of assumptions and limitations</li>
        <li>Regular updates to reflect changes in standards and regulations</li>
      </ul>

      <h2>How We Verify Formulas</h2>
      <p>Accuracy here is a process, not a claim. Three layers back every calculator:</p>
      <ol>
        <li><strong>Published formulas only.</strong> Each tool implements a standard, publicly documented formula — the amortization equation lenders use, Mifflin-St Jeor for basal metabolic rate, the Euclidean algorithm for GCD — and names it in the page's "How It Works" section.</li>
        <li><strong>Hand-verified worked examples.</strong> Every page shows a worked example with expected values, checked by hand against the formula before it ships, so you can confirm the arithmetic yourself.</li>
        <li><strong>Automated QA contract.</strong> Each calculator is covered by an automated test suite with independently computed expected results. The suite runs on every build; a tool that fails its formula contract is not promoted to the sitemap. The full matrix is public on our <a href="/qa-dashboard.html" target="_blank" rel="noopener">QA dashboard</a>.</li>
      </ol>
      <p>Where real-world outcomes depend on facts no formula can know — your lender's fee schedule, your tax situation, market movements — the calculator's limitations section says so explicitly. Read the full <a href="/editorial-policy">editorial policy</a> for how content is written, reviewed and corrected.</p>

      <h2>Transparency</h2>
      <p>CalcProMaster is supported by non-intrusive advertising (Google AdSense) and we may earn commissions from affiliate links. This does not affect our calculator results, which are always unbiased and algorithm-based.</p>

      <h2>Open Source</h2>
      <p>Many of our calculation formulas and methodologies are documented in each calculator's "How It Works" section. We believe in transparency and education.</p>

      <h2>Get in Touch</h2>
      <p>Have feedback, found a bug, or want to suggest a new calculator? We'd love to hear from you! Visit our <a href="/contact" onclick="event.preventDefault();Router.navigate('/contact')">Contact page</a>.</p>
    </div>
  `;

  // STEP 1G: Contact Page
  const CONTACT_PAGE = `
    <div class="legal-page">
      <h1>Contact CalcProMaster</h1>

      <h2>Get in Touch</h2>
      <p>We're here to help! Whether you have a question, found a bug, want to suggest a new calculator, or just want to say hi, we'd love to hear from you.</p>

      <h2>Email Us</h2>
      <p>For general inquiries, feedback, bug reports, or calculator requests:</p>
      <p class="contact-email"><a href="mailto:calpromaster@gmail.com"><strong>calpromaster@gmail.com</strong></a></p>

      <h2>Business &amp; Partnership Inquiries</h2>
      <p>Interested in affiliate partnerships, sponsored placements, content collaborations, or backlink exchanges? We love working with brands and publishers who care about useful, privacy-first tools. Email us at <a href="mailto:calpromaster@gmail.com"><strong>calpromaster@gmail.com</strong></a> with the subject line <em>Partnership</em> and we typically reply within 2-3 business days.</p>
      <p>We accept a limited number of <strong>sponsored recommendation placements</strong> in our calculator result pages (clearly labeled "Recommended"), as well as <strong>guest content and editorial backlinks</strong> on our reference sections. All partnerships are disclosed and never affect calculation results.</p>

      <h2>What to Include in Your Message</h2>
      <p>To help us respond quickly, please include:</p>
      <ul>
        <li><strong>For bug reports:</strong> Which calculator, what you entered, what result you expected vs. what you got, and your browser/device</li>
        <li><strong>For calculator requests:</strong> What you want to calculate and why existing calculators don't meet your needs</li>
        <li><strong>For partnerships:</strong> Your brand/company, the type of collaboration, and a sample link or placement you have in mind</li>
        <li><strong>For general feedback:</strong> Be specific! "The mortgage calculator is confusing" is less helpful than "The mortgage calculator should show monthly breakdown"</li>
      </ul>

      <h2>Recommended Resources &amp; Partners</h2>
      <p>We carefully curate a short list of trusted resources we personally use and recommend alongside our tools. These links may include affiliate relationships — when you buy through them we may earn a small commission at no extra cost to you. It never affects our calculator results, which remain unbiased and algorithm-based.</p>
      <ul class="partner-list">
        <li>📈 <a href="https://www.investopedia.com/" rel="nofollow noopener sponsored" target="_blank">Investopedia</a> — financial education and definitions</li>
        <li>💳 <a href="https://www.nerdwallet.com/" rel="nofollow noopener sponsored" target="_blank">NerdWallet</a> — rate and card comparisons</li>
        <li>📊 <a href="https://www.semrush.com/" rel="nofollow noopener sponsored" target="_blank">Semrush</a> — SEO and keyword research</li>
        <li>🔗 <a href="https://ahrefs.com/" rel="nofollow noopener sponsored" target="_blank">Ahrefs</a> — backlink analysis</li>
        <li>🩺 <a href="https://www.who.int/health-topics" rel="nofollow noopener" target="_blank">WHO Health Topics</a> — health standards (editorial reference)</li>
      </ul>
      <p class="legal-note">Want to be listed here? Email <a href="mailto:calpromaster@gmail.com">calpromaster@gmail.com</a> with the subject <em>Partnership</em>.</p>

      <h2>Response Time</h2>
      <p>We typically respond within 2-3 business days. For urgent issues (calculator down, major bug), we aim to respond within 24 hours.</p>

      <h2>Privacy Note</h2>
      <p>When you email us, we collect your email address and message content only to respond to your inquiry. We do not add you to mailing lists or share your information with third parties. See our <a href="/privacy" onclick="event.preventDefault();Router.navigate('/privacy')">Privacy Policy</a> for details.</p>

      <h2>Alternative Contact (Future)</h2>
      <p>We're working on adding a contact form and social media channels. Check back soon!</p>
    </div>
  `;

  // STEP 1: Cookie Policy
  const COOKIE_POLICY = `
    <div class="legal-page">
      <h1>Cookie Policy</h1>
      <p class="legal-meta">Last Updated: July 26, 2026</p>

      <h2>What Are Cookies?</h2>
      <p>Cookies are small text files stored on your device by websites you visit. CalcProMaster uses minimal cookies and primarily relies on localStorage (similar to cookies but stored only in your browser).</p>

      <h2>What We Use</h2>

      <h3>Essential (Always Active):</h3>
      <ul>
        <li><strong>localStorage:</strong> Stores your calculation history, favorites, preferences, and settings. This is NOT a cookie and never leaves your device.</li>
        <li><strong>Cookie consent choice:</strong> Remembers whether you accepted or rejected non-essential cookies.</li>
      </ul>

      <h3>Non-Essential (Your Choice):</h3>
      <ul>
        <li><strong>Google Analytics cookies:</strong> If you consent, Google Analytics uses cookies to collect anonymous usage statistics (which calculators are popular, page views, etc.). You can opt out via our cookie banner.</li>
        <li><strong>Google AdSense cookies:</strong> If you consent, Google AdSense uses cookies for ad personalization. You can opt out via our cookie banner or use an ad blocker.</li>
      </ul>

      <h2>We Do NOT Use:</h2>
      <ul>
        <li>Tracking cookies that follow you across websites</li>
        <li>Third-party marketing cookies (except Google Analytics/AdSense if you consent)</li>
        <li>Social media tracking pixels</li>
        <li>Fingerprinting or other invasive tracking methods</li>
      </ul>

      <h2>Your Choices</h2>
      <p>You can control cookies via:</p>
      <ul>
        <li><strong>Our cookie banner:</strong> Appears on your first visit. Choose "Accept All" or "Reject Non-Essential".</li>
        <li><strong>Browser settings:</strong> Most browsers let you block or delete cookies. Note: Blocking essential localStorage will prevent favorites/history from working.</li>
        <li><strong>Ad blockers:</strong> Browser extensions can block advertising and tracking cookies.</li>
      </ul>

      <h2>Third-Party Cookies</h2>
      <p>If you consent, Google Analytics and Google AdSense may set their own cookies. Their use is governed by:</p>
      <ul>
        <li><a href="https://policies.google.com/technologies/cookies" target="_blank">Google Cookie Policy</a></li>
        <li><a href="https://policies.google.com/privacy" target="_blank">Google Privacy Policy</a></li>
      </ul>

      <h2>Changes to This Policy</h2>
      <p>We may update this Cookie Policy from time to time. Changes will be posted here with an updated date.</p>

      <h2>Contact</h2>
      <p>Questions about cookies? Email us at <strong>calpromaster@gmail.com</strong></p>
    </div>
  `;

  // Return all content
  return {
    TERMS_OF_SERVICE,
    FINANCIAL_DISCLAIMER,
    HEALTH_DISCLAIMER,
    PRIVACY_POLICY,
    GENERAL_DISCLAIMER,
    ABOUT_PAGE,
    CONTACT_PAGE,
    COOKIE_POLICY,
    EDITORIAL_POLICY,

    // Helper function to get content by page type
    getContent: function(pageType) {
      switch(pageType) {
        case 'terms': return this.TERMS_OF_SERVICE;
        case 'disclaimer-finance': return this.FINANCIAL_DISCLAIMER;
        case 'disclaimer-health': return this.HEALTH_DISCLAIMER;
        case 'disclaimer-general': return this.GENERAL_DISCLAIMER;
        case 'privacy': return this.PRIVACY_POLICY;
        case 'cookies': return this.COOKIE_POLICY;
        case 'about': return this.ABOUT_PAGE;
        case 'contact': return this.CONTACT_PAGE;
        case 'editorial-policy': return this.EDITORIAL_POLICY;
        default: return '<p>Page content not found.</p>';
      }
    }
  };
})();

if (typeof window !== 'undefined') {
  window.LegalPages = LegalPages;
}
