'use client';

import { useMemo, useState } from 'react';
import dynamic from 'next/dynamic';
import core from '@calcpro-js/core.js';
import excelFormulas from '@calcpro-js/excel-formulas.js';

// Lazy-load the chart renderer — Recharts (~100 KB) only ships to the client
// when a tool actually produces a chart, keeping chart-less tool pages lean.
const ChartSection = dynamic(() => import('./ChartSection'), {
  ssr: false,
  loading: () => null,
});

// ====== ResultPanel — displays the calculation output ======
// Mirrors the vanilla rendering rules:
//  - result.result  → escaped (or allow-list sanitized when isHtml: true)
//  - result.extra   → escaped
//  - result.chart   → trusted SVG string generated by our own Charts module
//  - tool.steps()   → step-by-step solution list
export default function ResultPanel({ tool, values, result, error, calculating }) {
  const Security = useMemo(() => (typeof window !== 'undefined' ? (window.Security || core.Security) : core.Security), []);
  const [copied, setCopied] = useState(false);

  // Spreadsheet formula (Gap 2) — CalculatorSoup-style copyable Excel/Sheets cell
  const excelEntry = excelFormulas && typeof excelFormulas.has === 'function' && excelFormulas.has(tool?.id)
    ? { formula: excelFormulas.build(tool.id, values), hint: excelFormulas.EXCEL_FORMULAS[tool.id]?.hint || '' }
    : null;

  if (error) {
    return (
      <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">
        <strong className="block mb-1">Calculation error</strong>
        {String(error)}
        <p className="mt-2 text-xs text-red-500">Please verify your input formats and try again.</p>
      </div>
    );
  }

  if (!result) {
    return (
      <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-6 text-center text-sm text-slate-500">
        {calculating ? 'Calculating…' : 'Enter values and the result appears instantly.'}
      </div>
    );
  }

  let html = '';
  if (result.result) {
    html = result.isHtml
      ? (Security.sanitizeOutput ? Security.sanitizeOutput(String(result.result)) : Security.sanitizeHtml(String(result.result)))
      : Security.sanitizeHtml(String(result.result));
  }

  // Step-by-step solution (optional hook)
  let steps = [];
  if (typeof tool.steps === 'function') {
    try {
      steps = tool.steps(values, result) || [];
    } catch (e) { /* steps are best-effort */ }
  }

  return (
    <div className="flex flex-col gap-4">
      {html && (
        <div
          className="result-main rounded-xl border border-primary/20 bg-gradient-to-br from-primary/5 to-transparent p-4 text-lg font-bold text-ink"
          dangerouslySetInnerHTML={{ __html: html }}
        />
      )}
      {result.extra && (
        <div
          className="text-sm text-slate-600"
          dangerouslySetInnerHTML={{ __html: result.extraHtml ? (Security.sanitizeOutput ? Security.sanitizeOutput(String(result.extra)) : Security.sanitizeHtml(String(result.extra))) : Security.sanitizeHtml(String(result.extra)) }}
        />
      )}
      {result.chart && (
        <ChartSection svg={result.chart} />
      )}
      {steps.length > 0 && (
        <details className="rounded-xl border border-slate-200 bg-white" open>
          <summary className="cursor-pointer select-none px-4 py-3 text-sm font-bold text-ink">
            📐 Formula &amp; Step-by-Step Solution
          </summary>
          <ol className="space-y-1.5 px-4 pb-4 text-sm text-slate-700">
            {steps.map((s, i) => (
              <li key={i} className="flex gap-2">
                <span className="mt-0.5 flex h-5 w-5 flex-none items-center justify-center rounded-full bg-primary/10 text-[11px] font-bold text-primary">{i + 1}</span>
                <span>{s}</span>
              </li>
            ))}
          </ol>
        </details>
      )}
      {excelEntry && excelEntry.formula && (
        <section className="rounded-xl border border-blue-200 bg-blue-50/60 p-4">
          <h3 className="mb-2 flex items-center gap-2 text-sm font-bold text-ink">
            📊 Spreadsheet Formula
            <span className="rounded-full bg-blue-600/10 px-2 py-0.5 text-[10px] font-bold text-blue-700">Excel / Google Sheets</span>
          </h3>
          <div className="flex flex-wrap items-center gap-2">
            <code className="min-w-0 flex-1 break-all rounded-lg border border-slate-200 bg-white px-3 py-2 font-mono text-[13px] text-blue-700">
              {excelEntry.formula}
            </code>
            <button
              type="button"
              onClick={() => {
                if (navigator.clipboard?.writeText) {
                  navigator.clipboard.writeText(excelEntry.formula);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 1600);
                }
              }}
              className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white transition hover:bg-blue-700"
            >
              {copied ? '✓ Copied' : '📋 Copy'}
            </button>
          </div>
          {excelEntry.hint && <p className="mt-2 text-xs text-slate-500">{excelEntry.hint}</p>}
        </section>
      )}
    </div>
  );
}
