// Batch A2b inserter — 48 genuinely unique tools, CRLF-safe.
// Usage: node scripts/a2b-batch.cjs [--check] [--qa]
//   --check  dry run: report what would change
//   --qa     also insert QA matrix rows into tests/unit/formula-qa-full.test.js
// Idempotent: skips any tool id already present in the target file.
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const T = {}; // file -> array of tool code strings (each starts with "{ id:", ends with "} }")

T['finance'] = [
  `{ id: 'prorated-rent', name: 'Prorated Rent Calculator', desc: 'Fair rent owed for a partial month of occupancy', kw: 'prorated rent calculator partial month move in move out daily rent',
    inputs: [{id:'rent',label:'Monthly Rent ($)',type:'number',def:1200},{id:'day',label:'Occupied Days',type:'number',def:15},{id:'days',label:'Days in Month',type:'number',def:30}],
    calc: function(v){ if(v.rent<=0||v.day<0||v.days<=0||v.day>v.days) return{result:'Enter rent > 0 and occupied days between 0 and days in month',chart:'',extra:''}; var daily=v.rent/v.days; var owed=daily*v.day; return{result:'Prorated Rent: $'+owed.toFixed(2),chart:Charts.bar([v.rent-owed,owed],['Unused days','Occupied days']),extra:'Daily rate: $'+daily.toFixed(2)+' | '+v.day+' of '+v.days+' days ('+(v.day/v.days*100).toFixed(1)+'% of month)'};},
    steps: function(v){ var daily=v.rent/v.days; var owed=daily*v.day; return['Formula: Owed = (Monthly rent ÷ days in month) × occupied days','Step 1: Daily rate = $'+v.rent.toFixed(2)+' ÷ '+v.days+' = $'+daily.toFixed(2),'Step 2: Owed = $'+daily.toFixed(2)+' × '+v.day+' days = $'+owed.toFixed(2),'Some leases use a 30-day standard month instead of the actual day count — agree on the method in the lease'];} }`,
  `{ id: 'dso', name: 'Days Sales Outstanding (DSO)', desc: 'Average days to collect payment after a credit sale', kw: 'dso calculator days sales outstanding receivables collection period working capital',
    inputs: [{id:'ar',label:'Accounts Receivable ($)',type:'number',def:50000},{id:'sales',label:'Credit Sales ($) for the Period',type:'number',def:600000},{id:'days',label:'Period Length (days)',type:'number',def:365}],
    calc: function(v){ if(v.sales<=0||v.days<=0) return{result:'Credit sales and period length must be positive',chart:'',extra:''}; var dso=v.ar/v.sales*v.days; return{result:'DSO: '+dso.toFixed(1)+' days',chart:Charts.gauge(dso,90),extra:'Receivables turn over '+(v.days/dso).toFixed(1)+'× per period | Under about 45 days is generally healthy'};},
    steps: function(v){ var dso=v.ar/v.sales*v.days; return['Formula: DSO = (Accounts receivable ÷ credit sales) × days in period','Step 1: AR ÷ Sales = $'+v.ar.toLocaleString()+' ÷ $'+v.sales.toLocaleString()+' = '+(v.ar/v.sales).toFixed(4),'Step 2: DSO = '+(v.ar/v.sales).toFixed(4)+' × '+v.days+' = '+dso.toFixed(1)+' days','Lower DSO means faster cash conversion; compare it against your stated payment terms'];} }`,
  `{ id: 'pe-ratio', name: 'P/E Ratio Calculator', desc: 'Price-to-earnings valuation multiple of a stock', kw: 'pe ratio calculator price to earnings stock valuation multiple earnings yield',
    inputs: [{id:'price',label:'Share Price ($)',type:'number',def:150},{id:'eps',label:'Earnings Per Share ($)',type:'number',def:6}],
    calc: function(v){ if(v.eps<=0||v.price<=0) return{result:'Price and EPS must be positive',chart:'',extra:''}; var pe=v.price/v.eps; return{result:'P/E Ratio: '+pe.toFixed(2),chart:Charts.gauge(pe,60),extra:'Earnings yield: '+(v.eps/v.price*100).toFixed(2)+'% (the inverse of P/E) | Compare within the same industry'};},
    steps: function(v){ var pe=v.price/v.eps; return['Formula: P/E = Share price ÷ Earnings per share','Step 1: P/E = $'+v.price+' ÷ $'+v.eps+' = '+pe.toFixed(2),'Step 2: Earnings yield = EPS ÷ price = '+(v.eps/v.price*100).toFixed(2)+'%','A high P/E implies growth expectations; a low P/E may signal value or risk — context matters more than the number alone'];} }`,
];

T['math'] = [
  `{ id: 'quartiles', name: 'Quartile Calculator', desc: 'Q1, median, Q3 and IQR of a data set', kw: 'quartile calculator q1 q3 interquartile range iqr five number summary box plot',
    inputs: [{id:'data',label:'Data (comma separated)',type:'text',def:'2,4,6,8,10,12,16'}],
    calc: function(v){ var a=v.data.split(',').map(Number); if(a.length<4||a.some(isNaN)) return{result:'Enter at least 4 numeric values',chart:'',extra:''}; a.sort(function(x,y){return x-y;}); var n=a.length; function med(arr){ var m=arr.length; return m%2 ? arr[(m-1)/2] : (arr[m/2-1]+arr[m/2])/2; } var q2=med(a); var lo=a.slice(0,Math.floor(n/2)); var hi=a.slice(Math.ceil(n/2)); var q1=med(lo); var q3=med(hi); var iqr=q3-q1; return{result:'Q1: '+q1+' | Median: '+q2+' | Q3: '+q3+' | IQR: '+iqr,chart:Charts.bar([q1,q2,q3],['Q1','Median','Q3']),extra:'n = '+n+' | Outlier fences: ['+(q1-1.5*iqr).toFixed(2)+', '+(q3+1.5*iqr).toFixed(2)+'] — values outside are potential outliers'};},
    steps: function(v){ var a=v.data.split(',').map(Number); a.sort(function(x,y){return x-y;}); var n=a.length; function med(arr){ var m=arr.length; return m%2 ? arr[(m-1)/2] : (arr[m/2-1]+arr[m/2])/2; } var q2=med(a); var q1=med(a.slice(0,Math.floor(n/2))); var q3=med(a.slice(Math.ceil(n/2))); return['Method: median-of-halves (Tukey / TI-83 style)','Step 1: Sorted data: '+a.join(', '),'Step 2: Median (Q2) = '+q2,'Step 3: Q1 = median of the lower half = '+q1+'; Q3 = median of the upper half = '+q3,'Step 4: IQR = Q3 − Q1 = '+(q3-q1)];} }`,
  `{ id: 'rms', name: 'Root Mean Square Calculator', desc: 'RMS (effective) value of a data set', kw: 'rms calculator root mean square effective value ac signal voltage',
    inputs: [{id:'data',label:'Values (comma separated)',type:'text',def:'3,4'}],
    calc: function(v){ var a=v.data.split(',').map(Number); if(!a.length||a.some(isNaN)) return{result:'Enter numeric values',chart:'',extra:''}; var ss=0; for(var i=0;i<a.length;i++) ss+=a[i]*a[i]; var rms=Math.sqrt(ss/a.length); var mean=a.reduce(function(s,x){return s+x;},0)/a.length; return{result:'RMS: '+rms.toFixed(4),chart:Charts.bar(a.map(Math.abs),a.map(function(_,i){return 'x'+(i+1);})),extra:'Mean of squares: '+(ss/a.length).toFixed(4)+' | n = '+a.length+' | Arithmetic mean for comparison: '+mean.toFixed(4)};},
    steps: function(v){ var a=v.data.split(',').map(Number); var ss=0; for(var i=0;i<a.length;i++) ss+=a[i]*a[i]; var rms=Math.sqrt(ss/a.length); return['Formula: RMS = √( (x₁² + … + xₙ²) ÷ n )','Step 1: Squares: '+a.map(function(x){return x+'²='+(x*x);}).join(', '),'Step 2: Mean of squares = '+(ss/a.length).toFixed(4),'Step 3: RMS = √'+(ss/a.length).toFixed(4)+' = '+rms.toFixed(4),'RMS is the effective magnitude — for a pure sine wave, RMS = peak ÷ √2'];} }`,
  `{ id: 'z-score', name: 'Z-Score Calculator', desc: 'Standard deviations a value sits from the mean', kw: 'z score calculator standard score normal distribution percentile sigma',
    inputs: [{id:'x',label:'Value (x)',type:'number',def:85},{id:'mean',label:'Mean (μ)',type:'number',def:70},{id:'sd',label:'Std Dev (σ)',type:'number',def:10}],
    calc: function(v){ if(v.sd<=0) return{result:'Std deviation must be positive',chart:'',extra:''}; function erf(x){ var s=x<0?-1:1; x=Math.abs(x); var t=1/(1+0.3275911*x); var y=1-((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+0.254829592)*t*Math.exp(-x*x); return s*y; } var z=(v.x-v.mean)/v.sd; var pct=50*(1+erf(z/Math.SQRT2)); return{result:'z = '+z.toFixed(2),chart:Charts.gauge(Math.abs(z),3),extra:'x is '+Math.abs(z).toFixed(2)+'σ '+(z>=0?'above':'below')+' the mean | Approx. percentile: '+pct.toFixed(1)+'%'};},
    steps: function(v){ if(v.sd<=0) return['Std deviation must be positive']; var z=(v.x-v.mean)/v.sd; return['Formula: z = (x − μ) ÷ σ','Step 1: Deviation = '+v.x+' − '+v.mean+' = '+(v.x-v.mean),'Step 2: z = '+(v.x-v.mean)+' ÷ '+v.sd+' = '+z.toFixed(2),'|z| > 2 is unusual under a normal distribution — about 5% of values lie outside ±2σ'];} }`,
  `{ id: 'covariance', name: 'Covariance Calculator', desc: 'How two variables move together, linearly', kw: 'covariance calculator sample population correlation direction relationship',
    inputs: [{id:'x',label:'X values (comma separated)',type:'text',def:'2,4,6,8'},{id:'y',label:'Y values (comma separated)',type:'text',def:'1,3,2,5'}],
    calc: function(v){ var x=v.x.split(',').map(Number), y=v.y.split(',').map(Number); if(x.length!==y.length||x.length<2||x.some(isNaN)||y.some(isNaN)) return{result:'Enter equal-length numeric lists (at least 2 pairs)',chart:'',extra:''}; var n=x.length; var mx=x.reduce(function(s,a){return s+a;},0)/n, my=y.reduce(function(s,a){return s+a;},0)/n; var sp=0; for(var i=0;i<n;i++) sp+=(x[i]-mx)*(y[i]-my); var covP=sp/n, covS=sp/(n-1); return{result:'Population Covariance: '+covP.toFixed(4),chart:Charts.bar(y,x.map(function(_,i){return 'i'+(i+1);})),extra:'Sample covariance (n−1): '+covS.toFixed(4)+' | '+(covP>0?'positive relationship':covP<0?'negative relationship':'no linear relationship')+' — magnitude is scale-dependent'};},
    steps: function(v){ var x=v.x.split(',').map(Number), y=v.y.split(',').map(Number); var n=x.length; var mx=x.reduce(function(s,a){return s+a;},0)/n, my=y.reduce(function(s,a){return s+a;},0)/n; var sp=0; for(var i=0;i<n;i++) sp+=(x[i]-mx)*(y[i]-my); return['Formula: cov = Σ(xᵢ−x̄)(yᵢ−ȳ) ÷ n (population)','Step 1: Means: x̄ = '+mx.toFixed(4)+', ȳ = '+my.toFixed(4),'Step 2: Σ of deviation products = '+sp.toFixed(4),'Step 3: Divide by n = '+n+' → '+ (sp/n).toFixed(4)+' (or n−1 = '+(n-1)+' for the sample version)'];} }`,
  `{ id: 'exponential-prob', name: 'Exponential Distribution Calculator', desc: 'P(X ≤ x) and P(X > x) for wait times', kw: 'exponential distribution calculator probability wait time rate lambda reliability',
    inputs: [{id:'rate',label:'Rate λ (events per unit time)',type:'number',def:0.5},{id:'x',label:'Time (x)',type:'number',def:2}],
    calc: function(v){ if(v.rate<=0||v.x<0) return{result:'Rate must be positive and time at least 0',chart:'',extra:''}; var le=1-Math.exp(-v.rate*v.x); return{result:'P(X ≤ x): '+(le*100).toFixed(2)+'%',chart:Charts.bar([le*100,(1-le)*100],['P(X ≤ x)','P(X > x)']),extra:'Mean wait: '+(1/v.rate).toFixed(3)+' | Median wait: '+(Math.LN2/v.rate).toFixed(3)+' | The exponential distribution is memoryless'};},
    steps: function(v){ var le=1-Math.exp(-v.rate*v.x); return['Formula: P(X ≤ x) = 1 − e^(−λx)','Step 1: λx = '+v.rate+' × '+v.x+' = '+(v.rate*v.x).toFixed(4),'Step 2: e^−'+(v.rate*v.x).toFixed(4)+' = '+Math.exp(-v.rate*v.x).toFixed(4),'Step 3: P(X ≤ x) = 1 − '+Math.exp(-v.rate*v.x).toFixed(4)+' = '+le.toFixed(4),'P(X > x) = e^(−λx) = '+Math.exp(-v.rate*v.x).toFixed(4)];} }`,
  `{ id: 'expected-value', name: 'Expected Value Calculator', desc: 'Probability-weighted average outcome', kw: 'expected value calculator probability weighted average outcomes ev decision making',
    inputs: [{id:'outcomes',label:'Outcomes (comma separated)',type:'text',def:'10,20,30'},{id:'probs',label:'Probabilities (comma separated)',type:'text',def:'0.2,0.3,0.5'}],
    calc: function(v){ var o=v.outcomes.split(',').map(Number), p=v.probs.split(',').map(Number); if(o.length!==p.length||!o.length||o.some(isNaN)||p.some(isNaN)) return{result:'Enter equal-length outcome and probability lists',chart:'',extra:''}; var sp=p.reduce(function(s,a){return s+a;},0); if(Math.abs(sp-1)>0.001) return{result:'Probabilities must sum to 1 (currently '+sp.toFixed(3)+')',chart:'',extra:''}; var ev=0; for(var i=0;i<o.length;i++) ev+=o[i]*p[i]; return{result:'Expected Value: '+ev.toFixed(4),chart:Charts.bar(o.map(function(x,i){return x*p[i];}),o.map(String)),extra:'Each outcome × its probability, summed | Positive EV favours repeating the bet; negative EV does not'};},
    steps: function(v){ var o=v.outcomes.split(',').map(Number), p=v.probs.split(',').map(Number); var ev=0; for(var i=0;i<o.length;i++) ev+=o[i]*p[i]; return['Formula: EV = Σ outcomeᵢ × probabilityᵢ','Step 1: Products: '+o.map(function(x,i){return x+'×'+p[i]+'='+(x*p[i]).toFixed(4);}).join(', '),'Step 2: Sum = '+ev.toFixed(4),'Long-run average per trial — individual outcomes still vary around it'];} }`,
  `{ id: 'euler-totient', name: 'Euler Totient Calculator', desc: 'Count of integers up to n that are coprime to n', kw: 'euler totient calculator phi function coprime rsa number theory',
    inputs: [{id:'n',label:'n',type:'number',def:36}],
    calc: function(v){ var n=Math.floor(v.n); if(n<1||n>1e7) return{result:'Enter an integer between 1 and 10,000,000',chart:'',extra:''}; var result=n, m=n; for(var p=2;p*p<=m;p++){ if(m%p===0){ while(m%p===0) m/=p; result-=result/p; } } if(m>1) result-=result/m; return{result:'φ('+n+') = '+result,chart:Charts.gauge(result,n),extra:(result/n*100).toFixed(1)+'% of integers up to '+n+' are coprime to it | φ is central to RSA key generation'};},
    steps: function(v){ var n=Math.floor(v.n); var result=n, m=n, fs=[]; for(var p=2;p*p<=m;p++){ if(m%p===0){ while(m%p===0) m/=p; fs.push(p); result-=result/p; } } if(m>1){ fs.push(m); result-=result/m; } return['Formula: φ(n) = n × Π(1 − 1/p) over the distinct primes p of n','Step 1: Distinct prime factors of '+n+': '+fs.join(', '),'Step 2: Apply each factor: φ = '+n+' × '+fs.map(function(p){return '(1−1/'+p+')';}).join(' × ')+' = '+result,'Counts integers k in 1..n with gcd(k, n) = 1'];} }`,
];

T['science'] = [
  `{ id: 'hooke-law', name: "Hooke's Law Calculator", desc: 'Spring force from stiffness and displacement', kw: "hooke's law calculator spring force constant elastic potential energy extension",
    inputs: [{id:'k',label:'Spring Constant k (N/m)',type:'number',def:200},{id:'x',label:'Displacement x (m)',type:'number',def:0.15}],
    calc: function(v){ if(v.k<0) return{result:'Spring constant cannot be negative',chart:'',extra:''}; var F=v.k*v.x; return{result:'Force: '+F.toFixed(2)+' N',chart:Charts.gauge(Math.abs(F),Math.max(v.k,1)),extra:'Elastic PE = ½kx² = '+(0.5*v.k*v.x*v.x).toFixed(4)+' J | Valid only while the spring stays within its elastic limit'};},
    steps: function(v){ var F=v.k*v.x; return["Formula: F = k × x",'Step 1: F = '+v.k+' N/m × '+v.x+' m = '+F.toFixed(2)+' N','Stored energy: PE = ½kx² = '+(0.5*v.k*v.x*v.x).toFixed(4)+' J','Beyond the elastic limit the spring deforms permanently and Hooke\u2019s law no longer applies'];} }`,
  `{ id: 'mach-number', name: 'Mach Number Calculator', desc: 'Speed as a multiple of the local speed of sound', kw: 'mach number calculator speed of sound supersonic transonic aircraft aviation',
    inputs: [{id:'v',label:'Object Speed (m/s)',type:'number',def:680},{id:'a',label:'Speed of Sound (m/s)',type:'number',def:340}],
    calc: function(v){ if(v.a<=0||v.v<0) return{result:'Speed of sound must be positive',chart:'',extra:''}; var M=v.v/v.a; var regime=M<0.8?'subsonic':M<1.2?'transonic':M<5?'supersonic':'hypersonic'; return{result:'Mach '+M.toFixed(3),chart:Charts.gauge(M,5),extra:'Regime: '+regime+' | At 20 °C at sea level, a ≈ 343 m/s — it falls with altitude'};},
    steps: function(v){ var M=v.v/v.a; return['Formula: M = v ÷ a (object speed ÷ local speed of sound)','Step 1: M = '+v.v+' ÷ '+v.a+' = '+M.toFixed(3),'Step 2: Regime thresholds: <0.8 subsonic, 0.8–1.2 transonic, 1.2–5 supersonic, >5 hypersonic','Compare against the LOCAL speed of sound — temperature changes it significantly'];} }`,
  `{ id: 'stefan-boltzmann', name: 'Stefan-Boltzmann Calculator', desc: 'Radiated power per unit area of a hot surface', kw: 'stefan boltzmann calculator blackbody radiation thermal emission emissivity',
    inputs: [{id:'T',label:'Temperature T (kelvin)',type:'number',def:300},{id:'emis',label:'Emissivity ε (0–1)',type:'number',def:1}],
    calc: function(v){ if(v.T<=0||v.emis<0||v.emis>1) return{result:'Temperature above 0 K and emissivity between 0 and 1 required',chart:'',extra:''}; var P=5.670374419e-8*v.emis*Math.pow(v.T,4); return{result:'Radiated Power: '+P.toFixed(2)+' W/m²',chart:Charts.gauge(v.T,1000),extra:'σ = 5.670×10⁻⁸ W·m⁻²·K⁻⁴ | Doubling absolute temperature multiplies output 16-fold (T⁴ law)'};},
    steps: function(v){ var P=5.670374419e-8*v.emis*Math.pow(v.T,4); return['Formula: P = ε · σ · T⁴ (per square metre)','Step 1: T⁴ = '+v.T+'⁴ = '+Math.pow(v.T,4).toExponential(3),'Step 2: P = '+v.emis+' × 5.670×10⁻⁸ × '+Math.pow(v.T,4).toExponential(3)+' = '+P.toFixed(2)+' W/m²','A blackbody has ε = 1; real surfaces radiate less (polished metals can be ε ≈ 0.05)'];} }`,
  `{ id: 'coulomb-law', name: "Coulomb's Law Calculator", desc: 'Electrostatic force between two point charges', kw: "coulomb's law calculator electrostatic force point charges permittivity",
    inputs: [{id:'q1',label:'Charge q₁ (µC)',type:'number',def:1},{id:'q2',label:'Charge q₂ (µC)',type:'number',def:1},{id:'r',label:'Separation r (m)',type:'number',def:0.1}],
    calc: function(v){ if(v.r<=0) return{result:'Separation must be positive',chart:'',extra:''}; var F=8.9875517923e9*(v.q1*1e-6)*(v.q2*1e-6)/(v.r*v.r); return{result:'Force: '+F.toFixed(4)+' N',chart:Charts.gauge(Math.abs(F),10),extra:(v.q1*v.q2>0?'Repulsive — like charges':'Attractive — opposite charges')+' | k = 8.99×10⁹ N·m²/C² | Force obeys the inverse-square law'};},
    steps: function(v){ var F=8.9875517923e9*(v.q1*1e-6)*(v.q2*1e-6)/(v.r*v.r); return["Formula: F = k·q₁·q₂ ÷ r²",'Step 1: Convert µC → C: q₁ = '+(v.q1*1e-6).toExponential(2)+' C, q₂ = '+(v.q2*1e-6).toExponential(2)+' C','Step 2: r² = '+v.r+'² = '+(v.r*v.r).toExponential(2)+' m²','Step 3: F = 8.99×10⁹ × '+((v.q1*1e-6)*(v.q2*1e-6)).toExponential(2)+' ÷ '+(v.r*v.r).toExponential(2)+' = '+F.toFixed(4)+' N'];} }`,
  `{ id: 'photon-energy', name: 'Photon Energy Calculator', desc: 'Energy of light from its wavelength', kw: 'photon energy calculator wavelength planck constant eV joules frequency',
    inputs: [{id:'wl',label:'Wavelength (nm)',type:'number',def:500}],
    calc: function(v){ if(v.wl<=0) return{result:'Wavelength must be positive',chart:'',extra:''}; var J=6.62607015e-34*2.99792458e8/(v.wl*1e-9); var eV=J/1.602176634e-19; return{result:'Energy: '+eV.toFixed(3)+' eV',chart:Charts.gauge(eV,5),extra:'In joules: '+J.toExponential(3)+' J | Visible light spans roughly 1.6–3.3 eV (700–380 nm)'};},
    steps: function(v){ var J=6.62607015e-34*2.99792458e8/(v.wl*1e-9); var eV=J/1.602176634e-19; return['Formula: E = hc ÷ λ','Step 1: hc = 6.626×10⁻³⁴ × 3.00×10⁸ = 1.986×10⁻²⁵ J·m','Step 2: λ = '+v.wl+' nm = '+(v.wl*1e-9).toExponential(2)+' m','Step 3: E = '+J.toExponential(3)+' J = '+eV.toFixed(3)+' eV (1 eV = 1.602×10⁻¹⁹ J)'];} }`,
  `{ id: 'debroglie', name: 'De Broglie Wavelength Calculator', desc: 'Matter-wave wavelength of a moving particle', kw: 'de broglie wavelength calculator matter wave electron quantum momentum',
    inputs: [{id:'m',label:'Mass (kg, scientific notation ok)',type:'number',def:9.11e-31},{id:'v',label:'Velocity (m/s)',type:'number',def:1e6}],
    calc: function(v){ if(v.m<=0||v.v<=0) return{result:'Mass and velocity must be positive',chart:'',extra:''}; var L=6.62607015e-34/(v.m*v.v); return{result:'Wavelength: '+L.toExponential(3)+' m',chart:Charts.gauge(L*1e9,2),extra:'In nanometres: '+(L*1e9).toFixed(4)+' nm | Smaller momentum → longer wavelength (p = mv)'};},
    steps: function(v){ var L=6.62607015e-34/(v.m*v.v); return['Formula: λ = h ÷ p = h ÷ (mv)','Step 1: Momentum p = '+v.m.toExponential(2)+' × '+v.v.toExponential(2)+' = '+(v.m*v.v).toExponential(2)+' kg·m/s','Step 2: λ = 6.626×10⁻³⁴ ÷ '+(v.m*v.v).toExponential(2)+' = '+L.toExponential(3)+' m','Wave behaviour becomes noticeable when λ approaches the size of obstacles the particle meets'];} }`,
  `{ id: 'rocket-equation', name: 'Rocket Equation Calculator', desc: 'Tsiolkovsky delta-v from exhaust velocity and mass ratio', kw: 'rocket equation calculator tsiolkovsky delta v exhaust velocity mass ratio propulsion',
    inputs: [{id:'ve',label:'Effective Exhaust Velocity (m/s)',type:'number',def:3000},{id:'m0',label:'Initial (wet) Mass (kg)',type:'number',def:10000},{id:'mf',label:'Final (dry) Mass (kg)',type:'number',def:4000}],
    calc: function(v){ if(v.mf<=0||v.m0<=v.mf) return{result:'Final mass must be positive and less than initial mass',chart:'',extra:''}; var dv=v.ve*Math.log(v.m0/v.mf); return{result:'Delta-v: '+dv.toFixed(0)+' m/s',chart:Charts.gauge(dv,10000),extra:'Mass ratio: '+(v.m0/v.mf).toFixed(3)+' | Reaching low Earth orbit needs roughly 9,400 m/s of delta-v including losses'};},
    steps: function(v){ var dv=v.ve*Math.log(v.m0/v.mf); return['Formula (Tsiolkovsky): Δv = ve × ln(m0 ÷ mf)','Step 1: Mass ratio = '+v.m0+' ÷ '+v.mf+' = '+(v.m0/v.mf).toFixed(4),'Step 2: ln('+(v.m0/v.mf).toFixed(4)+') = '+Math.log(v.m0/v.mf).toFixed(4),'Step 3: Δv = '+v.ve+' × '+Math.log(v.m0/v.mf).toFixed(4)+' = '+dv.toFixed(0)+' m/s','Delta-v is additive: staging lets a rocket exceed what one burn of its engines implies'];} }`,
  `{ id: 'carbon-dating', name: 'Carbon Dating Calculator', desc: 'Radiocarbon age from the remaining C-14 fraction', kw: 'carbon dating calculator radiocarbon age c14 half life archaeology fossils',
    inputs: [{id:'pct',label:'C-14 Remaining (% of living level)',type:'number',def:25},{id:'hl',label:'C-14 Half-life (years)',type:'number',def:5730}],
    calc: function(v){ if(v.pct<=0||v.pct>100||v.hl<=0) return{result:'Remaining % must be in (0, 100] and half-life positive',chart:'',extra:''}; var t=v.hl*Math.log(100/v.pct)/Math.LN2; return{result:'Age: '+t.toLocaleString('en-US',{maximumFractionDigits:0})+' years',chart:Charts.gauge(v.pct,100),extra:'Half-lives elapsed: '+(t/v.hl).toFixed(3)+' | Practical dating range is roughly 50,000 years — beyond that too little C-14 remains'};},
    steps: function(v){ var t=v.hl*Math.log(100/v.pct)/Math.LN2; return['Formula: t = half-life × log₂(100 ÷ % remaining)','Step 1: Fraction remaining = '+(v.pct/100).toFixed(4),'Step 2: log₂('+(100/v.pct).toFixed(4)+') = '+Math.log(100/v.pct).toFixed(4)+' / ln2','Step 3: t = '+v.hl+' × '+(t/v.hl).toFixed(4)+' = '+t.toLocaleString('en-US',{maximumFractionDigits:0})+' years','Assumes the original C-14 level matched the modern atmosphere — calibration curves correct for drift'];} }`,
  `{ id: 'calorimetry', name: 'Heat Energy Calculator', desc: 'Thermal energy for a temperature change (Q = mcΔT)', kw: 'heat energy calculator calorimetry specific heat q m c delta t joules',
    inputs: [{id:'m',label:'Mass (kg)',type:'number',def:0.5},{id:'c',label:'Specific Heat (J/kg·K)',type:'number',def:4186},{id:'dT',label:'Temperature Change ΔT (°C or K)',type:'number',def:20}],
    calc: function(v){ if(v.m<=0||v.c<=0) return{result:'Mass and specific heat must be positive',chart:'',extra:''}; var Q=v.m*v.c*v.dT; return{result:'Heat Energy: '+Q.toLocaleString('en-US',{maximumFractionDigits:0})+' J',chart:Charts.gauge(Math.abs(Q),50000),extra:(Q>=0?'Energy absorbed':'Energy released')+': '+(Math.abs(Q)/1000).toFixed(2)+' kJ = '+(Math.abs(Q)/4184).toFixed(1)+' food calories (kcal)'};},
    steps: function(v){ var Q=v.m*v.c*v.dT; return['Formula: Q = m × c × ΔT','Step 1: Q = '+v.m+' kg × '+v.c+' J/kg·K × '+v.dT+' K','Step 2: Q = '+Q.toLocaleString('en-US',{maximumFractionDigits:0})+' J = '+(Q/1000).toFixed(2)+' kJ','Water\u2019s c = 4186 J/kg·K is unusually high — that is why it is an effective coolant'];} }`,
  `{ id: 'freezing-depression', name: 'Freezing Point Depression Calculator', desc: 'How much a solute lowers the freezing point (ΔTf = i·Kf·m)', kw: 'freezing point depression calculator colligative property molality kf solvent antifreeze',
    inputs: [{id:'i',label:"van 't Hoff Factor i",type:'number',def:1},{id:'kf',label:'Cryoscopic Constant Kf (°C·kg/mol)',type:'number',def:1.86},{id:'m',label:'Molality (mol/kg solvent)',type:'number',def:1.5}],
    calc: function(v){ if(v.kf<=0||v.m<0||v.i<0) return{result:'Kf must be positive; i and molality must be 0 or more',chart:'',extra:''}; var dT=v.i*v.kf*v.m; return{result:'Freezing Point Lowered: '+dT.toFixed(2)+' °C',chart:Charts.gauge(dT,10),extra:'New freezing point: '+(0-dT).toFixed(2)+' °C (pure water freezes at 0 °C) | Water Kf = 1.86, benzene Kf = 5.12'};},
    steps: function(v){ var dT=v.i*v.kf*v.m; return['Formula: ΔTf = i × Kf × m','Step 1: i = '+v.i+' (1 for nonelectrolytes, ≈2 for NaCl, ≈3 for CaCl₂)','Step 2: ΔTf = '+v.i+' × '+v.kf+' × '+v.m+' = '+dT.toFixed(2)+' °C','Step 3: Solution freezes at −'+dT.toFixed(2)+' °C instead of 0 °C','This is why road salt and antifreeze work — dissolved particles depress the freezing point'];} }`,
  `{ id: 'air-density', name: 'Air Density Calculator', desc: 'Dry-air density from pressure and temperature', kw: 'air density calculator atmosphere pressure temperature engine tuning altitude performance',
    inputs: [{id:'p',label:'Air Pressure (Pa)',type:'number',def:101325},{id:'T',label:'Temperature (K)',type:'number',def:288.15}],
    calc: function(v){ if(v.p<=0||v.T<=0) return{result:'Pressure and temperature must be positive',chart:'',extra:''}; var rho=v.p/(287.05*v.T); return{result:'Air Density: '+rho.toFixed(4)+' kg/m³',chart:Charts.gauge(rho,2),extra:'ISA sea-level reference: 1.225 kg/m³ | In lb/ft³: '+(rho*0.062428).toFixed(4)+' | Thinner (hotter or higher) air reduces engine and aero performance'};},
    steps: function(v){ var rho=v.p/(287.05*v.T); return['Formula (ideal gas): ρ = p ÷ (R·T), R for dry air = 287.05 J/kg·K','Step 1: R·T = 287.05 × '+v.T+' = '+(287.05*v.T).toFixed(0),'Step 2: ρ = '+v.p+' ÷ '+(287.05*v.T).toFixed(0)+' = '+rho.toFixed(4)+' kg/m³','Compare with 1.225 kg/m³ (ISA sea level, 15 °C) to gauge density altitude effects'];} }`,
];

T['health'] = [
  `{ id: 'creatinine-clearance', name: 'Creatinine Clearance Calculator', desc: 'Cockcroft-Gault estimate of kidney filtration', kw: 'creatinine clearance calculator cockcroft gault kidney function renal dosing gfr estimate',
    inputs: [{id:'age',label:'Age (years)',type:'number',def:40},{id:'wt',label:'Weight (kg)',type:'number',def:70},{id:'scr',label:'Serum Creatinine (mg/dL)',type:'number',def:1},{id:'sex',label:'Sex',type:'select',opts:[{v:'m',l:'Male'},{v:'f',l:'Female'}],def:'m'}],
    calc: function(v){ if(v.age<=0||v.wt<=0||v.scr<=0) return{result:'Age, weight and creatinine must be positive',chart:'',extra:''}; var crcl=(140-v.age)*v.wt/(72*v.scr); if(v.sex==='f') crcl*=0.85; var band=crcl>=90?'normal kidney function':crcl>=60?'mild reduction':crcl>=30?'moderate reduction':'severe reduction'; return{result:'CrCl: '+crcl.toFixed(1)+' mL/min',chart:Charts.gauge(crcl,120),extra:'Cockcroft-Gault estimate — '+band+' | Used for drug dosing; not a direct GFR measurement'};},
    steps: function(v){ var crcl=(140-v.age)*v.wt/(72*v.scr); if(v.sex==='f') crcl*=0.85; return['Formula (Cockcroft-Gault): CrCl = (140 − age) × weight ÷ (72 × serum creatinine)','Step 1: (140 − '+v.age+') × '+v.wt+' = '+((140-v.age)*v.wt),'Step 2: ÷ (72 × '+v.scr+') = '+((140-v.age)*v.wt/(72*v.scr)).toFixed(2)+' mL/min',v.sex==='f'?'Step 3: × 0.85 for female patients = '+crcl.toFixed(2)+' mL/min':'Male patients need no sex adjustment'];} }`,
  `{ id: 'anion-gap', name: 'Anion Gap Calculator', desc: 'Metabolic acidosis screening from serum electrolytes', kw: 'anion gap calculator metabolic acidosis electrolytes sodium chloride bicarbonate',
    inputs: [{id:'na',label:'Sodium Na⁺ (mEq/L)',type:'number',def:140},{id:'cl',label:'Chloride Cl⁻ (mEq/L)',type:'number',def:104},{id:'hco3',label:'Bicarbonate HCO₃⁻ (mEq/L)',type:'number',def:24},{id:'alb',label:'Albumin (g/dL, optional)',type:'number',def:4}],
    calc: function(v){ var ag=v.na-(v.cl+v.hco3); var corr=ag+2.5*(4-(v.alb||4)); return{result:'Anion Gap: '+ag.toFixed(1)+' mEq/L',chart:Charts.gauge(ag,30),extra:'Albumin-corrected gap: '+corr.toFixed(1)+' | Normal ≈ 8–12 (without K⁺) | A high gap suggests lactic or ketoacidosis, toxins, or renal failure'};},
    steps: function(v){ var ag=v.na-(v.cl+v.hco3); return['Formula: AG = Na⁺ − (Cl⁻ + HCO₃⁻)','Step 1: Cl⁻ + HCO₃⁻ = '+v.cl+' + '+v.hco3+' = '+(v.cl+v.hco3),'Step 2: AG = '+v.na+' − '+(v.cl+v.hco3)+' = '+ag.toFixed(1)+' mEq/L','For every 1 g/dL albumin below 4, add 2.5 to the measured gap — low albumin masks a high gap'];} }`,
  `{ id: 'qtc', name: 'QTc Calculator (Bazett)', desc: 'Heart-rate corrected QT interval from an ECG', kw: 'qtc calculator bazett corrected qt interval ecg long qt syndrome',
    inputs: [{id:'qt',label:'Measured QT (ms)',type:'number',def:400},{id:'hr',label:'Heart Rate (bpm)',type:'number',def:60}],
    calc: function(v){ if(v.qt<=0||v.hr<=0) return{result:'QT and heart rate must be positive',chart:'',extra:''}; var rr=60/v.hr; var qtc=v.qt/Math.sqrt(rr); var flag=qtc>470?'prolonged — review medications and electrolytes':qtc>450?'borderline — repeat the ECG':'within normal range (< 450 ms)'; return{result:'QTc: '+qtc.toFixed(0)+' ms',chart:Charts.gauge(qtc,600),extra:'RR interval: '+rr.toFixed(2)+' s | '+flag+' | Bazett over-corrects at high heart rates — consider Fridericia there'};},
    steps: function(v){ var rr=60/v.hr; var qtc=v.qt/Math.sqrt(rr); return['Formula (Bazett): QTc = QT ÷ √RR, RR = 60 ÷ heart rate','Step 1: RR = 60 ÷ '+v.hr+' = '+rr.toFixed(3)+' s','Step 2: √RR = '+Math.sqrt(rr).toFixed(4),'Step 3: QTc = '+v.qt+' ÷ '+Math.sqrt(rr).toFixed(4)+' = '+qtc.toFixed(0)+' ms','Values above 470 ms (women) or 450 ms (men) raise long-QT concern'];} }`,
  `{ id: 'ponderal-index', name: 'Ponderal Index Calculator', desc: 'Height-normalised body mass — fairer than BMI at height extremes', kw: 'ponderal index calculator body mass infant neonatal corpulence height normalized',
    inputs: [{id:'wt',label:'Weight (kg)',type:'number',def:70},{id:'ht',label:'Height (m)',type:'number',def:1.75}],
    calc: function(v){ if(v.wt<=0||v.ht<=0) return{result:'Weight and height must be positive',chart:'',extra:''}; var pi=v.wt/Math.pow(v.ht,3); return{result:'Ponderal Index: '+pi.toFixed(2)+' kg/m³',chart:Charts.gauge(pi,30),extra:'BMI equivalent view: BMI = '+(v.wt/(v.ht*v.ht)).toFixed(1)+' | PI scales with height cubed, so very tall or short adults compare more fairly'};},
    steps: function(v){ var pi=v.wt/Math.pow(v.ht,3); return['Formula: PI = weight ÷ height³','Step 1: height³ = '+v.ht+'³ = '+Math.pow(v.ht,3).toFixed(4),'Step 2: PI = '+v.wt+' ÷ '+Math.pow(v.ht,3).toFixed(4)+' = '+pi.toFixed(2)+' kg/m³','Newborn PI reference: about 2.5 (normal) to 3.0+ (mothers with diabetes)'];} }`,
];

T['tech-digital'] = [
  `{ id: 'subnet-cidr', name: 'Subnet Calculator (CIDR)', desc: 'Network, broadcast, mask and host count from CIDR', kw: 'subnet calculator cidr ipv4 netmask broadcast hosts network range',
    inputs: [{id:'ip',label:'IPv4 Address',type:'text',def:'192.168.1.10'},{id:'prefix',label:'Prefix (/bits)',type:'number',def:26}],
    calc: function(v){ var o=v.ip.split('.').map(Number); if(o.length!==4||o.some(isNaN)||o.some(function(x){return x<0||x>255;})||v.prefix<0||v.prefix>32) return{result:'Enter a valid IPv4 address and a prefix of 0–32',chart:'',extra:''}; var ip=((o[0]<<24)|(o[1]<<16)|(o[2]<<8)|o[3])>>>0; var mask=v.prefix===0?0:((0xFFFFFFFF<<(32-v.prefix))>>>0); var net=(ip&mask)>>>0; var bc=(net|(~mask>>>0))>>>0; function s(n){return [(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255].join('.');} var total=Math.pow(2,32-v.prefix); var hosts=v.prefix>=31?total:(total-2); return{result:'Network: '+s(net)+'/'+v.prefix,chart:Charts.bar([total,hosts],['Total addresses','Usable hosts']),extra:'Mask: '+s(mask)+' | Broadcast: '+s(bc)+' | Usable range: '+s(v.prefix>=31?net:net+1)+' – '+s(v.prefix>=31?bc:bc-1)+' ('+hosts+' hosts)'};},
    steps: function(v){ var o=v.ip.split('.').map(Number); var ip=((o[0]<<24)|(o[1]<<16)|(o[2]<<8)|o[3])>>>0; var mask=v.prefix===0?0:((0xFFFFFFFF<<(32-v.prefix))>>>0); var net=(ip&mask)>>>0; function s(n){return [(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255].join('.');} var total=Math.pow(2,32-v.prefix); return['Formula: mask = 32−prefix host bits set to 0; network = IP AND mask','Step 1: /'+v.prefix+' leaves '+(32-v.prefix)+' host bits → '+total+' addresses','Step 2: Mask = '+s(mask),'Step 3: Network = '+s(net)+'; subtract 2 (network + broadcast) for usable hosts unless /31 or /32'];} }`,
  `{ id: 'video-bitrate', name: 'Video File Size Calculator', desc: 'Storage needed from bitrate and duration', kw: 'video file size calculator bitrate duration mb gb streaming upload estimate',
    inputs: [{id:'mbps',label:'Video Bitrate (Mbps)',type:'number',def:8},{id:'min',label:'Duration (minutes)',type:'number',def:10},{id:'audio',label:'Audio Bitrate (kbps)',type:'number',def:128}],
    calc: function(v){ if(v.mbps<=0||v.min<=0) return{result:'Bitrate and duration must be positive',chart:'',extra:''}; var bits=(v.mbps*1e6+v.audio*1000)*v.min*60; var MB=bits/8/1e6; return{result:'File Size: '+MB.toFixed(1)+' MB',chart:Charts.bar([v.mbps*1e6,v.audio*1000],['Video (bps)','Audio (bps)']),extra:'Total bitrate: '+((v.mbps*1e6+v.audio*1000)/1e6).toFixed(3)+' Mbps | In GB: '+(MB/1000).toFixed(3)+' | Per hour at these settings: '+(MB*6/1000).toFixed(2)+' GB'};},
    steps: function(v){ var bits=(v.mbps*1e6+v.audio*1000)*v.min*60; var MB=bits/8/1e6; return['Formula: size = (video + audio bitrate) × seconds ÷ 8','Step 1: Total bitrate = '+v.mbps+' Mbps + '+(v.audio/1000)+' Mbps = '+((v.mbps*1e6+v.audio*1000)/1e6).toFixed(3)+' Mbps','Step 2: Bits = '+((v.mbps*1e6+v.audio*1000)/1e6).toFixed(3)+'e6 × '+(v.min*60)+' s = '+bits.toExponential(3),'Step 3: ÷ 8 → bytes = '+MB.toFixed(1)+' MB','Container overhead adds roughly 1–2% beyond the raw stream size'];} }`,
];

T['construction'] = [
  `{ id: 'stair-stringer', name: 'Stair Stringer Calculator', desc: 'Riser height and tread layout for a staircase', kw: 'stair stringer calculator riser height tread depth total rise run building code',
    inputs: [{id:'rise',label:'Total Rise (inches)',type:'number',def:105},{id:'risers',label:'Number of Risers',type:'number',def:14},{id:'tread',label:'Tread Depth (inches)',type:'number',def:10}],
    calc: function(v){ if(v.rise<=0||v.risers<=0) return{result:'Total rise and riser count must be positive',chart:'',extra:''}; var rh=v.rise/v.risers; var run=v.tread*(v.risers-1); var r2=rh*2+v.tread; return{result:'Riser Height: '+rh.toFixed(3)+' in',chart:Charts.bar([rh,v.tread],['Riser (in)','Tread (in)']),extra:'Total run: '+run.toFixed(1)+' in ('+(run/12).toFixed(2)+' ft) | Comfort rule 2r+t = '+r2.toFixed(1)+' in (aim 24–25) | Most codes cap riser at 7¾ in'};},
    steps: function(v){ var rh=v.rise/v.risers; var run=v.tread*(v.risers-1); return['Formula: riser height = total rise ÷ number of risers','Step 1: '+v.rise+' in ÷ '+v.risers+' = '+rh.toFixed(3)+' in per riser','Step 2: Total run = tread × (risers − 1) = '+v.tread+' × '+(v.risers-1)+' = '+run.toFixed(1)+' in','Step 3: Check 2r + t = '+(rh*2+v.tread).toFixed(1)+' in — between 24 and 25 in feels comfortable'];} }`,
  `{ id: 'siding-squares', name: 'Siding Squares Calculator', desc: 'Siding squares needed from wall area and openings', kw: 'siding squares calculator vinyl wall area waste factor material estimate',
    inputs: [{id:'len',label:'Wall Length (ft)',type:'number',def:40},{id:'ht',label:'Wall Height (ft)',type:'number',def:10},{id:'walls',label:'Number of Walls',type:'number',def:4},{id:'openings',label:'Openings to Deduct (sq ft)',type:'number',def:100},{id:'waste',label:'Waste Factor (%)',type:'number',def:10}],
    calc: function(v){ if(v.len<=0||v.ht<=0||v.walls<=0) return{result:'Dimensions and wall count must be positive',chart:'',extra:''}; var gross=v.len*v.ht*v.walls; var net=Math.max(0,gross-v.openings); var sq=net/100; var withWaste=sq*(1+v.waste/100); return{result:'Siding Needed: '+withWaste.toFixed(1)+' squares',chart:Charts.donut([net,v.openings],['Wall area','Openings']),extra:'Gross '+gross.toFixed(0)+' sq ft − openings = '+net.toFixed(0)+' sq ft = '+sq.toFixed(2)+' squares (1 square = 100 sq ft) | Gables and story walls add area — measure them separately'};},
    steps: function(v){ var gross=v.len*v.ht*v.walls; var net=Math.max(0,gross-v.openings); var sq=net/100; var withWaste=sq*(1+v.waste/100); return['Formula: squares = net wall area ÷ 100, then × (1 + waste %)','Step 1: Gross = '+v.len+' × '+v.ht+' × '+v.walls+' = '+gross.toFixed(0)+' sq ft','Step 2: Net = '+gross.toFixed(0)+' − '+v.openings+' = '+net.toFixed(0)+' sq ft → '+sq.toFixed(2)+' squares','Step 3: With '+v.waste+'% waste: '+withWaste.toFixed(1)+' squares to order'];} }`,
  `{ id: 'soffit-area', name: 'Soffit Area Calculator', desc: 'Soffit material area from building perimeter and overhang', kw: 'soffit area calculator overhang eave vented panels attic ventilation',
    inputs: [{id:'len',label:'Building Length (ft)',type:'number',def:60},{id:'wid',label:'Building Width (ft)',type:'number',def:30},{id:'oh',label:'Overhang (ft)',type:'number',def:1.5}],
    calc: function(v){ if(v.len<=0||v.wid<=0||v.oh<0) return{result:'Dimensions must be positive',chart:'',extra:''}; var per=2*(v.len+v.wid); var area=per*v.oh; var ventNote=area>=150?'1 sq ft of vent per 150 sq ft attic → you can vent '+(area/150).toFixed(1)+' sq ft of attic through this soffit':'add '+(150-area).toFixed(0)+' more sq ft to vent a 150 sq ft attic footprint'; return{result:'Soffit Area: '+area.toFixed(1)+' sq ft',chart:Charts.bar([per,v.oh],['Perimeter (ft)','Overhang (ft)']),extra:'Perimeter: '+per.toFixed(1)+' ft | '+ventNote};},
    steps: function(v){ var per=2*(v.len+v.wid); var area=per*v.oh; return['Formula: soffit area = building perimeter × overhang width','Step 1: Perimeter = 2 × ('+v.len+' + '+v.wid+') = '+per.toFixed(1)+' ft','Step 2: Area = '+per.toFixed(1)+' × '+v.oh+' = '+area.toFixed(1)+' sq ft','Vented soffit panels usually cover about 0.5–1 sq ft of net free vent each — check the product rating'];} }`,
  `{ id: 'post-hole-concrete', name: 'Post Hole Concrete Calculator', desc: 'Concrete volume for fence post holes', kw: 'post hole concrete calculator fence posts bags cubic yards volume',
    inputs: [{id:'holes',label:'Number of Holes',type:'number',def:8},{id:'dia',label:'Hole Diameter (inches)',type:'number',def:12},{id:'depth',label:'Hole Depth (inches)',type:'number',def:36},{id:'post',label:'Post Width (inches)',type:'number',def:4}],
    calc: function(v){ if(v.holes<=0||v.dia<=0||v.depth<=0) return{result:'Hole count, diameter and depth must be positive',chart:'',extra:''}; var holeV=Math.PI*Math.pow(v.dia/24,2)*(v.depth/12); var postV=Math.pow(v.post/12,2)*(v.depth/12); var net=Math.max(0,holeV-postV)*v.holes; var yd=net/27; var bags=Math.ceil(net/0.45); return{result:'Concrete: '+yd.toFixed(2)+' yd³',chart:Charts.donut([holeV*v.holes,postV*v.holes],['Hole volume','Post volume']),extra:'= '+net.toFixed(1)+' cu ft after displacing the post | ≈ '+bags+' × 60-lb bags (0.45 cu ft) | Order about 10% extra'};},
    steps: function(v){ var holeV=Math.PI*Math.pow(v.dia/24,2)*(v.depth/12); var postV=Math.pow(v.post/12,2)*(v.depth/12); var net=Math.max(0,holeV-postV)*v.holes; return['Formula: cylinder volume πr²h, minus the post volume, × number of holes','Step 1: Per hole = π×'+(v.dia/24).toFixed(4)+'² × '+(v.depth/12).toFixed(2)+' = '+holeV.toFixed(4)+' cu ft','Step 2: Post displaces '+postV.toFixed(4)+' cu ft → net '+(holeV-postV).toFixed(4)+' cu ft each','Step 3: × '+v.holes+' holes = '+net.toFixed(1)+' cu ft = '+(net/27).toFixed(2)+' yd³'];} }`,
  `{ id: 'fence-panel', name: 'Fence Panel Calculator', desc: 'Panels and posts for a fence run', kw: 'fence panel calculator posts pickets linear feet panel spacing',
    inputs: [{id:'len',label:'Fence Length (ft)',type:'number',def:100},{id:'panel',label:'Panel Width (ft)',type:'number',def:6}],
    calc: function(v){ if(v.len<=0||v.panel<=0) return{result:'Length and panel width must be positive',chart:'',extra:''}; var panels=Math.ceil(v.len/v.panel); var posts=panels+1; var last=v.len-(panels-1)*v.panel; return{result:panels+' panels | '+posts+' posts',chart:Charts.bar([panels,posts],['Panels','Posts']),extra:'Last panel cut to '+last.toFixed(2)+' ft | Posts sit at every panel joint plus both ends — add one pair per gate'};},
    steps: function(v){ var panels=Math.ceil(v.len/v.panel); var posts=panels+1; var last=v.len-(panels-1)*v.panel; return['Step 1: Panels = ceiling(length ÷ panel width) = ceil('+v.len+' ÷ '+v.panel+') = '+panels,'Step 2: Posts = panels + 1 = '+posts+' (one at each end of every panel)','Step 3: Last panel is ripped to '+last.toFixed(2)+' ft to close the run exactly'];} }`,
  `{ id: 'gravel-driveway', name: 'Gravel Driveway Calculator', desc: 'Gravel volume and tonnage for a driveway', kw: 'gravel driveway calculator tons cubic yards depth crushed stone coverage',
    inputs: [{id:'len',label:'Length (ft)',type:'number',def:40},{id:'wid',label:'Width (ft)',type:'number',def:12},{id:'depth',label:'Depth (inches)',type:'number',def:4}],
    calc: function(v){ if(v.len<=0||v.wid<=0||v.depth<=0) return{result:'Dimensions must be positive',chart:'',extra:''}; var cuft=v.len*v.wid*v.depth/12; var yd=cuft/27; var tons=yd*1.4; return{result:'Gravel Needed: '+tons.toFixed(2)+' tons',chart:Charts.bar([yd,tons],['Cubic yards','Tons']),extra:'Volume: '+cuft.toFixed(0)+' cu ft = '+yd.toFixed(2)+' yd³ | Crushed stone runs about 1.4 tons per yd³ | Order 5–10% extra for compaction'};},
    steps: function(v){ var cuft=v.len*v.wid*v.depth/12; var yd=cuft/27; var tons=yd*1.4; return['Step 1: Volume = '+v.len+' × '+v.wid+' × '+(v.depth/12).toFixed(4)+' ft = '+cuft.toFixed(1)+' cu ft','Step 2: ÷ 27 = '+yd.toFixed(2)+' cubic yards','Step 3: × 1.4 tons/yd³ ≈ '+tons.toFixed(2)+' tons','Two 3-inch lifts compact better than one deep pass; geotextile under the gravel stops rutting'];} }`,
  `{ id: 'insulation-batts', name: 'Insulation Coverage Calculator', desc: 'Batts or rolls needed for a framed area', kw: 'insulation coverage calculator batts rolls r value sq ft bags attic wall',
    inputs: [{id:'area',label:'Area to Insulate (sq ft)',type:'number',def:1000},{id:'cover',label:'Coverage per Roll / Batt (sq ft)',type:'number',def:40}],
    calc: function(v){ if(v.area<=0||v.cover<=0) return{result:'Area and coverage must be positive',chart:'',extra:''}; var n=v.area/v.cover; return{result:'Units Needed: '+Math.ceil(n),chart:Charts.gauge(v.cover,100),extra:'Exact coverage: '+n.toFixed(2)+' units | Buy one extra for offcuts, compressed edges, and odd cavities'};},
    steps: function(v){ var n=v.area/v.cover; return['Step 1: Units = area ÷ coverage per unit = '+v.area+' ÷ '+v.cover+' = '+n.toFixed(2),'Step 2: Round up to '+Math.ceil(n)+' full units','Step 3: Match the R-value to your climate zone — coverage numbers already assume the labelled thickness'];} }`,
];

T['engineering'] = [
  `{ id: 'section-modulus', name: 'Section Modulus Calculator', desc: 'Elastic section modulus of a rectangle or circle', kw: 'section modulus calculator beam bending rectangle circle elastic design',
    inputs: [{id:'shape',label:'Shape',type:'select',opts:[{v:'rect',l:'Rectangle (b × h)'},{v:'circle',l:'Circle (diameter d)'}],def:'rect'},{id:'b',label:'Width b (mm)',type:'number',def:50},{id:'h',label:'Height h / Diameter d (mm)',type:'number',def:100}],
    calc: function(v){ if(v.h<=0||(v.shape==='rect'&&v.b<=0)) return{result:'Dimensions must be positive',chart:'',extra:''}; var S=v.shape==='circle'?Math.PI*Math.pow(v.h,3)/32:v.b*v.h*v.h/6; return{result:'Section Modulus: '+S.toLocaleString('en-US',{maximumFractionDigits:1})+' mm³',chart:Charts.gauge(v.h,200),extra:'Bending stress σ = M ÷ S | Rectangle: bh²/6; circle: πd³/32 — depth matters more than width (h² term)'};},
    steps: function(v){ var S=v.shape==='circle'?Math.PI*Math.pow(v.h,3)/32:v.b*v.h*v.h/6; return['Formula: '+(v.shape==='circle'?'S = πd³/32':'S = bh²/6'),'Step 1: '+(v.shape==='circle'?'d³ = '+v.h+'³ = '+Math.pow(v.h,3):'h² = '+v.h+'² = '+(v.h*v.h)),'Step 2: S = '+S.toLocaleString('en-US',{maximumFractionDigits:1})+' mm³','Use S to size beams: for a given moment M, bending stress falls as S grows'];} }`,
  `{ id: 'shaft-torsion', name: 'Shaft Torsion Stress Calculator', desc: 'Shear stress in a solid circular shaft under torque', kw: 'shaft torsion calculator shear stress solid circular torque polar moment',
    inputs: [{id:'T',label:'Torque T (N·m)',type:'number',def:100},{id:'d',label:'Shaft Diameter (mm)',type:'number',def:20}],
    calc: function(v){ if(v.d<=0) return{result:'Diameter must be positive',chart:'',extra:''}; var tau=16*v.T/(Math.PI*Math.pow(v.d/1000,3)); var J=Math.PI*Math.pow(v.d/1000,4)/32; return{result:'Shear Stress: '+(tau/1e6).toFixed(2)+' MPa',chart:Charts.gauge(tau/1e6,200),extra:'Polar moment J = πd⁴/32 = '+J.toExponential(3)+' m⁴ | τ = T·r/J gives the same value at the outer surface'};},
    steps: function(v){ var tau=16*v.T/(Math.PI*Math.pow(v.d/1000,3)); return['Formula: τmax = 16T ÷ (πd³)','Step 1: d = '+(v.d/1000)+' m → d³ = '+Math.pow(v.d/1000,3).toExponential(3)+' m³','Step 2: τ = 16 × '+v.T+' ÷ (π × '+Math.pow(v.d/1000,3).toExponential(3)+') = '+(tau/1e6).toFixed(2)+' MPa','Stress scales with 1/d³ — halving the diameter multiplies stress eightfold'];} }`,
  `{ id: 'pulley-speed', name: 'Pulley Speed Calculator', desc: 'Driven pulley rpm from the diameter ratio', kw: 'pulley speed calculator rpm diameter ratio belt drive driven sheave',
    inputs: [{id:'d1',label:'Driver Diameter (mm)',type:'number',def:100},{id:'n1',label:'Driver Speed (rpm)',type:'number',def:1750},{id:'d2',label:'Driven Diameter (mm)',type:'number',def:200}],
    calc: function(v){ if(v.d1<=0||v.d2<=0||v.n1<=0) return{result:'Diameters and driver speed must be positive',chart:'',extra:''}; var n2=v.d1*v.n1/v.d2; return{result:'Driven Speed: '+n2.toFixed(1)+' rpm',chart:Charts.gauge(n2,Math.max(v.n1,1)),extra:'Speed ratio: '+(v.d2/v.d1).toFixed(2)+':1 | Belt speed ≈ π × d₁ × n₁ = '+(Math.PI*v.d1/1000*v.n1).toFixed(0)+' m/min (same on both pulleys)'};},
    steps: function(v){ var n2=v.d1*v.n1/v.d2; return['Formula: n2 = (d1 × n1) ÷ d2 — belt speed is equal on both pulleys','Step 1: d1 × n1 = '+v.d1+' × '+v.n1+' = '+(v.d1*v.n1),'Step 2: ÷ d2 ('+v.d2+') = '+n2.toFixed(1)+' rpm','A larger driven pulley turns slower but delivers more torque — power (ignoring losses) stays the same'];} }`,
  `{ id: 'manning-flow', name: 'Manning Flow Calculator', desc: 'Full-pipe discharge via the Manning equation', kw: 'manning equation calculator pipe flow discharge slope roughness gravity main',
    inputs: [{id:'D',label:'Pipe Diameter (m)',type:'number',def:0.3},{id:'n',label:'Manning n (roughness)',type:'number',def:0.013},{id:'S',label:'Slope S (m/m)',type:'number',def:0.01}],
    calc: function(v){ if(v.D<=0||v.n<=0||v.S<=0) return{result:'Diameter, n and slope must be positive',chart:'',extra:''}; var A=Math.PI*v.D*v.D/4; var R=v.D/4; var Q=A*Math.pow(R,2/3)*Math.sqrt(v.S)/v.n; return{result:'Discharge: '+Q.toFixed(4)+' m³/s',chart:Charts.gauge(Q,1),extra:'Area: '+A.toFixed(5)+' m² | Hydraulic radius: '+R.toFixed(4)+' m | Velocity: '+(Q/A).toFixed(3)+' m/s | ≈ '+(Q*15850.32).toFixed(0)+' gpm'};},
    steps: function(v){ var A=Math.PI*v.D*v.D/4; var R=v.D/4; var Q=A*Math.pow(R,2/3)*Math.sqrt(v.S)/v.n; return['Formula: Q = (1/n) × A × R^(2/3) × √S','Step 1: A = πD²/4 = '+A.toFixed(5)+' m²; full-pipe R = D/4 = '+R.toFixed(4)+' m','Step 2: R^(2/3) = '+Math.pow(R,2/3).toFixed(4)+'; √S = '+Math.sqrt(v.S).toFixed(4),'Step 3: Q = '+(1/v.n).toFixed(2)+' × '+A.toFixed(5)+' × '+Math.pow(R,2/3).toFixed(4)+' × '+Math.sqrt(v.S).toFixed(4)+' = '+Q.toFixed(4)+' m³/s'];} }`,
  `{ id: 'orifice-flow', name: 'Orifice Flow Calculator', desc: 'Discharge through a sharp-edged orifice', kw: 'orifice flow calculator discharge coefficient tank drainage torricelli head',
    inputs: [{id:'cd',label:'Discharge Coefficient Cd',type:'number',def:0.62},{id:'d',label:'Orifice Diameter (m)',type:'number',def:0.05},{id:'h',label:'Head Above Orifice (m)',type:'number',def:2}],
    calc: function(v){ if(v.cd<=0||v.d<=0||v.h<0) return{result:'Cd and diameter must be positive; head at least 0',chart:'',extra:''}; var A=Math.PI*v.d*v.d/4; var Q=v.cd*A*Math.sqrt(2*9.81*v.h); return{result:'Flow: '+(Q*1000).toFixed(2)+' L/s',chart:Charts.gauge(Q,0.05),extra:'Area: '+(A*1e4).toFixed(2)+' cm² | Jet velocity: '+Math.sqrt(2*9.81*v.h).toFixed(2)+' m/s (Torricelli) | Sharp edge Cd ≈ 0.61–0.63'};},
    steps: function(v){ var A=Math.PI*v.d*v.d/4; var Q=v.cd*A*Math.sqrt(2*9.81*v.h); return['Formula: Q = Cd × A × √(2gh)','Step 1: A = πd²/4 = '+(A*1e4).toFixed(2)+' cm²','Step 2: √(2 × 9.81 × '+v.h+') = '+Math.sqrt(2*9.81*v.h).toFixed(3)+' m/s','Step 3: Q = '+v.cd+' × '+A.toExponential(3)+' × '+Math.sqrt(2*9.81*v.h).toFixed(3)+' = '+(Q*1000).toFixed(2)+' L/s'];} }`,
  `{ id: 'three-phase-power', name: 'Three Phase Power Calculator', desc: 'Real power of a balanced three-phase load', kw: 'three phase power calculator kw voltage current power factor apparent reactive',
    inputs: [{id:'V',label:'Line Voltage (V)',type:'number',def:400},{id:'I',label:'Line Current (A)',type:'number',def:20},{id:'pf',label:'Power Factor (0–1)',type:'number',def:0.85}],
    calc: function(v){ if(v.V<=0||v.I<=0||v.pf<=0||v.pf>1) return{result:'Voltage and current positive; power factor between 0 and 1',chart:'',extra:''}; var P=Math.sqrt(3)*v.V*v.I*v.pf; var S=Math.sqrt(3)*v.V*v.I; return{result:'Real Power: '+(P/1000).toFixed(2)+' kW',chart:Charts.gauge(v.pf,1),extra:'Apparent power: '+(S/1000).toFixed(2)+' kVA | Reactive: '+(Math.sqrt(Math.max(0,S*S-P*P))/1000).toFixed(2)+' kVAR | Improving pf toward 1 cuts current for the same kW'};},
    steps: function(v){ var P=Math.sqrt(3)*v.V*v.I*v.pf; return['Formula: P = √3 × V × I × pf','Step 1: √3 × '+v.V+' × '+v.I+' = '+(Math.sqrt(3)*v.V*v.I).toFixed(0)+' VA (apparent)','Step 2: × pf '+v.pf+' = '+P.toFixed(0)+' W = '+(P/1000).toFixed(2)+' kW','Balanced-load assumption — unbalanced phases need per-phase calculation'];} }`,
  `{ id: 'ups-sizing', name: 'UPS Battery Sizing Calculator', desc: 'Battery amp-hours for a load and runtime target', kw: 'ups battery sizing calculator ah runtime backup load inverter efficiency',
    inputs: [{id:'load',label:'Load (W)',type:'number',def:600},{id:'min',label:'Backup Time (minutes)',type:'number',def:30},{id:'V',label:'Battery Bank Voltage (V)',type:'number',def:12},{id:'eff',label:'Inverter Efficiency (%)',type:'number',def:85}],
    calc: function(v){ if(v.load<=0||v.min<=0||v.V<=0||v.eff<=0||v.eff>100) return{result:'Load, time and voltage must be positive; efficiency 0–100%',chart:'',extra:''}; var ah=v.load*(v.min/60)/(v.V*v.eff/100); return{result:'Battery Capacity: '+ah.toFixed(1)+' Ah',chart:Charts.gauge(ah,200),extra:'Energy needed: '+(v.load*v.min/60/1000).toFixed(2)+' kWh | Add about 25% margin for aging and cold → '+(ah*1.25).toFixed(1)+' Ah'};},
    steps: function(v){ var ah=v.load*(v.min/60)/(v.V*v.eff/100); return['Formula: Ah = (load × hours) ÷ (V × efficiency)','Step 1: Energy = '+v.load+' W × '+(v.min/60).toFixed(2)+' h = '+(v.load*v.min/60).toFixed(0)+' Wh','Step 2: Delivered from batteries = Wh ÷ '+v.V+' V ÷ '+(v.eff/100)+' = '+ah.toFixed(1)+' Ah','Lead-acid rated at the 20-hour rate delivers less at high draw — check the discharge curve for short runtimes'];} }`,
];

T['everyday'] = [
  `{ id: 'poker-flush', name: 'Poker Flush Odds Calculator', desc: 'Probability of flush-type hands in 5-card poker', kw: 'poker flush odds calculator 5 card probability combinations straight flush',
    inputs: [{id:'matches',label:'Cards of the Same Suit Needed (1–5 of 5)',type:'number',def:5}],
    calc: function(v){ function C(n,k){ if(k<0||k>n) return 0; k=Math.min(k,n-k); var r=1; for(var i=1;i<=k;i++) r=r*(n-k+i)/i; return r; } var need=Math.min(5,Math.max(1,Math.round(v.matches))); var ways=C(4,1)*C(13,need)*C(39,5-need); var total=C(52,5); var p=ways/total; return{result:'Probability: '+(p*100).toFixed(4)+'%',chart:Charts.bar([p*100,100-p*100],['This hand','Other hands']),extra:'1 in '+Math.round(1/p).toLocaleString()+' hands | Ways: '+ways.toLocaleString()+' of '+total.toLocaleString()+' | A 5-card flush includes straight flushes — subtract 40 ways to exclude them'};},
    steps: function(v){ function C(n,k){ if(k<0||k>n) return 0; k=Math.min(k,n-k); var r=1; for(var i=1;i<=k;i++) r=r*(n-k+i)/i; return r; } var need=Math.min(5,Math.max(1,Math.round(v.matches))); var ways=C(4,1)*C(13,need)*C(39,5-need); var total=C(52,5); return['Formula: P = (suit choices × suit-card picks × other-suit fill) ÷ C(52,5)','Step 1: Ways = C(4,1) × C(13,'+need+') × C(39,'+(5-need)+') = '+ways.toLocaleString(),'Step 2: Total 5-card hands = C(52,5) = '+total.toLocaleString(),'Step 3: P = '+(ways/total*100).toFixed(4)+'% ≈ 1 in '+Math.round(total/ways).toLocaleString()];} }`,
  `{ id: 'easter-date', name: 'Easter Date Calculator', desc: 'Western Easter Sunday from the Gregorian computus', kw: 'easter date calculator computus good friday western sunday ash wednesday',
    inputs: [{id:'year',label:'Year (1583–4099)',type:'number',def:2026}],
    calc: function(v){ var y=Math.floor(v.year); if(y<1583||y>4099) return{result:'Enter a year between 1583 and 4099 (Gregorian era)',chart:'',extra:''}; var a=y%19, b=Math.floor(y/100), c=y%100, d=Math.floor(b/4), e=b%4, f=Math.floor((b+8)/25), g=Math.floor((b-f+1)/3), h=(19*a+b-d-g+15)%30, i=Math.floor(c/4), k=c%4, l=(32+2*e+2*i-h-k)%7, m=Math.floor((a+11*h+22*l)/451), mo=Math.floor((h+l-7*m+114)/31), day=((h+l-7*m+114)%31)+1; var names=['','January','February','March','April','May','June']; return{result:'Easter '+y+': '+names[mo]+' '+day,chart:Charts.bar([mo,12],['Month #','Months in year']),extra:'Good Friday is two days earlier; Ash Wednesday 46 days before | Orthodox Easter can differ — this is the Western date'};},
    steps: function(v){ var y=Math.floor(v.year); var a=y%19, b=Math.floor(y/100), c=y%100, d=Math.floor(b/4), e=b%4, f=Math.floor((b+8)/25), g=Math.floor((b-f+1)/3), h=(19*a+b-d-g+15)%30, i=Math.floor(c/4), k=c%4, l=(32+2*e+2*i-h-k)%7, m=Math.floor((a+11*h+22*l)/451), mo=Math.floor((h+l-7*m+114)/31), day=((h+l-7*m+114)%31)+1; var names=['','January','February','March','April','May','June']; return['Anonymous Gregorian computus (1583 onward)','Step 1: Golden number a = '+a+'; epact term h = '+h,'Step 2: Weekday offset l = '+l+'; correction m = '+m,'Step 3: Easter '+y+' = '+names[mo]+' '+day];} }`,
  `{ id: 'day-of-week', name: 'Day of Week Calculator', desc: 'Weekday for any calendar date', kw: 'day of week calculator what day was date weekday calendar finder',
    inputs: [{id:'date',label:'Date (YYYY-MM-DD)',type:'text',def:'2000-01-01'}],
    calc: function(v){ var d=new Date(v.date+'T12:00:00Z'); if(isNaN(d.getTime())) return{result:'Enter a valid date as YYYY-MM-DD',chart:'',extra:''}; var names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']; var start=new Date(Date.UTC(d.getUTCFullYear(),0,1)); var doy=Math.floor((d-start)/86400000)+1; return{result:names[d.getUTCDay()],chart:Charts.bar([doy,365],['Day of year','Days in year']),extra:v.date+' is day '+doy+' of '+d.getUTCFullYear()+' | Uses the proleptic Gregorian calendar for past centuries'};},
    steps: function(v){ var d=new Date(v.date+'T12:00:00Z'); var names=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']; return['Step 1: Parse '+v.date+' as a UTC date','Step 2: Weekday index = '+d.getUTCDay(),'Step 3: '+(isNaN(d.getTime())?'invalid date':names[d.getUTCDay()]),'ISO 8601 weeks start on Monday; Sunday-based calendars differ on week numbering'];} }`,
  `{ id: 'moon-phase', name: 'Moon Phase Calculator', desc: 'Lunar phase for a given date', kw: 'moon phase calculator lunar cycle synodic month full moon new moon illumination',
    inputs: [{id:'date',label:'Date (YYYY-MM-DD)',type:'text',def:'2000-01-06'}],
    calc: function(v){ var d=new Date(v.date+'T18:14:00Z'); if(isNaN(d.getTime())) return{result:'Enter a valid date as YYYY-MM-DD',chart:'',extra:''}; var ref=Date.UTC(2000,0,6,18,14); var age=((d.getTime()-ref)/86400000)%29.530588; if(age<0) age+=29.530588; var bands=[[1.85,'New Moon'],[5.54,'Waxing Crescent'],[9.23,'First Quarter'],[12.92,'Waxing Gibbous'],[16.61,'Full Moon'],[20.30,'Waning Gibbous'],[23.99,'Last Quarter'],[26.69,'Waning Crescent'],[99,'New Moon']]; var phase='New Moon'; for(var i=0;i<bands.length;i++){ if(age<bands[i][0]){ phase=bands[i][1]; break; } } var illum=(1-Math.cos(2*Math.PI*age/29.530588))/2*100; return{result:phase,chart:Charts.gauge(illum,100),extra:'Lunar age: '+age.toFixed(2)+' days into the 29.53-day synodic month | Illumination: '+illum.toFixed(1)+'% (approximate ±1 day)'};},
    steps: function(v){ var d=new Date(v.date+'T18:14:00Z'); var ref=Date.UTC(2000,0,6,18,14); var age=((d.getTime()-ref)/86400000)%29.530588; if(age<0) age+=29.530588; return['Method: count days since a known new moon (2000-01-06 18:14 UTC), then take the remainder over the 29.53-day synodic month','Step 1: Age = '+age.toFixed(2)+' days','Step 2: Match to the 8-phase cycle (new → first quarter → full → last quarter)','Approximation drifts about a day over decades — almanac values are authoritative for observation'];} }`,
  `{ id: 'meeting-cost', name: 'Meeting Cost Calculator', desc: 'Salary cost of a meeting in money and person-hours', kw: 'meeting cost calculator attendees hourly rate salary time waste productivity',
    inputs: [{id:'people',label:'Attendees',type:'number',def:8},{id:'rate',label:'Average Loaded Hourly Cost ($)',type:'number',def:50},{id:'hours',label:'Duration (hours)',type:'number',def:1.5}],
    calc: function(v){ if(v.people<=0||v.rate<=0||v.hours<=0) return{result:'Attendees, rate and duration must be positive',chart:'',extra:''}; var cost=v.people*v.rate*v.hours; var manHrs=v.people*v.hours; return{result:'Meeting Cost: $'+cost.toFixed(2),chart:Charts.bar([manHrs,cost],['Person-hours','Dollars']),extra:manHrs.toFixed(1)+' person-hours consumed | If held weekly: $'+(cost*52).toLocaleString('en-US',{maximumFractionDigits:0})+'/year — use loaded rates (salary + benefits) for honesty'};},
    steps: function(v){ var cost=v.people*v.rate*v.hours; return['Formula: cost = attendees × hourly cost × hours','Step 1: '+v.people+' × $'+v.rate+' × '+v.hours+' h = $'+cost.toFixed(2),'Step 2: Person-hours = '+v.people+' × '+v.hours+' = '+(v.people*v.hours).toFixed(1),'Step 3: Weekly cadence would cost $'+(cost*52).toLocaleString('en-US',{maximumFractionDigits:0})+' per year'];} }`,
];

T['utilities'] = [
  `{ id: 'password-entropy', name: 'Password Entropy Calculator', desc: 'Strength in bits from length and character pool', kw: 'password entropy calculator bits strength character pool brute force crack time',
    inputs: [{id:'len',label:'Password Length',type:'number',def:12},{id:'pool',label:'Character Pool Size (26 lower, 52 mixed case, 62 alphanumeric, 95 all ASCII)',type:'number',def:62}],
    calc: function(v){ if(v.len<=0||v.pool<=1) return{result:'Length must be positive; pool needs at least 2 characters',chart:'',extra:''}; var bits=v.len*Math.log2(v.pool); var secs=Math.pow(2,bits-1)/1e12; function fmt(s){ if(s<60) return s.toFixed(1)+' seconds'; if(s<3600) return (s/60).toFixed(1)+' minutes'; if(s<86400) return (s/3600).toFixed(1)+' hours'; if(s<3.15e7) return (s/86400).toFixed(1)+' days'; var y=s/3.15e7; return y>1e12?y.toExponential(1)+' years':y.toLocaleString('en-US',{maximumFractionDigits:0})+' years'; } var verdict=bits>=100?'excellent':bits>=75?'strong':bits>=60?'reasonable':bits>=40?'weak':'very weak'; return{result:'Entropy: '+bits.toFixed(1)+' bits',chart:Charts.gauge(bits,128),extra:'Pool^length = '+v.pool+'^'+v.len+' | Median crack time at 10¹² guesses/s: '+fmt(secs)+' — '+verdict+' | Assumes truly random characters; patterns lower real entropy'};},
    steps: function(v){ var bits=v.len*Math.log2(v.pool); return['Formula: entropy = length × log₂(pool size)','Step 1: log₂('+v.pool+') = '+Math.log2(v.pool).toFixed(4),'Step 2: bits = '+v.len+' × '+Math.log2(v.pool).toFixed(4)+' = '+bits.toFixed(1),'Each extra character multiplies search space by the pool size — length beats complexity'];} }`,
  `{ id: 'speech-time', name: 'Speech Time Calculator', desc: 'Speaking duration from word count and pace', kw: 'speech time calculator words per minute presentation duration pace toastmasters',
    inputs: [{id:'words',label:'Word Count',type:'number',def:650},{id:'wpm',label:'Speaking Pace (words per minute)',type:'number',def:130}],
    calc: function(v){ if(v.words<=0||v.wpm<=0) return{result:'Word count and pace must be positive',chart:'',extra:''}; var min=v.words/v.wpm; var mm=Math.floor(min); var ss=Math.round((min-mm)*60); if(ss===60){mm++;ss=0;} return{result:mm+' min '+ss+' s',chart:Charts.bar([min,mm],['Exact minutes','Rounded']),extra:'Conversational pace is 120–150 wpm; allow 1 slide per minute | Script pages (250 w/page): '+(v.words/250).toFixed(2)+' — rehearse aloud, reading pace differs'};},
    steps: function(v){ var min=v.words/v.wpm; var mm=Math.floor(min); var ss=Math.round((min-mm)*60); if(ss===60){mm++;ss=0;} return['Formula: minutes = words ÷ pace','Step 1: '+v.words+' ÷ '+v.wpm+' wpm = '+min.toFixed(2)+' minutes','Step 2: = '+mm+' min '+ss+' s','Add 10–15% for pauses, laughter, and slide transitions'];} }`,
];

// ---- QA matrix rows (independent known-answer expectations) ----
const QA_ROWS = [
  `  ['finance', 'prorated-rent', { rent: 1200, day: 15, days: 30 }, 600, 0.01, '1200/30×15 daily rate method'],`,
  `  ['finance', 'dso', { ar: 50000, sales: 600000, days: 365 }, 30.42, 0.05, 'AR/credit sales × period days'],`,
  `  ['finance', 'pe-ratio', { price: 150, eps: 6 }, 25, 0.01, 'price ÷ EPS'],`,
  `  ['math', 'quartiles', { data: '2,4,6,8,10,12,16' }, 4, 0.01, 'Q1 median-of-halves odd n'],`,
  `  ['math', 'rms', { data: '3,4' }, 3.5355, 0.01, '√((9+16)/2)'],`,
  `  ['math', 'z-score', { x: 85, mean: 70, sd: 10 }, 1.5, 0.01, '(85−70)/10'],`,
  `  ['math', 'covariance', { x: '2,4,6,8', y: '1,3,2,5' }, 2.75, 0.01, 'population covariance of 4 pairs'],`,
  `  ['math', 'exponential-prob', { rate: 0.5, x: 2 }, 63.21, 0.05, '1−e^(−1) as %'],`,
  `  ['math', 'expected-value', { outcomes: '10,20,30', probs: '0.2,0.3,0.5' }, 23, 0.01, 'Σ outcome×probability'],`,
  `  ['math', 'euler-totient', { n: 36 }, 12, 0.01, '36×(1/2)×(2/3)'],`,
  `  ['science', 'hooke-law', { k: 200, x: 0.15 }, 30, 0.01, 'F = kx'],`,
  `  ['science', 'mach-number', { v: 680, a: 340 }, 2, 0.01, 'v ÷ local sound speed'],`,
  `  ['science', 'stefan-boltzmann', { T: 300, emis: 1 }, 459.3, 0.5, 'σT⁴ per m²'],`,
  `  ['science', 'coulomb-law', { q1: 1, q2: 1, r: 0.1 }, 8.9876, 0.01, 'kq₁q₂/r² with µC inputs'],`,
  `  ['science', 'photon-energy', { wl: 500 }, 2.48, 0.01, 'hc/λ in eV'],`,
  `  ['science', 'debroglie', { m: 9.11e-31, v: 1e6 }, 0.7274, 0.01, 'h/mv in nm'],`,
  `  ['science', 'rocket-equation', { ve: 3000, m0: 10000, mf: 4000 }, 2748.9, 1, 've·ln(m0/mf)'],`,
  `  ['science', 'carbon-dating', { pct: 25, hl: 5730 }, 11460, 1, '5730×log₂(4)'],`,
  `  ['science', 'calorimetry', { m: 0.5, c: 4186, dT: 20 }, 41860, 1, 'mcΔT'],`,
  `  ['science', 'freezing-depression', { i: 1, kf: 1.86, m: 1.5 }, 2.79, 0.01, 'i·Kf·m'],`,
  `  ['science', 'air-density', { p: 101325, T: 288.15 }, 1.225, 0.001, 'p/(R·T) ISA sea level'],`,
  `  ['health', 'creatinine-clearance', { age: 40, wt: 70, scr: 1, sex: 'm' }, 97.22, 0.1, 'Cockcroft-Gault male'],`,
  `  ['health', 'anion-gap', { na: 140, cl: 104, hco3: 24, alb: 4 }, 12, 0.01, 'Na−(Cl+HCO₃)'],`,
  `  ['health', 'qtc', { qt: 400, hr: 60 }, 400, 0.5, 'Bazett at RR = 1 s'],`,
  `  ['health', 'ponderal-index', { wt: 70, ht: 1.75 }, 13.06, 0.01, 'kg/m³'],`,
  `  ['tech-digital', 'subnet-cidr', { ip: '192.168.1.10', prefix: 26 }, 62, 0.5, '/26 usable hosts'],`,
  `  ['tech-digital', 'video-bitrate', { mbps: 8, min: 10, audio: 128 }, 76.2, 0.3, '(8 Mbps + 128 kbps) × 600 s'],`,
  `  ['construction', 'stair-stringer', { rise: 105, risers: 14, tread: 10 }, 7.5, 0.01, '105 ÷ 14 risers'],`,
  `  ['construction', 'siding-squares', { len: 40, ht: 10, walls: 4, openings: 100, waste: 10 }, 16.5, 0.1, '(1600−100)/100 × 1.1'],`,
  `  ['construction', 'soffit-area', { len: 60, wid: 30, oh: 1.5 }, 270, 0.01, 'perimeter × overhang'],`,
  `  ['construction', 'post-hole-concrete', { holes: 8, dia: 12, depth: 36, post: 4 }, 0.6, 0.02, '(πr²h − post) × 8 ÷ 27'],`,
  `  ['construction', 'fence-panel', { len: 100, panel: 6 }, 17, 0.01, 'ceil(100/6) panels'],`,
  `  ['construction', 'gravel-driveway', { len: 40, wid: 12, depth: 4 }, 8.3, 0.05, '160 cu ft → yd³ × 1.4 t'],`,
  `  ['construction', 'insulation-batts', { area: 1000, cover: 40 }, 25, 0.01, '1000 ÷ 40 units'],`,
  `  ['engineering', 'section-modulus', { shape: 'rect', b: 50, h: 100 }, 83333.3, 1, 'bh²/6'],`,
  `  ['engineering', 'shaft-torsion', { T: 100, d: 20 }, 63.66, 0.1, '16T/πd³ in MPa'],`,
  `  ['engineering', 'pulley-speed', { d1: 100, n1: 1750, d2: 200 }, 875, 0.1, 'd₁n₁/d₂'],`,
  `  ['engineering', 'manning-flow', { D: 0.3, n: 0.013, S: 0.01 }, 0.0967, 0.001, '(1/n)·A·R^(2/3)·√S'],`,
  `  ['engineering', 'orifice-flow', { cd: 0.62, d: 0.05, h: 2 }, 7.63, 0.05, 'Cd·A·√(2gh) in L/s'],`,
  `  ['engineering', 'three-phase-power', { V: 400, I: 20, pf: 0.85 }, 11.78, 0.02, '√3·V·I·pf in kW'],`,
  `  ['engineering', 'ups-sizing', { load: 600, min: 30, V: 12, eff: 85 }, 29.4, 0.1, 'Wh ÷ (V·η) in Ah'],`,
  `  ['everyday', 'poker-flush', { matches: 5 }, 0.0495, 0.001, 'C(13,5)/C(52,5) as %'],`,
  `  ['everyday', 'easter-date', { year: 2026 }, 'April 5', 0, 'Gregorian computus 2026', 'contains'],`,
  `  ['everyday', 'day-of-week', { date: '2000-01-01' }, 'Saturday', 0, 'Y2K rollover day', 'contains'],`,
  `  ['everyday', 'moon-phase', { date: '2000-01-06' }, 'New Moon', 0, 'reference new moon date', 'contains'],`,
  `  ['everyday', 'meeting-cost', { people: 8, rate: 50, hours: 1.5 }, 600, 0.01, '8 × 50 × 1.5'],`,
  `  ['utilities', 'password-entropy', { len: 12, pool: 62 }, 71.45, 0.1, '12·log₂62 bits'],`,
  `  ['utilities', 'speech-time', { words: 650, wpm: 130 }, 5, 0.01, '650 ÷ 130 wpm'],`,
];

// ---------- insertion logic ----------
const check = process.argv.includes('--check');
const doQa = process.argv.includes('--qa');
let applied = 0, skipped = 0;

for (const file of Object.keys(T)) {
  const fp = path.join(ROOT, 'js', 'data', file + '.js');
  let src = fs.readFileSync(fp, 'utf8');
  const newIds = T[file].map(code => code.match(/\{ id: '([^']+)'/)[1]);
  const present = newIds.filter(id => src.includes("id: '" + id + "'"));
  if (present.length === newIds.length) { console.log('[skip] ' + file + ': all ' + newIds.length + ' already present'); skipped++; continue; }
  if (present.length) { console.error('[ABORT] ' + file + ' partially contains: ' + present.join(', ')); process.exit(1); }
  const block = T[file].map(code => '  ' + code).join(',\r\n\r\n');
  const anchor = src.lastIndexOf('\r\n];');
  if (anchor < 0) { console.error('[ABORT] no CRLF ]; tail in ' + file); process.exit(1); }
  const out = src.slice(0, anchor) + ',\r\n\r\n' + block + src.slice(anchor);
  if (!check) fs.writeFileSync(fp, out);
  applied += newIds.length;
  console.log('[ok] ' + file + ': +' + newIds.length + ' tools (' + newIds.join(', ') + ')');
}

if (doQa) {
  const tfp = path.join(ROOT, 'tests', 'unit', 'formula-qa-full.test.js');
  let tsrc = fs.readFileSync(tfp, 'utf8');
  const firstRow = "['finance', 'prorated-rent'";
  if (tsrc.includes(firstRow)) {
    console.log('[skip] QA rows already present');
  } else {
    const start = tsrc.indexOf('const CASES = [');
    if (start < 0) { console.error('[ABORT] CASES array not found'); process.exit(1); }
    const close = tsrc.indexOf('\n];', start);
    if (close < 0) { console.error('[ABORT] CASES terminator not found'); process.exit(1); }
    tsrc = tsrc.slice(0, close) + '\n' + QA_ROWS.join('\n') + tsrc.slice(close);
    if (!check) fs.writeFileSync(tfp, tsrc);
    console.log('[ok] +' + QA_ROWS.length + ' QA rows');
  }
}

console.log((check ? '[DRY RUN] would insert ' : 'Inserted ') + applied + ' tools across ' + Object.keys(T).length + ' files');
