// Batch A3-F3a: 17 finance + 25 math tools. Usage: node scripts/a3-f3a.cjs [--check]
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const T = {};
T['finance'] = [
`{ id: 'apr-annual', name: 'Loan APR Calculator', desc: 'True APR including fees, not just the note rate', kw: 'apr calculator loan fees true cost annual percentage rate', inputs: [{id:'principal',label:'Loan Amount ($)',type:'number',def:20000},{id:'fees',label:'Fees & Points ($)',type:'number',def:2000},{id:'interest',label:'Total Interest Over Loan ($)',type:'number',def:4800},{id:'years',label:'Term (years)',type:'number',def:4}], calc: function(v){ if(v.principal<=0||v.years<=0) return{result:'Principal and term must be positive',chart:'',extra:''}; var apr=(v.fees+v.interest)/v.principal/v.years*100; return{result:'APR: '+apr.toFixed(2)+'%',chart:Charts.gauge(apr,25),extra:'Finance charge: $'+(v.fees+v.interest).toFixed(0)+' on $'+v.principal.toLocaleString()+' | APR bundles fees with interest, which is why it usually exceeds the quoted note rate'};}, steps: function(v){ var apr=(v.fees+v.interest)/v.principal/v.years*100; return['Formula: APR = (fees + total interest) ÷ principal ÷ years','Step 1: $'+v.fees.toLocaleString()+' + $'+v.interest.toLocaleString()+' = $'+(v.fees+v.interest).toLocaleString(),'Step 2: ÷ $'+v.principal.toLocaleString()+' = '+(v.fees+v.interest)/v.principal,'Step 3: ÷ '+v.years+' years × 100 = '+apr.toFixed(2)+'%'];} }`,
`{ id: 'auto-lease-vs-buy', name: 'Lease vs Buy Calculator', desc: 'Total cost of leasing against financing a purchase', kw: 'lease vs buy calculator car total cost comparison', inputs: [{id:'lPay',label:'Monthly Lease ($)',type:'number',def:350},{id:'lDown',label:'Lease Down Payment ($)',type:'number',def:2500},{id:'lTerm',label:'Lease Term (months)',type:'number',def:36},{id:'bPay',label:'Monthly Loan Payment ($)',type:'number',def:450},{id:'bDown',label:'Loan Down Payment ($)',type:'number',def:3000},{id:'bTerm',label:'Loan Term (months)',type:'number',def:60}], calc: function(v){ var lt=v.lPay*v.lTerm+v.lDown, bt=v.bPay*v.bTerm+v.bDown; var cheap=lt<=bt; return{result:(cheap?'Lease':'Buy')+' costs less: $'+(cheap?lt:bt).toLocaleString()+' vs $'+(cheap?bt:lt).toLocaleString(),chart:Charts.bar([lt,bt],['Lease','Buy']),extra:'Difference: $'+Math.abs(bt-lt).toLocaleString()+' | Leasing buys the depreciation plus a rent charge; buying builds equity you keep at trade-in — compare per-month: lease $'+(lt/v.lTerm).toFixed(0)+' vs buy $'+(bt/v.bTerm).toFixed(0)};}, steps: function(v){ var lt=v.lPay*v.lTerm+v.lDown, bt=v.bPay*v.bTerm+v.bDown; return['Step 1: Lease total = $'+v.lPay+' × '+v.lTerm+' + $'+v.lDown.toLocaleString()+' = $'+lt.toLocaleString(),'Step 2: Buy total = $'+v.bPay+' × '+v.bTerm+' + $'+v.bDown.toLocaleString()+' = $'+bt.toLocaleString(),'Step 3: Cheaper path wins on cash — but equity, mileage limits, and how long you keep the car decide the real winner'];} }`,
`{ id: 'heloc-payment', name: 'HELOC Interest-Only Payment', desc: 'Monthly payment during the draw period', kw: 'heloc payment calculator interest only home equity line', inputs: [{id:'bal',label:'Drawn Balance ($)',type:'number',def:50000},{id:'rate',label:'Rate (%)',type:'number',def:8}], calc: function(v){ if(v.bal<=0||v.rate<0) return{result:'Enter valid values',chart:'',extra:''}; var m=v.bal*v.rate/100/12; return{result:'Interest-Only Payment: $'+m.toFixed(2),chart:Charts.bar([m,v.bal],['Monthly interest','Balance']),extra:'HELOCs are variable-rate — this payment moves every time the index moves | The draw period pays interest only, so the balance does not shrink until repayment begins'};}, steps: function(v){ var m=v.bal*v.rate/100/12; return['Formula: Monthly interest = balance × rate ÷ 12','Step 1: $'+v.bal.toLocaleString()+' × '+(v.rate/100)+' = $'+(v.bal*v.rate/100).toFixed(0)+' per year','Step 2: ÷ 12 = $'+m.toFixed(2)+' per month','Paying principal above this number during the draw period saves every future month'];} }`,
`{ id: 'pmi-drop', name: 'PMI Removal Calculator', desc: 'Current LTV and whether PMI can be cancelled', kw: 'pmi removal calculator ltv 80 percent cancel mortgage insurance', inputs: [{id:'bal',label:'Current Balance ($)',type:'number',def:152000},{id:'value',label:'Current Home Value ($)',type:'number',def:200000}], calc: function(v){ if(v.bal<=0||v.value<=0) return{result:'Enter positive values',chart:'',extra:''}; var ltv=v.bal/v.value*100; var ok=ltv<80; return{result:'LTV: '+ltv.toFixed(1)+'% — '+(ok?'below 80%, you can request PMI cancellation':'above 80%, PMI continues'),chart:Charts.bar([ltv,100-ltv],['LTV','Equity']),extra:'Under the Homeowners Protection Act lenders must cancel PMI at 78% automatically; at 80% you may request it with a clean payment history | A new appraisal that lifts value can get you there faster'};}, steps: function(v){ var ltv=v.bal/v.value*100; return['Formula: LTV = balance ÷ value × 100','Step 1: $'+v.bal.toLocaleString()+' ÷ $'+v.value.toLocaleString()+' = '+ltv.toFixed(3),'Step 2: Compare with the 80% threshold — '+(ltv<80?'you are under':'you are still over'),'Dropping PMI on a typical loan saves 0.3-1.5% of the original loan amount per year'];} }`,
`{ id: 'escrow-analysis', name: 'Escrow Payment Calculator', desc: 'Monthly escrow with the two-month cushion', kw: 'escrow calculator property tax insurance monthly cushion', inputs: [{id:'tax',label:'Annual Property Tax ($)',type:'number',def:3600},{id:'ins',label:'Annual Insurance ($)',type:'number',def:1200}], calc: function(v){ if(v.tax<0||v.ins<0) return{result:'Enter non-negative amounts',chart:'',extra:''}; var total=v.tax+v.ins; var withCushion=total*1.1667; var m=withCushion/12; return{result:'Escrow: $'+m.toFixed(2)+'/month',chart:Charts.bar([total/12,m-total/12],['Base','Cushion']),extra:'Lenders hold a 2-month cushion by federal rule, so the deposit is about '+((withCushion/total-1)*100).toFixed(1)+'% above the raw 1/12 | Escrow analyses arrive annually — shortages are spread over 12 months, surpluses above $50 are refunded'};}, steps: function(v){ var total=v.tax+v.ins; var m=total*1.1667/12; return['Step 1: Annual total = $'+total.toLocaleString(),'Step 2: Add the 2-month cushion → $'+(total*1.1667).toLocaleString(),'Step 3: ÷ 12 = $'+m.toFixed(2)+' per month','Tax reassessments are the usual cause of payment jumps, not the insurance'];} }`,
`{ id: 'portfolio-beta', name: 'Portfolio Beta Calculator', desc: 'Weighted market sensitivity of your holdings', kw: 'portfolio beta calculator weighted stock market sensitivity', inputs: [{id:'w1',label:'Holding 1 Weight (%)',type:'number',def:60},{id:'b1',label:'Holding 1 Beta',type:'number',def:1.2},{id:'w2',label:'Holding 2 Weight (%)',type:'number',def:40},{id:'b2',label:'Holding 2 Beta',type:'number',def:0.8}], calc: function(v){ var tot=v.w1+v.w2; if(tot<=0) return{result:'Enter weights',chart:'',extra:''}; var beta=(v.w1*v.b1+v.w2*v.b2)/tot; return{result:'Portfolio Beta: '+beta.toFixed(2),chart:Charts.gauge(beta,2),extra:'Beta 1.0 moves with the market; above 1 amplifies both directions | A 10% market drop against beta '+beta.toFixed(2)+' implies roughly a '+(beta*10).toFixed(1)+'% portfolio move'};}, steps: function(v){ var tot=v.w1+v.w2; var beta=(v.w1*v.b1+v.w2*v.b2)/tot; return['Formula: Portfolio beta = Σ(weight × beta)','Step 1: '+v.w1+'% × '+v.b1+' + '+v.w2+'% × '+v.b2+' = '+((v.w1*v.b1+v.w2*v.b2)/100).toFixed(3),'Step 2: ÷ '+tot+'% total weight = '+beta.toFixed(2),'Betas drift — recompute after big allocations or rebalances'];} }`,
`{ id: 'yield-to-worst', name: 'Yield to Worst Calculator', desc: 'Conservative yield across call and maturity dates', kw: 'yield to worst calculator callable bond ytw ytc ytm', inputs: [{id:'ytm',label:'Yield to Maturity (%)',type:'number',def:5.2},{id:'ytc',label:'Yield to Call (%)',type:'number',def:4.1}], calc: function(v){ var w=Math.min(v.ytm,v.ytc); return{result:'Yield to Worst: '+w.toFixed(2)+'%',chart:Charts.bar([v.ytm,v.ytc,w],['YTM','YTC','YTW']),extra:'Callable bonds get redeemed when it suits the issuer — evaluate them at the lowest plausible yield, not the highest'};}, steps: function(v){ var w=Math.min(v.ytm,v.ytc); return['Step 1: Compute YTM (hold to maturity) and YTC (first call date)','Step 2: Yield to worst = the lower of every scenario = '+w.toFixed(2)+'%','Add YTC for each call date if the bond has a schedule — the floor governs the decision'];} }`,
`{ id: 'coupon-payment', name: 'Bond Coupon Payment Calculator', desc: 'Periodic interest from face value and coupon rate', kw: 'bond coupon payment calculator semiannual interest face value', inputs: [{id:'face',label:'Face Value ($)',type:'number',def:1000},{id:'rate',label:'Annual Coupon Rate (%)',type:'number',def:6},{id:'perYear',label:'Payments per Year (1, 2, 4)',type:'number',def:2}], calc: function(v){ if(v.face<=0||v.perYear<1) return{result:'Enter valid values',chart:'',extra:''}; var p=v.face*v.rate/100/v.perYear; return{result:'Coupon Payment: $'+p.toFixed(2),chart:Charts.bar([p,v.face*v.rate/100],['Per period','Annual']),extra:'Annual total: $'+(v.face*v.rate/100).toFixed(2)+' in '+v.perYear+' payments | US corporate and Treasury bonds pay semiannually; many European bonds pay annually'};}, steps: function(v){ var p=v.face*v.rate/100/v.perYear; return['Formula: Payment = face × coupon ÷ payments per year','Step 1: $'+v.face.toLocaleString()+' × '+(v.rate/100)+' = $'+(v.face*v.rate/100).toFixed(2)+' annual','Step 2: ÷ '+v.perYear+' = $'+p.toFixed(2)+' each','The coupon never changes; what changes is the yield you earn relative to the price you paid'];} }`,
`{ id: 'clean-dirty-price', name: 'Clean vs Dirty Bond Price', desc: 'Strip accrued interest from the quoted price', kw: 'clean dirty price calculator accrued interest bond settlement', inputs: [{id:'dirty',label:'Dirty (Full) Price ($)',type:'number',def:1025},{id:'accrued',label:'Accrued Interest ($)',type:'number',def:8.5}], calc: function(v){ if(v.accrued<0) return{result:'Accrued cannot be negative',chart:'',extra:''}; var clean=v.dirty-v.accrued; return{result:'Clean Price: $'+clean.toFixed(2),chart:Charts.bar([clean,v.accrued],['Clean','Accrued']),extra:'The dirty price is what you actually pay; the clean price is what gets quoted and charted | Accrued resets to zero after each coupon date'};}, steps: function(v){ var clean=v.dirty-v.accrued; return['Formula: Clean = dirty − accrued','Step 1: $'+v.dirty+' − $'+v.accrued+' = $'+clean.toFixed(2),'Step 2: The buyer repays the seller the accrued slice at settlement, then collects the next full coupon'];} }`,
`{ id: 'convexity', name: 'Bond Convexity Calculator', desc: 'Curvature of price change from up and down repricing', kw: 'bond convexity calculator price sensitivity duration improvement', inputs: [{id:'p0',label:'Current Price ($)',type:'number',def:1000},{id:'pUp',label:'Price if Yield Falls ($)',type:'number',def:1019},{id:'pDn',label:'Price if Yield Rises ($)',type:'number',def:982},{id:'dy',label:'Yield Shift (decimal, e.g. 0.01)',type:'number',def:0.01}], calc: function(v){ if(v.p0<=0||v.dy<=0) return{result:'Enter valid values',chart:'',extra:''}; var cx=(v.pUp+v.pDn-2*v.p0)/(v.p0*v.dy*v.dy); return{result:'Convexity: '+cx.toFixed(1),chart:Charts.gauge(cx,200),extra:'Positive convexity means prices rise more when yields fall than they drop when yields rise — duration alone understates the upside'};}, steps: function(v){ var cx=(v.pUp+v.pDn-2*v.p0)/(v.p0*v.dy*v.dy); return['Formula: Convexity = (P↓yield + P↑yield − 2P0) ÷ (P0 × Δy²)','Step 1: '+v.pUp+' + '+v.pDn+' − 2×'+v.p0+' = '+(v.pUp+v.pDn-2*v.p0),'Step 2: ÷ ('+v.p0+' × '+Math.pow(v.dy,2)+') = '+cx.toFixed(1),'Bigger convexity is better for holders, all else equal'];} }`,
`{ id: 'duration-bond', name: 'Modified Duration Calculator', desc: 'Rate sensitivity adjusted for payment frequency', kw: 'modified duration calculator macaulay bond interest rate sensitivity', inputs: [{id:'mac',label:'Macaulay Duration (years)',type:'number',def:7.2},{id:'y',label:'Yield (%)',type:'number',def:6},{id:'perYear',label:'Compounding per Year (1, 2)',type:'number',def:2}], calc: function(v){ if(v.mac<=0||v.perYear<1) return{result:'Enter valid values',chart:'',extra:''}; var md=v.mac/(1+v.y/100/v.perYear); return{result:'Modified Duration: '+md.toFixed(2),chart:Charts.gauge(md,30),extra:'A 1% rate rise drops the bond price about '+md.toFixed(2)+'% — modified duration is the practical risk number, Macaulay is the weighted time'};}, steps: function(v){ var md=v.mac/(1+v.y/100/v.perYear); return['Formula: Modified = Macaulay ÷ (1 + y ÷ k)','Step 1: '+v.y+'% ÷ '+v.perYear+' = '+(v.y/100/v.perYear),'Step 2: '+v.mac+' ÷ (1 + '+(v.y/100/v.perYear)+') = '+md.toFixed(2),'Price change ≈ −modified duration × Δyield for small shifts'];} }`,
`{ id: 'appreciation-forecast', name: 'Property Appreciation Calculator', desc: 'Future value of real estate at a growth rate', kw: 'property appreciation calculator future home value growth rate', inputs: [{id:'val',label:'Current Value ($)',type:'number',def:300000},{id:'g',label:'Annual Growth (%)',type:'number',def:3},{id:'years',label:'Years',type:'number',def:10}], calc: function(v){ if(v.val<=0||v.years<0) return{result:'Enter valid values',chart:'',extra:''}; var fv=v.val*Math.pow(1+v.g/100,v.years); return{result:'Projected Value: $'+fv.toFixed(0),chart:Charts.bar([v.val,fv-v.val],['Today','Growth']),extra:'Gain: $'+(fv-v.val).toFixed(0)+' | Long-run US home appreciation has averaged 3-5%, but it is lumpy — decade-long flat stretches happen in weaker markets'};}, steps: function(v){ var fv=v.val*Math.pow(1+v.g/100,v.years); return['Formula: FV = value × (1 + g)^years','Step 1: (1 + '+(v.g/100)+')^'+v.years+' = '+Math.pow(1+v.g/100,v.years).toFixed(4),'Step 2: $'+v.val.toLocaleString()+' × '+Math.pow(1+v.g/100,v.years).toFixed(4)+' = $'+fv.toFixed(0),'Doubling time at '+v.g+'% is about '+(72/v.g).toFixed(0)+' years (rule of 72)'];} }`,
`{ id: 'rent-vs-sell', name: 'Rent vs Sell Calculator', desc: 'Ten years of net rent against selling and investing', kw: 'rent vs sell calculator landlord keep property invest proceeds', inputs: [{id:'rentNet',label:'Net Annual Rent ($)',type:'number',def:20000},{id:'sell',label:'Sale Proceeds if Sold ($)',type:'number',def:350000},{id:'inv',label:'Investment Return (%)',type:'number',def:5},{id:'years',label:'Horizon (years)',type:'number',def:10}], calc: function(v){ var rentPath=v.rentNet*v.years; var sellPath=v.sell*Math.pow(1+v.inv/100,v.years)-v.sell; var keepRent=rentPath>=sellPath; return{result:(keepRent?'Renting':'Selling')+' projects ahead by $'+Math.abs(rentPath-sellPath).toFixed(0),chart:Charts.bar([rentPath,sellPath],['Rent income','Sale invested gains']),extra:'Rent path: $'+rentPath.toFixed(0)+' | Sale path gains: $'+sellPath.toFixed(0)+' | This ignores rent growth, upkeep shocks, and tax — treat it as the first cut, not the verdict'};}, steps: function(v){ var rentPath=v.rentNet*v.years; var sellPath=v.sell*Math.pow(1+v.inv/100,v.years)-v.sell; return['Step 1: Rent path = $'+v.rentNet.toLocaleString()+' × '+v.years+' = $'+rentPath.toLocaleString(),'Step 2: Sale path = $'+v.sell.toLocaleString()+' invested at '+v.inv+'% for '+v.years+' years → $'+(v.sell*Math.pow(1+v.inv/100,v.years)).toFixed(0)+', gains $'+sellPath.toFixed(0),'Step 3: Compare — but remember the house also appreciates while rented, and being a landlord is a job'];} }`,
`{ id: 'seller-net', name: 'Seller Net Proceeds Calculator', desc: 'Cash in hand after commission and payoff', kw: 'seller net proceeds calculator home sale commission payoff', inputs: [{id:'price',label:'Sale Price ($)',type:'number',def:400000},{id:'comm',label:'Commission (%)',type:'number',def:6},{id:'closing',label:'Seller Closing Costs ($)',type:'number',def:3000},{id:'payoff',label:'Mortgage Payoff ($)',type:'number',def:250000}], calc: function(v){ if(v.price<=0) return{result:'Price must be positive',chart:'',extra:''}; var commD=v.price*v.comm/100; var net=v.price-commD-v.closing-v.payoff; return{result:'Net to Seller: $'+net.toFixed(0),chart:Charts.bar([v.price-commD-v.closing,v.payoff],['Before payoff','Payoff']),extra:'Commission: $'+commD.toFixed(0)+', closing: $'+v.closing.toLocaleString()+' | Add prorated taxes, seller credits, and any second liens to refine — net is usually 80-90% of price'};}, steps: function(v){ var commD=v.price*v.comm/100; var net=v.price-commD-v.closing-v.payoff; return['Step 1: Commission = $'+v.price.toLocaleString()+' × '+(v.comm/100)+' = $'+commD.toFixed(0),'Step 2: $'+v.price.toLocaleString()+' − $'+commD.toFixed(0)+' − $'+v.closing.toLocaleString()+' = $'+(v.price-commD-v.closing).toLocaleString(),'Step 3: − payoff $'+v.payoff.toLocaleString()+' = $'+net.toFixed(0)+' cash at closing'];} }`,
`{ id: 'points-breakeven', name: 'Mortgage Points Break-Even', desc: 'Months for discount points to pay for themselves', kw: 'mortgage points break even calculator discount origination', inputs: [{id:'cost',label:'Points Cost ($)',type:'number',def:4000},{id:'save',label:'Monthly Savings ($)',type:'number',def:80}], calc: function(v){ if(v.save<=0) return{result:'Monthly savings must be positive',chart:'',extra:''}; var m=v.cost/v.save; return{result:'Break-even: '+m.toFixed(1)+' months ('+(m/12).toFixed(1)+' years)',chart:Charts.bar([m,360-m],['To break even','Remaining benefit window']),extra:'Stay past break-even and the points pay; sell or refinance earlier and they were a loss | Typical break-evens run 3-7 years'};}, steps: function(v){ var m=v.cost/v.save; return['Formula: Break-even months = points cost ÷ monthly saving','Step 1: $'+v.cost.toLocaleString()+' ÷ $'+v.save+' = '+m.toFixed(1)+' months','Step 2: Compare with how long you realistically expect to keep this loan','One point = 1% of the loan amount, buying roughly a 0.25% rate cut at normal pricing'];} }`,
`{ id: 'mortgage-recast', name: 'Mortgage Recast Calculator', desc: 'New payment after a lump-sum principal reduction', kw: 'mortgage recast calculator lump sum reamortize payment', inputs: [{id:'bal',label:'Current Balance ($)',type:'number',def:280000},{id:'lump',label:'Lump Sum ($)',type:'number',def:30000},{id:'rate',label:'Rate (%)',type:'number',def:6},{id:'months',label:'Months Remaining',type:'number',def:360}], calc: function(v){ var nb=v.bal-v.lump; if(nb<=0||v.months<=0||v.rate<0) return{result:'Enter valid values',chart:'',extra:''}; var r=v.rate/100/12; var p=nb*r/(1-Math.pow(1+r,-v.months)); var pOld=v.bal*r/(1-Math.pow(1+r,-v.months)); return{result:'New Payment: $'+p.toFixed(2)+' (was $'+pOld.toFixed(2)+')',chart:Charts.bar([pOld,p],['Before','After']),extra:'Monthly savings: $'+(pOld-p).toFixed(2)+' | A recast keeps your rate and term — unlike a refinance there are minimal fees, usually a few hundred dollars'};}, steps: function(v){ var nb=v.bal-v.lump; var r=v.rate/100/12; var p=nb*r/(1-Math.pow(1+r,-v.months)); return['Step 1: New balance = $'+v.bal.toLocaleString()+' − $'+v.lump.toLocaleString()+' = $'+nb.toLocaleString(),'Step 2: Reamortize over the remaining '+v.months+' months at the same rate','Step 3: Payment = P × r ÷ (1 − (1+r)^−n) = $'+p.toFixed(2),'Not all loans allow recasting — government-backed loans often do not'];} }`,
];
T['math'] = [
`{ id: 'exponent-solver', name: 'Exponent Calculator', desc: 'Raise any base to any power', kw: 'exponent calculator power base raised x to the y', inputs: [{id:'b',label:'Base',type:'number',def:2},{id:'e',label:'Exponent',type:'number',def:10}], calc: function(v){ var r=Math.pow(v.b,v.e); if(!isFinite(r)) return{result:'Result too large or undefined for these inputs',chart:'',extra:''}; return{result:v.b+'^'+v.e+' = '+(+r.toFixed(6)),chart:Charts.bar([v.b,r],['base','result']),extra:'Negative exponents divide: b^(−n) = 1/b^n | Fractional exponents are roots: b^(1/2) = √b'};}, steps: function(v){ var r=Math.pow(v.b,v.e); return['Formula: b^e means e copies of b multiplied together','Step 1: '+v.b+'^'+v.e+' = '+(+r.toFixed(6)),'For e = 2 the operation is squaring, e = 3 is cubing, e = 0 always gives 1'];} }`,
`{ id: 'nth-root', name: 'Nth Root Calculator', desc: 'Any root of any non-negative number', kw: 'nth root calculator cube root fourth root radical index', inputs: [{id:'x',label:'Number',type:'number',def:27},{id:'n',label:'Root Index',type:'number',def:3}], calc: function(v){ if(v.n===0) return{result:'Root index cannot be zero',chart:'',extra:''}; if(v.x<0&&v.n%2===0) return{result:'Even roots of negative numbers are not real',chart:'',extra:''}; var r=Math.pow(Math.abs(v.x),1/v.n)*(v.x<0?-1:1); return{result:'Root '+v.n+' of '+v.x+' = '+(+r.toFixed(6)),chart:Charts.bar([r],['root']),extra:'Check: ('+(+r.toFixed(6))+')^'+v.n+' = '+(+Math.pow(r,v.n).toFixed(4))+' — squaring the result undoes the root'};}, steps: function(v){ var r=Math.pow(Math.abs(v.x),1/v.n)*(v.x<0?-1:1); return['Formula: root n of x = x^(1/n)','Step 1: '+v.x+'^(1/'+v.n+') = '+(+r.toFixed(6)),'Odd roots keep the sign of the number; even roots do not exist for negatives in the reals'];} }`,
`{ id: 'series-sum-ap', name: 'Arithmetic Series Sum', desc: 'Sum of n terms of an arithmetic sequence', kw: 'arithmetic series sum calculator sequence common difference gauss', inputs: [{id:'a',label:'First Term',type:'number',def:2},{id:'d',label:'Common Difference',type:'number',def:3},{id:'n',label:'Number of Terms',type:'number',def:10}], calc: function(v){ if(v.n<=0) return{result:'Term count must be positive',chart:'',extra:''}; var s=v.n*(2*v.a+(v.n-1)*v.d)/2; var last=v.a+(v.n-1)*v.d; return{result:'Sum: '+s,charchart:'',chart:Charts.bar([v.a,last,s],['first','last','sum']),extra:'Terms run '+v.a+', '+(v.a+v.d)+', ... , '+last+' | Pairing first and last gives n/2 equal pairs — Gauss celebrated this sum as a schoolboy'};}, steps: function(v){ var s=v.n*(2*v.a+(v.n-1)*v.d)/2; return['Formula: S = n ÷ 2 × (2a + (n−1)d)','Step 1: 2×'+v.a+' + ('+v.n+'−1)×'+v.d+' = '+(2*v.a+(v.n-1)*v.d),'Step 2: '+v.n+' ÷ 2 × '+(2*v.a+(v.n-1)*v.d)+' = '+s];} }`,
`{ id: 'sigma-notation', name: 'Sum of Squares Calculator', desc: 'Sigma k=1..n of k-squared', kw: 'sum of squares calculator sigma notation series formula', inputs: [{id:'n',label:'Upper Limit n',type:'number',def:10}], calc: function(v){ if(v.n<1) return{result:'n must be at least 1',chart:'',extra:''}; var s=v.n*(v.n+1)*(2*v.n+1)/6; return{result:'Sum: '+s,chart:Charts.bar([s],['sum of k^2']),extra:'Formula: n(n+1)(2n+1)/6 | Squares grow fast: the first 10 contribute just 385, the first 100 already 338,350'};}, steps: function(v){ var s=v.n*(v.n+1)*(2*v.n+1)/6; return['Formula: Σk² = n(n+1)(2n+1) ÷ 6','Step 1: '+v.n+' × '+(v.n+1)+' × '+(2*v.n+1)+' = '+(v.n*(v.n+1)*(2*v.n+1)),'Step 2: ÷ 6 = '+s,'This closed form replaces adding '+v.n+' terms by hand'];} }`,
`{ id: 'combination-repeat', name: 'Combinations with Repetition', desc: 'Multiset count: choose k from n with repeats', kw: 'combinations with repetition calculator multiset stars and bars', inputs: [{id:'n',label:'Distinct Types (n)',type:'number',def:5},{id:'k',label:'Picks (k)',type:'number',def:2}], calc: function(v){ if(v.n<1||v.k<0) return{result:'Enter valid n and k',chart:'',extra:''}; var num=1; for(var i=0;i<v.k;i++) num*=v.n+i; var den=1; for(var j=2;j<=v.k;j++) den*=j; var c=num/den; return{result:'C(n+k−1, k) = '+(+c.toFixed(4)),chart:Charts.bar([c],['multisets']),extra:'Stars and bars: distributing '+v.k+' identical picks across '+v.n+' types — picking 2 scoops from 5 flavors gives 15 bowls, not 10'};}, steps: function(v){ var num=1; for(var i=0;i<v.k;i++) num*=v.n+i; var den=1; for(var j=2;j<=v.k;j++) den*=j; var c=num/den; return['Formula: C(n+k−1, k) = (n+k−1)! ÷ (k!(n−1)!)','Step 1: Numerator = '+num+' (product of k consecutive values from n)','Step 2: Denominator = '+den+' (k!)','Step 3: '+num+' ÷ '+den+' = '+(+c.toFixed(4))];} }`,
`{ id: 'permutation-repeat', name: 'Permutations with Repetition', desc: 'Arrangements when symbols can repeat', kw: 'permutations with repetition calculator n^k arrangements passwords', inputs: [{id:'n',label:'Symbols (n)',type:'number',def:3},{id:'k',label:'Positions (k)',type:'number',def:4}], calc: function(v){ if(v.n<1||v.k<0) return{result:'Enter valid n and k',chart:'',extra:''}; var p=Math.pow(v.n,v.k); return{result:'n^k = '+p.toLocaleString(),chart:Charts.bar([p],['arrangements']),extra:'Each of '+v.k+' positions picks freely from '+v.n+' symbols — a 4-digit PIN from 10 digits has 10,000 combinations'};}, steps: function(v){ var p=Math.pow(v.n,v.k); return['Formula: permutations with repetition = n^k','Step 1: '+v.n+'^'+v.k+' = '+p.toLocaleString(),'Repetition allowed explodes the count — without repetition it would be the falling factorial n!/(n−k)!'];} }`,
`{ id: 'probability-odds', name: 'Odds to Probability', desc: 'Convert a:b odds into a percent chance', kw: 'odds to probability calculator a to b chance convert percent', inputs: [{id:'a',label:'Odds For (a)',type:'number',def:3},{id:'b',label:'Odds Against (b)',type:'number',def:1}], calc: function(v){ if(v.a<=0||v.b<0) return{result:'Odds-for must be positive',chart:'',extra:''}; var p=v.a/(v.a+v.b)*100; return{result:'Probability: '+p.toFixed(2)+'%',chart:Charts.bar([p,100-p],['For','Against']),extra:'Odds 3:1 means 3 wins per 1 loss — 75%, not 300% | Bookmaker decimal odds of '+(1+(v.b/v.a)).toFixed(2)+' carry an implied probability of '+p.toFixed(1)+'% before margin'};}, steps: function(v){ var p=v.a/(v.a+v.b)*100; return['Formula: P = a ÷ (a + b)','Step 1: '+v.a+' ÷ ('+v.a+' + '+v.b+') = '+(v.a/(v.a+v.b)),'Step 2: × 100 = '+p.toFixed(2)+'%','Odds and probability are different scales — 1:1 odds is exactly 50%'];} }`,
`{ id: 'negative-binomial', name: 'Negative Binomial Probability', desc: 'Chance the k-th success lands on trial n', kw: 'negative binomial calculator kth success trial probability', inputs: [{id:'k',label:'Target Successes (k)',type:'number',def:2},{id:'n',label:'Trial Number (n)',type:'number',def:3},{id:'p',label:'Success Probability (0-1)',type:'number',def:0.5}], calc: function(v){ if(v.k<1||v.n<v.k||v.p<=0||v.p>=1) return{result:'Need k ≥ 1, n ≥ k, and p between 0 and 1',chart:'',extra:''}; var num=1; for(var i=0;i<v.k-1;i++) num*=v.n-1-i; var den=1; for(var j=2;j<=v.k-1;j++) den*=j; var c=num/den; var pr=c*Math.pow(v.p,v.k)*Math.pow(1-v.p,v.n-v.k); return{result:'P = '+(+pr.toFixed(5)),chart:Charts.bar([pr*100],['%']),extra:'Read as: of the first '+(v.n-1)+' trials, '+(v.k-1)+' were successes (choose which), then trial '+v.n+' succeeds'};}, steps: function(v){ var num=1; for(var i=0;i<v.k-1;i++) num*=v.n-1-i; var den=1; for(var j=2;j<=v.k-1;j++) den*=j; var c=num/den; var pr=c*Math.pow(v.p,v.k)*Math.pow(1-v.p,v.n-v.k); return['Formula: P = C(n−1, k−1) × p^k × (1−p)^(n−k)','Step 1: C('+(v.n-1)+', '+(v.k-1)+') = '+c,'Step 2: '+c+' × '+Math.pow(v.p,v.k)+' × '+Math.pow(1-v.p,v.n-v.k)+' = '+(+pr.toFixed(5)),'Counts trials until a quota of successes — the geometric distribution is the k=1 special case'];} }`,
`{ id: 'circle-through-points', name: 'Circumradius Calculator', desc: 'Radius of the circle through a triangle', kw: 'circumradius calculator triangle circumcircle abc 4K', inputs: [{id:'a',label:'Side a',type:'number',def:3},{id:'b',label:'Side b',type:'number',def:4},{id:'c',label:'Side c',type:'number',def:5}], calc: function(v){ var s=(v.a+v.b+v.c)/2; var K=s*(s-v.a)*(s-v.b)*(s-v.c); if(K<=0) return{result:'These sides do not form a valid triangle',chart:'',extra:''}; K=Math.sqrt(K); var R=v.a*v.b*v.c/(4*K); return{result:'Circumradius: '+(+R.toFixed(4)),chart:Charts.bar([R],['radius']),extra:'Area (Heron): '+(+K.toFixed(4))+' | R = abc/4K — a right triangle inscribes in a circle whose diameter is the hypotenuse (here 5 gives R = 2.5)'};}, steps: function(v){ var s=(v.a+v.b+v.c)/2; var K=Math.sqrt(s*(s-v.a)*(s-v.b)*(s-v.c)); var R=v.a*v.b*v.c/(4*K); return['Step 1: Semi-perimeter s = '+s,'Step 2: Heron area K = √(s(s−a)(s−b)(s−c)) = '+(+K.toFixed(4)),'Step 3: R = abc ÷ 4K = '+R.toFixed(4)];} }`,
`{ id: 'secant-tangent', name: 'Secant-Tangent Length', desc: 'Tangent length from the power of a point', kw: 'secant tangent calculator power of a point circle geometry', inputs: [{id:'s',label:'External Secant Segment',type:'number',def:4},{id:'e',label:'Secant Inside Circle',type:'number',def:5}], calc: function(v){ if(v.s<=0||v.e<=0) return{result:'Segments must be positive',chart:'',extra:''}; var t=Math.sqrt(v.s*(v.s+v.e)); return{result:'Tangent length: '+(+t.toFixed(4)),chart:Charts.bar([v.s,v.e,t],['external','internal','tangent']),extra:'Power of a point: tangent² = external × whole secant = '+v.s+' × '+(v.s+v.e)+' = '+(v.s*(v.s+v.e))+'; the tangent segment is the geometric mean'};}, steps: function(v){ var t=Math.sqrt(v.s*(v.s+v.e)); return['Formula: t² = s(s + e)','Step 1: Whole secant = '+v.s+' + '+v.e+' = '+(v.s+v.e),'Step 2: t = √('+v.s+' × '+(v.s+v.e)+') = '+t.toFixed(4)];} }`,
`{ id: 'inscribed-angle', name: 'Inscribed Angle Calculator', desc: 'Inscribed angle is half the central angle', kw: 'inscribed angle calculator central angle circle theorem half', inputs: [{id:'central',label:'Central Angle (degrees)',type:'number',def:80}], calc: function(v){ if(v.central<0||v.central>360) return{result:'Central angle must be 0-360',chart:'',extra:''}; var ins=v.central/2; return{result:'Inscribed Angle: '+ins.toFixed(1)+'°',chart:Charts.bar([v.central,ins],['central','inscribed']),extra:'Any point on the same arc sees the same inscribed angle — the theorem behind the invariant of a circle view'};}, steps: function(v){ return['Formula: inscribed = central ÷ 2','Step 1: '+v.central+' ÷ 2 = '+(v.central/2)+'°','The same arc subtends double the angle at the center compared to any point on the circumference'];} }`,
`{ id: 'sector-perimeter', name: 'Sector Perimeter Calculator', desc: 'Arc plus two radii around a pie slice', kw: 'sector perimeter calculator arc length radius angle pie', inputs: [{id:'r',label:'Radius',type:'number',def:5},{id:'deg',label:'Sector Angle (degrees)',type:'number',def:68.75}], calc: function(v){ if(v.r<=0||v.deg<=0||v.deg>360) return{result:'Enter valid radius and angle',chart:'',extra:''}; var arc=v.r*v.deg*Math.PI/180; var p=2*v.r+arc; return{result:'Perimeter: '+(+p.toFixed(4)),chart:Charts.bar([2*v.r,arc],['two radii','arc']),extra:'Arc length: '+(+arc.toFixed(4))+' | Perimeter of a sector is NOT the arc alone — the two straight radii close the shape'};}, steps: function(v){ var arc=v.r*v.deg*Math.PI/180; return['Formula: Perimeter = 2r + rθ, θ in radians','Step 1: θ = '+v.deg+'° × π/180 = '+(v.deg*Math.PI/180).toFixed(4)+' rad','Step 2: Arc = r × θ = '+arc.toFixed(4),'Step 3: 2r + arc = '+(2*v.r)+' + '+arc.toFixed(4)+' = '+(2*v.r+arc).toFixed(4)];} }`,
`{ id: 'ellipse-perimeter', name: 'Ellipse Perimeter Calculator', desc: 'Ramanujan approximation of an ellipse outline', kw: 'ellipse perimeter calculator circumference ramanujan approximation', inputs: [{id:'a',label:'Semi-major Axis (a)',type:'number',def:5},{id:'b',label:'Semi-minor Axis (b)',type:'number',def:3}], calc: function(v){ if(v.a<=0||v.b<=0) return{result:'Axes must be positive',chart:'',extra:''}; var p=Math.PI*(3*(v.a+v.b)-Math.sqrt((3*v.a+v.b)*(v.a+3*v.b))); return{result:'Perimeter: '+(+p.toFixed(4)),chart:Charts.bar([p],['perimeter']),extra:'No elementary closed form exists — Ramanujan\\u2019s approximation is exact to within a fraction of a percent for any eccentricity'};}, steps: function(v){ var p=Math.PI*(3*(v.a+v.b)-Math.sqrt((3*v.a+v.b)*(v.a+3*v.b))); return['Formula: P ≈ π[3(a+b) − √((3a+b)(a+3b))]','Step 1: 3(a+b) = '+(3*(v.a+v.b)),'Step 2: √((3a+b)(a+3b)) = '+Math.sqrt((3*v.a+v.b)*(v.a+3*v.b)).toFixed(4),'Step 3: π × difference = '+p.toFixed(4)];} }`,
`{ id: 'rectangular-solid', name: 'Box Diagonal Calculator', desc: 'Space diagonal of a rectangular solid', kw: 'rectangular box diagonal calculator 3d cuboid space diagonal', inputs: [{id:'l',label:'Length',type:'number',def:3},{id:'w',label:'Width',type:'number',def:4},{id:'h',label:'Height',type:'number',def:12}], calc: function(v){ if(Math.min(v.l,v.w,v.h)<=0) return{result:'Dimensions must be positive',chart:'',extra:''}; var d=Math.sqrt(v.l*v.l+v.w*v.w+v.h*v.h); return{result:'Space Diagonal: '+(+d.toFixed(4)),chart:Charts.bar([v.l*v.w*v.h,d],['volume','diagonal']),extra:'Volume: '+(v.l*v.w*v.h)+' | The 3-4-12 box gives diagonal 13 — the 3D cousin of the 3-4-5 triangle'};}, steps: function(v){ var d=Math.sqrt(v.l*v.l+v.w*v.w+v.h*v.h); return['Formula: d = √(l² + w² + h²)','Step 1: '+v.l+'² + '+v.w+'² + '+v.h+'² = '+(v.l*v.l+v.w*v.w+v.h*v.h),'Step 2: √ = '+d.toFixed(4),'Apply Pythagoras twice: face diagonal first, then through the box'];} }`,
`{ id: 'triangular-prism', name: 'Triangular Prism Volume', desc: 'Triangle area times prism length', kw: 'triangular prism volume calculator base area length', inputs: [{id:'b',label:'Triangle Base',type:'number',def:6},{id:'h',label:'Triangle Height',type:'number',def:4},{id:'len',label:'Prism Length',type:'number',def:10}], calc: function(v){ if(Math.min(v.b,v.h,v.len)<=0) return{result:'All dimensions must be positive',chart:'',extra:''}; var vol=0.5*v.b*v.h*v.len; return{result:'Volume: '+(+vol.toFixed(4)),chart:Charts.bar([0.5*v.b*v.h,vol],['base area','volume']),extra:'Base area '+(0.5*v.b*v.h)+' × length '+v.len+' — a prism is its 2D face swept through 3D'};}, steps: function(v){ var vol=0.5*v.b*v.h*v.len; return['Formula: V = ½ × b × h × length','Step 1: Triangle area = ½ × '+v.b+' × '+v.h+' = '+(0.5*v.b*v.h),'Step 2: × length '+v.len+' = '+vol.toFixed(4)];} }`,
`{ id: 'octahedron-volume', name: 'Octahedron Volume', desc: 'Regular octahedron from its edge', kw: 'octahedron volume calculator regular platonic solid edge', inputs: [{id:'a',label:'Edge Length',type:'number',def:3}], calc: function(v){ if(v.a<=0) return{result:'Edge must be positive',chart:'',extra:''}; var vol=Math.SQRT2/3*Math.pow(v.a,3); return{result:'Volume: '+(+vol.toFixed(4)),chart:Charts.bar([vol],['volume']),extra:'Formula: √2/3 × a³ | Two square pyramids glued base-to-base — an octahedron is one of the five Platonic solids'};}, steps: function(v){ var vol=Math.SQRT2/3*Math.pow(v.a,3); return['Formula: V = (√2 ÷ 3) × a³','Step 1: a³ = '+Math.pow(v.a,3),'Step 2: × 0.4714 = '+vol.toFixed(4),'Doubling the edge multiplies volume by 8'];} }`,
`{ id: 'icosahedron-volume', name: 'Icosahedron Volume', desc: 'Regular 20-faced solid from its edge', kw: 'icosahedron volume calculator platonic solid edge golden ratio', inputs: [{id:'a',label:'Edge Length',type:'number',def:2}], calc: function(v){ if(v.a<=0) return{result:'Edge must be positive',chart:'',extra:''}; var vol=5*(3+Math.sqrt(5))/12*Math.pow(v.a,3); return{result:'Volume: '+(+vol.toFixed(4)),chart:Charts.bar([vol],['volume']),extra:'Formula: 5(3+√5)/12 × a³ — the √5 comes from the golden ratio hiding in the icosahedron\\u2019s geometry'};}, steps: function(v){ var vol=5*(3+Math.sqrt(5))/12*Math.pow(v.a,3); return['Formula: V = 5(3+√5)/12 × a³','Step 1: 5(3+√5)/12 = '+(5*(3+Math.sqrt(5))/12).toFixed(5),'Step 2: a³ = '+Math.pow(v.a,3),'Step 3: Product = '+vol.toFixed(4)];} }`,
`{ id: 'bitwise-xor', name: 'Bitwise XOR Calculator', desc: 'Exclusive-OR of two integers with binary shown', kw: 'bitwise xor calculator exclusive or binary bits integer', inputs: [{id:'a',label:'First Integer',type:'number',def:12},{id:'b',label:'Second Integer',type:'number',def:10}], calc: function(v){ var x=(v.a|0)^(v.b|0); return{result:x+'',chart:Charts.bar([v.a|0,v.b|0,x],['a','b','a XOR b']),extra:'Binary: '+((v.a|0)>>>0).toString(2)+' XOR '+((v.b|0)>>>0).toString(2)+' = '+(x>>>0).toString(2)+' | XOR is 1 only where bits differ; applying the same mask twice restores the original (the swap trick)'};}, steps: function(v){ var x=(v.a|0)^(v.b|0); return['Step 1: Write both numbers in binary','Step 2: '+((v.a|0)>>>0).toString(2)+' and '+((v.b|0)>>>0).toString(2),'Step 3: XOR column by column — differing bits give 1, matching bits give 0','Result: '+(x>>>0).toString(2)+' = '+x];} }`,
`{ id: 'shift-cipher', name: 'Caesar Shift Cipher', desc: 'Encode or decode text by shifting the alphabet', kw: 'caesar cipher calculator shift encode decode rot13', inputs: [{id:'text',label:'Text',type:'text',def:'hello'},{id:'shift',label:'Shift (0-25)',type:'number',def:3},{id:'mode',label:'1 = encode, 0 = decode',type:'number',def:1}], calc: function(v){ var s=((v.mode===1?v.shift:26-v.shift%26)%26+26)%26; var out=v.text.replace(/[a-zA-Z]/g,function(ch){var base=ch<='Z'?65:97; return String.fromCharCode((ch.charCodeAt(0)-base+s)%26+base);}); return{result:out,chart:Charts.bar([s],['shift']),extra:(v.mode===1?'Encoded':'Decoded')+' with shift '+s+' | Caesar shifted by 3: a becomes d | ROT13 is Caesar with shift 13, its own inverse'};}, steps: function(v){ var s=((v.mode===1?v.shift:26-v.shift%26)%26+26)%26; return['Step 1: '+(v.mode===1?'Encoding':'Decoding')+' shifts each letter by '+s+' position'+(s===1?'':'s')+(v.mode===1?' forward':' backward'),'Step 2: Non-letters pass through untouched','Step 3: Output: '+v.text.replace(/[a-zA-Z]/g,function(ch){var base=ch<='Z'?65:97; return String.fromCharCode((ch.charCodeAt(0)-base+s)%26+base);})];} }`,
`{ id: 'roman-numeral', name: 'Roman Numeral Converter', desc: 'Arabic to Roman numerals and back', kw: 'roman numeral converter calculator number to roman latin', inputs: [{id:'mode',label:'1 = number to Roman, 0 = Roman to number',type:'number',def:1},{id:'num',label:'Number (1-3999)',type:'number',def:2024},{id:'rom',label:'Roman numeral (if converting to number)',type:'text',def:'MMXXIV'}], calc: function(v){ var map=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']]; if(v.mode===1){ var n=Math.floor(v.num); if(n<1||n>3999) return{result:'Enter a number from 1 to 3999',chart:'',extra:''}; var out=''; for(var i=0;i<map.length;i++){ while(n>=map[i][0]){out+=map[i][1];n-=map[i][0];} } return{result:out,chart:Charts.gauge(Math.floor(v.num),4000),extra:'Subtractive pairs (IV, IX, XL, XC, CD, CM) keep the notation compact — Romans themselves often wrote IIII for 4'}; } var vals={I:1,V:5,X:10,L:50,C:100,D:500,M:1000}; var r=(v.rom||'').toUpperCase().replace(/[^IVXLCDM]/g,''); if(!r) return{result:'Enter a Roman numeral',chart:'',extra:''}; var total=0; for(var j=0;j<r.length;j++){ var cv=vals[r[j]]||0; var nv=j+1<r.length?(vals[r[j+1]]||0):0; total+= cv<nv?-cv:cv; } return{result:''+total,chart:Charts.bar([total],['value']),extra:'Subtractive rule: a smaller symbol before a larger one subtracts (IV = 4)'};}, steps: function(v){ if(v.mode===1) return['Step 1: Greedily match the value table from 1000 down to 1','Step 2: 2024 = MM (2000) + XX (20) + IV (4)','Roman numerals have no zero and no negative numbers']; return['Step 1: Read each symbol value: I=1 V=5 X=10 L=50 C=100 D=500 M=1000','Step 2: If a symbol precedes a larger one, subtract it','Step 3: Sum the rest'];} }`,
`{ id: 'units-per-person', name: 'Per Person Split', desc: 'Divide any total evenly across people', kw: 'per person calculator divide total people split share', inputs: [{id:'total',label:'Total Amount',type:'number',def:24},{id:'people',label:'People',type:'number',def:6}], calc: function(v){ if(v.people<=0) return{result:'People must be positive',chart:'',extra:''}; var each=v.total/v.people; return{result:'Each: '+(+each.toFixed(2)),chart:Charts.bar([each,v.people],['per person','people']),extra:'Leftover after even split: '+(v.total-(Math.floor(each)*v.people)).toFixed(2)+' | Works for dollars, liters, slices — anything divisible'};}, steps: function(v){ var each=v.total/v.people; return['Formula: each = total ÷ people','Step 1: '+v.total+' ÷ '+v.people+' = '+each.toFixed(4),'Step 2: Round to your needed precision — '+each.toFixed(2)+' per person'];} }`,
`{ id: 'rate-x-time', name: 'Distance = Rate × Time', desc: 'Solve any leg of the d = rt triangle', kw: 'distance rate time calculator speed travel d rt', inputs: [{id:'mode',label:'Solve for (1=d, 2=r, 3=t)',type:'number',def:1},{id:'a',label:'Known Value 1',type:'number',def:60},{id:'b',label:'Known Value 2',type:'number',def:3}], calc: function(v){ var r; if(v.mode===1) r={result:'Distance: '+(+v.a*v.b).toFixed(2),extra:v.a+' per unit × '+v.b+' units of time'}; else if(v.mode===2) r={result:'Rate: '+(+v.a/v.b).toFixed(4),extra:v.a+' distance ÷ '+v.b+' time'}; else r={result:'Time: '+(+v.a/v.b).toFixed(4),extra:v.a+' distance ÷ '+v.b+' rate'}; return{result:r.result,chart:Charts.bar([v.a],['known']),extra:r.extra+' | Average rate for a round trip is the harmonic mean, not the average of the two speeds'};}, steps: function(v){ var formulas={1:'d = r × t',2:'r = d ÷ t',3:'t = d ÷ r'}; var res=v.mode===1?v.a*v.b:v.a/v.b; return['Formula: '+formulas[v.mode],'Step 1: Substitute the two knowns','Step 2: Result = '+res.toFixed(4),'Keep units consistent: mph with hours, km/h with hours, never mixed'];} }`,
`{ id: 'work-rate-together', name: 'Combined Work Rate', desc: 'Time for two workers finishing one job', kw: 'work rate together calculator combined time two workers job', inputs: [{id:'a',label:'Worker A Time Alone (hours)',type:'number',def:6},{id:'b',label:'Worker B Time Alone (hours)',type:'number',def:3}], calc: function(v){ if(v.a<=0||v.b<=0) return{result:'Times must be positive',chart:'',extra:''}; var t=1/(1/v.a+1/v.b); return{result:'Together: '+t.toFixed(2)+' hours',chart:Charts.bar([v.a,v.b,t],['A alone','B alone','together']),extra:'Rates add: 1/'+v.a+' + 1/'+v.b+' = '+(1/v.a+1/v.b).toFixed(4)+' jobs per hour | The pair is always faster than the faster worker alone'};}, steps: function(v){ var t=1/(1/v.a+1/v.b); return['Formula: T = 1 ÷ (1/A + 1/B)','Step 1: A does '+(1/v.a).toFixed(4)+' of the job per hour, B does '+(1/v.b).toFixed(4),'Step 2: Combined rate = '+(1/v.a+1/v.b).toFixed(4),'Step 3: Time = 1 ÷ rate = '+t.toFixed(2)+' hours'];} }`,
`{ id: 'digital-root', name: 'Digital Root Calculator', desc: 'Repeated digit sum down to one digit', kw: 'digital root calculator digit sum casting out nines divisibility', inputs: [{id:'n',label:'Number',type:'number',def:98765}], calc: function(v){ var n=Math.abs(Math.floor(v.n)); if(!isFinite(n)) return{result:'Enter a valid integer',chart:'',extra:''}; var steps=[]; var x=n; while(x>=10){ var s=0; var t=x; while(t>0){s+=t%10;t=Math.floor(t/10);} steps.push(x+' → '+s); x=s; } return{result:'Digital Root: '+x,chart:Charts.bar([x],['root']),extra:steps.join(' | ')+' | Shortcut: digital root = 1 + (n−1) mod 9 — it is n mod 9, with 9 instead of 0'};}, steps: function(v){ var x=Math.abs(Math.floor(v.n)); var count=0; while(x>=10){ var s=0,t=x; while(t>0){s+=t%10;t=Math.floor(t/10);} x=s; count++; } return['Step 1: Add the digits of '+v.n,'Step 2: Repeat until a single digit remains ('+count+' pass'+(count===1?'':'es')+')','Step 3: Result: '+x,'Casting out nines uses this to check arithmetic: the root of a sum must match the sum of roots'];} }`,
`{ id: 'mixture-percent', name: 'Mixture Concentration', desc: 'Final strength after mixing two solutions', kw: 'mixture calculator concentration percent mixing solutions alligation', inputs: [{id:'v1',label:'Volume of Solution 1',type:'number',def:200},{id:'p1',label:'Concentration 1 (%)',type:'number',def:30},{id:'v2',label:'Volume of Solution 2',type:'number',def:300},{id:'p2',label:'Concentration 2 (%)',type:'number',def:10}], calc: function(v){ var tot=v.v1+v.v2; if(tot<=0) return{result:'Volumes must be positive',chart:'',extra:''}; var pure=v.v1*v.p1/100+v.v2*v.p2/100; var p=pure/tot*100; return{result:'Final: '+p.toFixed(2)+'%',chart:Charts.bar([v.v1*v.p1/100,v.v2*v.p2/100],['pure from 1','pure from 2']),extra:'Pure solute: '+(+pure.toFixed(2))+' in '+tot+' total — the result always lands between '+Math.min(v.p1,v.p2)+'% and '+Math.max(v.p1,v.p2)+'%'};}, steps: function(v){ var tot=v.v1+v.v2; var pure=v.v1*v.p1/100+v.v2*v.p2/100; var p=pure/tot*100; return['Step 1: Pure from 1 = '+v.v1+' × '+(v.p1/100)+' = '+(v.v1*v.p1/100),'Step 2: Pure from 2 = '+v.v2+' × '+(v.p2/100)+' = '+(v.v2*v.p2/100),'Step 3: '+(+pure.toFixed(2))+' ÷ '+tot+' × 100 = '+p.toFixed(2)+'%'];} }`
];

const QA_ROWS = [
  ['finance', 'apr-annual', { principal: 20000, fees: 2000, interest: 4800, years: 4 }, 8.5, 0.05, '(2000+4800)/20000/4'],
  ['finance', 'auto-lease-vs-buy', { lPay: 350, lDown: 2500, lTerm: 36, bPay: 450, bDown: 3000, bTerm: 60 }, 15100, 1, 'lease total'],
  ['finance', 'heloc-payment', { bal: 50000, rate: 8 }, 333.33, 0.5, '50000*0.08/12'],
  ['finance', 'pmi-drop', { bal: 152000, value: 200000 }, 76, 0.2, '152000/200000 %'],
  ['finance', 'escrow-analysis', { tax: 3600, ins: 1200 }, 466.67, 0.5, '4800*1.1667/12'],
  ['finance', 'portfolio-beta', { w1: 60, b1: 1.2, w2: 40, b2: 0.8 }, 1.04, 0.01, '0.6*1.2+0.4*0.8'],
  ['finance', 'yield-to-worst', { ytm: 5.2, ytc: 4.1 }, 4.1, 0.05, 'min'],
  ['finance', 'coupon-payment', { face: 1000, rate: 6, perYear: 2 }, 30, 0.1, '1000*0.06/2'],
  ['finance', 'clean-dirty-price', { dirty: 1025, accrued: 8.5 }, 1016.5, 0.1, '1025-8.5'],
  ['finance', 'convexity', { p0: 1000, pUp: 1019, pDn: 982, dy: 0.01 }, 10, 0.2, '(1019+982-2000)/(1000*0.0001)'],
  ['finance', 'duration-bond', { mac: 7.2, y: 6, perYear: 2 }, 6.99, 0.05, '7.2/1.03'],
  ['finance', 'appreciation-forecast', { val: 300000, g: 3, years: 10 }, 403175, 100, '300000*1.03^10'],
  ['finance', 'rent-vs-sell', { rentNet: 20000, sell: 350000, inv: 5, years: 10 }, 370098, 200, '570098-200000'],
  ['finance', 'seller-net', { price: 400000, comm: 6, closing: 3000, payoff: 250000 }, 123000, 10, '400000-24000-3000-250000'],
  ['finance', 'points-breakeven', { cost: 4000, save: 80 }, 50, 0.2, '4000/80 months'],
  ['finance', 'mortgage-recast', { bal: 280000, lump: 30000, rate: 6, months: 360 }, 1498.87, 1, '250000@6%/30y'],
  ['math', 'exponent-solver', { b: 2, e: 10 }, 1024, 0.5, '2^10'],
  ['math', 'nth-root', { x: 27, n: 3 }, 3, 0.01, 'cube root 27'],
  ['math', 'series-sum-ap', { a: 2, d: 3, n: 10 }, 155, 0.5, 'n/2(2a+(n-1)d)'],
  ['math', 'sigma-notation', { n: 10 }, 385, 0.5, 'sum of squares'],
  ['math', 'combination-repeat', { n: 5, k: 2 }, 15, 0.05, 'C(6,2)'],
  ['math', 'permutation-repeat', { n: 3, k: 4 }, 81, 0.05, '3^4'],
  ['math', 'probability-odds', { a: 3, b: 1 }, 75, 0.2, '3/4'],
  ['math', 'negative-binomial', { k: 2, n: 3, p: 0.5 }, 0.25, 0.005, 'C(2,1)*0.25*0.5'],
  ['math', 'circle-through-points', { a: 3, b: 4, c: 5 }, 2.5, 0.02, '345 triangle R'],
  ['math', 'secant-tangent', { s: 4, e: 5 }, 6, 0.05, 'sqrt(4*9)'],
  ['math', 'inscribed-angle', { central: 80 }, 40, 0.2, 'half central'],
  ['math', 'sector-perimeter', { r: 5, deg: 68.75 }, 16, 0.05, '10+5*1.2'],
  ['math', 'ellipse-perimeter', { a: 5, b: 3 }, 25.527, 0.05, 'Ramanujan 5,3'],
  ['math', 'rectangular-solid', { l: 3, w: 4, h: 12 }, 13, 0.05, 'sqrt(9+16+144)'],
  ['math', 'triangular-prism', { b: 6, h: 4, len: 10 }, 120, 0.5, '12*10'],
  ['math', 'octahedron-volume', { a: 3 }, 12.728, 0.05, 'sqrt2/3*27'],
  ['math', 'icosahedron-volume', { a: 2 }, 17.454, 0.05, '5(3+sqrt5)/12*8'],
  ['math', 'bitwise-xor', { a: 12, b: 10 }, 6, 0.05, '1100 xor 1010'],
  ['math', 'shift-cipher', { text: 'abc', shift: 3, mode: 1 }, 0, 0, 'text result (non-numeric)'],
  ['math', 'roman-numeral', { mode: 1, num: 2024, rom: '' }, 0, 0, 'text result (non-numeric)'],
  ['math', 'units-per-person', { total: 24, people: 6 }, 4, 0.05, '24/6'],
  ['math', 'rate-x-time', { mode: 1, a: 60, b: 3 }, 180, 0.5, '60*3'],
  ['math', 'work-rate-together', { a: 6, b: 3 }, 2, 0.05, '1/(1/6+1/3)'],
  ['math', 'digital-root', { n: 98765 }, 8, 0.05, '35 -> 8'],
  ['math', 'mixture-percent', { v1: 200, p1: 30, v2: 300, p2: 10 }, 18, 0.1, '(60+30)/500']
];

const check = process.argv.includes('--check');
for (const file of Object.keys(T)) {
  const fp = path.join(ROOT, 'js', 'data', file + '.js');
  let src = fs.readFileSync(fp, 'utf8');
  const ids = T[file].map(c => c.match(/id: '([^']+)'/)[1]);
  const present = ids.filter(id => src.includes("id: '" + id + "'"));
  if (present.length) { console.error('[ABORT] ' + file + ' already contains: ' + present.join(', ')); process.exit(1); }
  const anchor = src.lastIndexOf('\r\n];');
  if (anchor < 0) { console.error('[ABORT] no CRLF ]; tail in ' + file); process.exit(1); }
  const before = src.slice(0, anchor);
  const sep = /,\s*$/.test(before) ? '\r\n\r\n' : ',\r\n\r\n';
  const block = T[file].map(c => '  ' + c).join(',\r\n\r\n');
  const out = before + sep + block + src.slice(anchor);
  if (!check) {
    try { new Function(out); } catch (e) { console.error('[ABORT] ' + file + ' would not parse: ' + e.message); process.exit(1); }
    fs.writeFileSync(fp, out);
  }
  console.log('[ok] ' + file + ': +' + ids.length + ' tools');
}
const tfp = path.join(ROOT, 'tests', 'unit', 'formula-qa-full.test.js');
let tsrc = fs.readFileSync(tfp, 'utf8');
const firstRow = "['finance', 'apr-annual'";
if (tsrc.includes(firstRow)) { console.log('[skip] QA rows already present'); }
else {
  const start = tsrc.indexOf('const CASES = [');
  const close = tsrc.indexOf('\n];', start);
  if (start < 0 || close < 0) { console.error('[ABORT] CASES array not found'); process.exit(1); }
  tsrc = tsrc.slice(0, close) + '\n' + QA_ROWS.map(r => '  ' + JSON.stringify(r).replace(/"([a-zA-Z0-9_]+)":/g, '$1: ').replace(/,'/g, ", '").replace(/',/g, "', ").replace(/\{/g, '{ ').replace(/\}/g, ' }') + ',').join('\n') + tsrc.slice(close);
  if (!check) fs.writeFileSync(tfp, tsrc);
  console.log('[ok] +' + QA_ROWS.length + ' QA rows');
}
console.log((check ? '[DRY RUN] ' : '') + 'done: 42 tools');
