// Batch A3-F2b: 41 tools across 9 files. Usage: node scripts/a3-f2b.cjs [--check]
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const T = {};
T['engineering'] = [
`{ id: 'hydraulic-press', name: 'Hydraulic Press Force Calculator', desc: 'Output force from piston area ratio', kw: 'hydraulic press calculator force piston area pascal law', inputs: [{id:'f1',label:'Input Force (N)',type:'number',def:200},{id:'a1',label:'Input Piston Area (sq in)',type:'number',def:1},{id:'a2',label:'Output Piston Area (sq in)',type:'number',def:10}], calc: function(v){ if(v.a1<=0||v.a2<=0) return{result:'Piston areas must be positive',chart:'',extra:''}; var f2=v.f1*(v.a2/v.a1); return{result:'Output Force: '+f2.toFixed(0)+' N',chart:Charts.bar([v.f1,f2],['Input','Output']),extra:'Pascal\\u2019s law: pressure is equal everywhere, so force scales with piston area — the trade-off is distance: the input piston travels '+(v.a2/v.a1).toFixed(1)+'x further'};}, steps: function(v){ var f2=v.f1*(v.a2/v.a1); return['Formula: F2 = F1 × (A2 ÷ A1)','Step 1: Area ratio = '+v.a2+' ÷ '+v.a1+' = '+(v.a2/v.a1),'Step 2: '+v.f1+' × '+(v.a2/v.a1)+' = '+f2.toFixed(0)+' N','Work in equals work out — force multiplies, distance divides'];} }`,
`{ id: 'radiation-shielding', name: 'Radiation Shielding Calculator', desc: 'Intensity after absorber layers (half-value thickness)', kw: 'radiation shielding calculator half value layer hvl attenuation gamma xray', inputs: [{id:'i0',label:'Initial Intensity',type:'number',def:100},{id:'hvl',label:'Half-Value Layer (cm)',type:'number',def:2},{id:'x',label:'Shield Thickness (cm)',type:'number',def:6}], calc: function(v){ if(v.hvl<=0||v.x<0) return{result:'HVL must be positive',chart:'',extra:''}; var n=v.x/v.hvl; var i=v.i0*Math.pow(0.5,n); return{result:'Transmitted Intensity: '+i.toFixed(3),chart:Charts.bar([i,v.i0-i],['Transmitted','Absorbed']),extra:Math.floor(n)+' half-value layers attenuate '+(100-i/v.i0*100).toFixed(1)+'% — each HVL halves whatever remains, so absorption is exponential, never total'};}, steps: function(v){ var n=v.x/v.hvl; var i=v.i0*Math.pow(0.5,n); return['Formula: I = I0 × (1/2)^(x ÷ HVL)','Step 1: Layers = '+v.x+' ÷ '+v.hvl+' = '+n.toFixed(2),'Step 2: I = '+v.i0+' × 0.5^'+n.toFixed(2)+' = '+i.toFixed(3),'Adding one more HVL always halves the remaining dose — diminishing absolute returns'];} }`,
`{ id: 'steam-consumption', name: 'Steam Consumption Calculator', desc: 'Heat delivered by steam flow at a given latent heat', kw: 'steam consumption calculator latent heat boiler kg hour kw', inputs: [{id:'flow',label:'Steam Flow (kg/h)',type:'number',def:100},{id:'hfg',label:'Latent Heat (kJ/kg)',type:'number',def:2257}], calc: function(v){ if(v.flow<=0||v.hfg<=0) return{result:'Enter positive values',chart:'',extra:''}; var kw=v.flow*v.hfg/3600; return{result:'Heat Delivered: '+kw.toFixed(1)+' kW',chart:Charts.gauge(kw,200),extra:'Equivalent to '+(kw*3.412).toFixed(0)+' BTU/h — condensate load equals the steam flow, so size traps and returns for the same number'};}, steps: function(v){ var kw=v.flow*v.hfg/3600; return['Formula: Q = flow × hfg ÷ 3600 (kJ/h → kW)','Step 1: '+v.flow+' kg/h × '+v.hfg+' kJ/kg = '+(v.flow*v.hfg).toFixed(0)+' kJ/h','Step 2: ÷ 3600 s = '+kw.toFixed(1)+' kW','Latent heat falls as pressure rises — at 10 bar hfg is about 2015 kJ/kg, not 2257'];} }`,
`{ id: 'noise-level', name: 'Combined Noise Level Calculator', desc: 'Logarithmic sum of simultaneous sound sources', kw: 'combined noise level calculator decibel db addition sound sources', inputs: [{id:'l1',label:'Source 1 (dB)',type:'number',def:85},{id:'l2',label:'Source 2 (dB)',type:'number',def:88}], calc: function(v){ var tot=10*Math.log10(Math.pow(10,v.l1/10)+Math.pow(10,v.l2/10)); return{result:'Combined: '+tot.toFixed(1)+' dB',chart:Charts.gauge(tot,120),extra:'Decibels add logarithmically — two equal sources gain only +3 dB, never double the number | OSHA action level is 85 dB (8-hour TWA)'};}, steps: function(v){ var tot=10*Math.log10(Math.pow(10,v.l1/10)+Math.pow(10,v.l2/10)); return['Formula: L = 10·log10(10^(L1/10) + 10^(L2/10))','Step 1: 10^'+(v.l1/10)+' = '+Math.pow(10,v.l1/10).toExponential(2)+', 10^'+(v.l2/10)+' = '+Math.pow(10,v.l2/10).toExponential(2),'Step 2: Sum and take 10·log10 → '+tot.toFixed(1)+' dB','The louder source dominates: an 88 dB machine beside an 85 dB one raises the total under 3 dB above 88'];} }`
];
T['construction'] = [
`{ id: 'rafter-length', name: 'Rafter Length Calculator', desc: 'Hip and common rafter length from run and pitch', kw: 'rafter length calculator roof pitch run rise framing', inputs: [{id:'run',label:'Horizontal Run (ft)',type:'number',def:12},{id:'rise',label:'Rise (ft)',type:'number',def:5}], calc: function(v){ if(v.run<=0||v.rise<0) return{result:'Run must be positive',chart:'',extra:''}; var len=Math.sqrt(v.run*v.run+v.rise*v.rise); var pitch=v.rise/v.run*12; return{result:'Rafter Length: '+len.toFixed(2)+' ft',chart:Charts.bar([v.run,v.rise,len],['Run','Rise','Rafter']),extra:'Pitch: '+pitch.toFixed(1)+'/12 — order 10-15% extra for overhangs, ridge cuts, and waste'};}, steps: function(v){ var len=Math.sqrt(v.run*v.run+v.rise*v.rise); return['Formula: Rafter = √(run² + rise²) — the Pythagorean theorem','Step 1: '+v.run+'² + '+v.rise+'² = '+(v.run*v.run)+' + '+(v.rise*v.rise),'Step 2: √'+(v.run*v.run+v.rise*v.rise)+' = '+len.toFixed(2)+' ft','Add the overhang measured along the same slope, not horizontally'];} }`,
`{ id: 'shingle-squares', name: 'Shingle Squares Calculator', desc: 'Squares of shingles needed with waste factor', kw: 'shingle squares calculator roofing bundles waste factor', inputs: [{id:'area',label:'Roof Area (sq ft)',type:'number',def:2400},{id:'waste',label:'Waste Factor (%)',type:'number',def:10}], calc: function(v){ if(v.area<=0) return{result:'Area must be positive',chart:'',extra:''}; var sq=v.area/100*(1+v.waste/100); var bundles=Math.ceil(sq*3); return{result:sq.toFixed(1)+' squares ('+bundles+' bundles)',chart:Charts.bar([v.area/100,sq-v.area/100],['Base','Waste']),extra:'3 bundles per square is standard for 3-tab; architectural shingles often run 3-4 | Steep or cut-up roofs justify the higher waste %'};}, steps: function(v){ var sq=v.area/100*(1+v.waste/100); return['Step 1: Base squares = '+v.area+' ÷ 100 = '+(v.area/100).toFixed(1),'Step 2: Add '+v.waste+'% waste → '+sq.toFixed(1)+' squares','Step 3: Bundles = squares × 3, rounded up = '+Math.ceil(sq*3),'A square covers 100 sq ft of finished roof'];} }`,
`{ id: 'drywall-sheets', name: 'Drywall Sheets Calculator', desc: 'Sheet count from wall area with waste allowance', kw: 'drywall sheets calculator wall area 4x8 boards waste', inputs: [{id:'area',label:'Wall Area (sq ft)',type:'number',def:800},{id:'sheet',label:'Sheet Size (sq ft)',type:'number',def:32},{id:'waste',label:'Waste Factor (%)',type:'number',def:10}], calc: function(v){ if(v.area<=0||v.sheet<=0) return{result:'Enter positive areas',chart:'',extra:''}; var sheets=Math.ceil(v.area/v.sheet*(1+v.waste/100)); return{result:sheets+' sheets',chart:Charts.bar([v.area/v.sheet,Math.ceil(v.area/v.sheet*(1+v.waste/100))-v.area/v.sheet],['Base sheets','Waste']),extra:'4x8 sheet = 32 sq ft, 4x12 = 48 | Vertical hanging on 8 ft walls avoids horizontal seams and tapering labour'};}, steps: function(v){ var base=v.area/v.sheet; return['Step 1: Base sheets = '+v.area+' ÷ '+v.sheet+' = '+base.toFixed(1),'Step 2: Apply '+v.waste+'% waste and round up → '+Math.ceil(base*(1+v.waste/100))+' sheets','Ceilings count too — add them to the area before waste'];} }`,
`{ id: 'tile-boxes', name: 'Tile Boxes Calculator', desc: 'Boxes of tile for a floor with breakage allowance', kw: 'tile boxes calculator floor area coverage breakage waste', inputs: [{id:'area',label:'Floor Area (sq ft)',type:'number',def:200},{id:'box',label:'Coverage per Box (sq ft)',type:'number',def:20},{id:'waste',label:'Breakage & Cuts (%)',type:'number',def:10}], calc: function(v){ if(v.area<=0||v.box<=0) return{result:'Enter positive values',chart:'',extra:''}; var boxes=Math.ceil(v.area/v.box*(1+v.waste/100)); return{result:boxes+' boxes',chart:Charts.bar([v.area/v.box,Math.ceil(v.area/v.box*(1+v.waste/100))-v.area/v.box],['Base','Waste']),extra:'Order from one dye lot — mixing lots shows as shade bands across the floor | Diagonal layouts want 15%+ waste'};}, steps: function(v){ var base=v.area/v.box; return['Step 1: Base boxes = '+v.area+' ÷ '+v.box+' = '+base.toFixed(1),'Step 2: With '+v.waste+'% allowance and rounding up → '+Math.ceil(base*(1+v.waste/100))+' boxes','Keep 1 spare box per job for future repairs — dye lots retire'];} }`
];
T['everyday'] = [
`{ id: 'sunrise-sunset-length', name: 'Daylight Length Calculator', desc: 'Hours of daylight by latitude and season', kw: 'daylight hours calculator sunrise sunset length latitude season', inputs: [{id:'lat',label:'Latitude (degrees, +north)',type:'number',def:40},{id:'decl',label:'Solar Declination (deg: 23.44 solstice, 0 equinox)',type:'number',def:23.44}], calc: function(v){ if(v.lat<-90||v.lat>90) return{result:'Latitude must be between -90 and 90',chart:'',extra:''}; var x=-Math.tan(v.lat*Math.PI/180)*Math.tan(v.decl*Math.PI/180); if(x<-1||x>1) return{result:'Polar day or night — the sun does not rise (or set) at this latitude and declination',chart:'',extra:''}; var dayLen=24/Math.PI*Math.acos(x); return{result:'Daylight: '+dayLen.toFixed(2)+' hours',chart:Charts.bar([dayLen,24-dayLen],['Day','Night']),extra:'Sunrise '+(12-dayLen/2).toFixed(2)+', sunset '+(12+dayLen/2).toFixed(2)+' solar time | Equation of time shifts real clock times by up to ±16 minutes'};}, steps: function(v){ var x=-Math.tan(v.lat*Math.PI/180)*Math.tan(v.decl*Math.PI/180); var dayLen=24/Math.PI*Math.acos(x); return['Formula: Day length = (24/π) × arccos(−tan(lat) × tan(decl))','Step 1: −tan('+v.lat+'°) × tan('+v.decl+'°) = '+x.toFixed(4),'Step 2: arccos('+x.toFixed(4)+') = '+(Math.acos(x)*180/Math.PI).toFixed(2)+'°','Step 3: × 24/180 × ... = '+dayLen.toFixed(2)+' hours','At the equinoxes decl is 0 and every latitude gets 12 hours'];} }`,
`{ id: 'pomodoro-planner', name: 'Pomodoro Planner', desc: 'Total time for pomodoro sessions with breaks', kw: 'pomodoro calculator sessions breaks 25 5 study planner', inputs: [{id:'sessions',label:'Pomodoro Sessions',type:'number',def:8},{id:'work',label:'Work Minutes Each',type:'number',def:25},{id:'brk',label:'Break Minutes Each',type:'number',def:5}], calc: function(v){ if(v.sessions<=0) return{result:'Sessions must be positive',chart:'',extra:''}; var total=v.sessions*(v.work+v.brk); var work=v.sessions*v.work; return{result:'Total: '+(total/60).toFixed(1)+' hours ('+total+' min)',chart:Charts.bar([work,total-work],['Focused work','Breaks']),extra:'Focused work: '+work+' min, breaks: '+(total-work)+' min | After every 4th pomodoro take a longer 15-30 minute break'};}, steps: function(v){ var total=v.sessions*(v.work+v.brk); return['Step 1: Per cycle = '+v.work+' work + '+v.brk+' break = '+(v.work+v.brk)+' min','Step 2: '+v.sessions+' cycles × '+(v.work+v.brk)+' = '+total+' min = '+(total/60).toFixed(1)+' h','The method trains focus by making the break non-negotiable — protect both halves'];} }`,
`{ id: 'gift-wrap', name: 'Gift Wrap Calculator', desc: 'Paper area needed for a box', kw: 'gift wrap calculator wrapping paper box size area', inputs: [{id:'l',label:'Box Length (cm)',type:'number',def:40},{id:'w',label:'Box Width (cm)',type:'number',def:30},{id:'h',label:'Box Height (cm)',type:'number',def:15}], calc: function(v){ if(Math.min(v.l,v.w,v.h)<=0) return{result:'All dimensions must be positive',chart:'',extra:''}; var area=2*(v.w+v.h)*(v.l+2*v.h); return{result:'Paper: '+(area/10000).toFixed(2)+' sq m ('+area.toFixed(0)+' sq cm)',chart:Charts.bar([area/10000],['m2 needed']),extra:'Formula covers wrap-over and tuck ends — add 10% for patterned paper where you cannot rotate pieces'};}, steps: function(v){ var area=2*(v.w+v.h)*(v.l+2*v.h); return['Formula: Area = 2(W + H) × (L + 2H)','Step 1: 2('+v.w+' + '+v.h+') = '+(2*(v.w+v.h))+' cm wide strip','Step 2: ('+v.l+' + 2×'+v.h+') = '+(v.l+2*v.h)+' cm long','Step 3: Area = '+(2*(v.w+v.h))+' × '+(v.l+2*v.h)+' = '+area.toFixed(0)+' sq cm'];} }`,
`{ id: 'moving-truck', name: 'Moving Truck Size Calculator', desc: 'Truck volume from furnished rooms', kw: 'moving truck size calculator rooms cubic feet rental', inputs: [{id:'rooms',label:'Rooms of Furniture',type:'number',def:3},{id:'cf',label:'Cubic Feet per Room',type:'number',def:150}], calc: function(v){ if(v.rooms<=0||v.cf<=0) return{result:'Enter positive values',chart:'',extra:''}; var vol=v.rooms*v.cf; var truck=vol<=300?'10-12 ft cargo van':vol<=450?'14-17 ft truck':vol<=650?'20 ft truck':vol<=850?'24-26 ft truck':'multiple trips or larger'; return{result:vol.toFixed(0)+' cu ft — '+truck,chart:Charts.bar([vol],['volume']),extra:'Rule of thumb: 150-200 cu ft per furnished room plus 50 for every heavily-furnished space | Load heaviest items first against the cab wall'};}, steps: function(v){ var vol=v.rooms*v.cf; return['Step 1: '+v.rooms+' rooms × '+v.cf+' cu ft = '+vol.toFixed(0)+' cu ft','Step 2: Match against common truck sizes: van 300, 15 ft 450, 20 ft 650, 26 ft 850','Garage items, patio sets, and boxes add up — count them as rooms too'];} }`,
`{ id: 'jet-lag', name: 'Jet Lag Recovery Calculator', desc: 'Recovery days for eastward or westward travel', kw: 'jet lag calculator recovery days time zones east west', inputs: [{id:'zones',label:'Time Zones Crossed',type:'number',def:7},{id:'dir',label:'Direction (1=east, 0=west)',type:'number',def:1}], calc: function(v){ if(v.zones<=0||v.zones>12) return{result:'Enter zones between 1 and 12',chart:'',extra:''}; var days=v.zones*(v.dir===1?1:0.6); return{result:'Recovery: about '+days.toFixed(1)+' days',chart:Charts.bar([days,days],['days']),extra:(v.dir===1?'Eastward':'Westward')+' travel — flying east shortens your day and is harder; '+(v.dir===1?'':':westward is about 40% easier')+' | Morning bright light shifts your clock the right way after eastward flights'};}, steps: function(v){ var days=v.zones*(v.dir===1?1:0.6); return['Rule of thumb: ~1 day per zone eastward, ~0.6 westward','Step 1: '+v.zones+' zones × '+(v.dir===1?'1':'0.6')+' = '+days.toFixed(1)+' days','Speed it up: shift sleep an hour daily before departure, get morning light at destination, and stay awake to local bedtime'];} }`,
`{ id: 'heat-pump-savings', name: 'Heat Pump Savings Calculator', desc: 'Annual savings versus electric resistance heating', kw: 'heat pump savings calculator cop electric resistance annual cost', inputs: [{id:'load',label:'Annual Heating Need (kWh)',type:'number',def:12000},{id:'rate',label:'Electricity Rate ($/kWh)',type:'number',def:0.15},{id:'cop',label:'Heat Pump COP',type:'number',def:3}], calc: function(v){ if(v.load<=0||v.rate<=0||v.cop<=0) return{result:'Enter positive values',chart:'',extra:''}; var res=v.load*v.rate; var hp=v.load*v.rate/v.cop; var sav=res-hp; return{result:'Savings: $'+sav.toFixed(0)+'/year',chart:Charts.bar([res,hp],['Resistance','Heat pump']),extra:'Resistance cost $'+res.toFixed(0)+', heat pump $'+hp.toFixed(0)+' | COP falls in deep cold — size savings on the seasonal average, not the rated peak'};}, steps: function(v){ var res=v.load*v.rate; var hp=v.load*v.rate/v.cop; return['Step 1: Resistance cost = '+v.load+' kWh × $'+v.rate+' = $'+res.toFixed(0),'Step 2: Heat pump draws load ÷ COP = '+(v.load/v.cop).toFixed(0)+' kWh → $'+hp.toFixed(0),'Step 3: Savings = $'+sav.toFixed(0)+' per year','Every unit of electricity moves '+v.cop.toFixed(1)+' units of heat — that is the whole trick'];} }`
];
T['lifestyle'] = [
`{ id: 'french-press-ratio', name: 'French Press Ratio Calculator', desc: 'Coffee grams for a water amount at your ratio', kw: 'french press ratio calculator coffee grams water brew', inputs: [{id:'water',label:'Water (grams/ml)',type:'number',def:500},{id:'ratio',label:'Ratio (water : coffee)',type:'number',def:15}], calc: function(v){ if(v.water<=0||v.ratio<10) return{result:'Enter positive water; ratio is usually 12-17',chart:'',extra:''}; var g=v.water/v.ratio; return{result:'Coffee: '+g.toFixed(1)+' g',chart:Charts.gauge(g,60),extra:'Ratio 1:'+v.ratio+' | Steep 4 minutes, break the crust, plunge slowly — grind coarse like sea salt'};}, steps: function(v){ var g=v.water/v.ratio; return['Formula: coffee = water ÷ ratio','Step 1: '+v.water+' g ÷ '+v.ratio+' = '+g.toFixed(1)+' g','Stronger brew = smaller ratio number (1:12); lighter = larger (1:17)','Weigh the beans before grinding — scoop volume lies'];} }`,
`{ id: 'cocktail-dilution', name: 'Cocktail Dilution Calculator', desc: 'Final ABV after stirring or shaking with ice', kw: 'cocktail dilution calculator abv stir shake ice percent', inputs: [{id:'vol',label:'Drink Volume (ml)',type:'number',def:100},{id:'abv',label:'Starting ABV (%)',type:'number',def:40},{id:'dil',label:'Dilution (% of volume)',type:'number',def:25}], calc: function(v){ if(v.vol<=0||v.abv<0||v.dil<0) return{result:'Enter valid values',chart:'',extra:''}; var final=v.vol*v.abv/100/(v.vol*(1+v.dil/100))*100; return{result:'Final ABV: '+final.toFixed(1)+'%',chart:Charts.bar([v.abv,final],['Start','Final']),extra:'Stirred drinks dilute about 20-25%, shaken about 25-30% — taste and temperature, not just numbers, tell you when to stop'};}, steps: function(v){ var final=v.vol*v.abv/100/(v.vol*(1+v.dil/100))*100; return['Step 1: Pure alcohol = '+v.vol+' ml × '+(v.abv/100)+' = '+(v.vol*v.abv/100).toFixed(1)+' ml','Step 2: New volume = '+v.vol+' × '+(1+v.dil/100)+' = '+(v.vol*(1+v.dil/100)).toFixed(0)+' ml','Step 3: ABV = '+(v.vol*v.abv/100).toFixed(1)+' ÷ '+(v.vol*(1+v.dil/100)).toFixed(0)+' = '+final.toFixed(1)+'%'];} }`,
`{ id: 'wine-servings', name: 'Wine Servings Calculator', desc: 'Glasses from bottles at standard pours', kw: 'wine servings calculator glasses bottle standard pour', inputs: [{id:'bottles',label:'Bottles',type:'number',def:3},{id:'pour',label:'Ounces per Glass',type:'number',def:5}], calc: function(v){ if(v.bottles<=0||v.pour<=0) return{result:'Enter positive values',chart:'',extra:''}; var g=Math.floor(25.4/v.pour*v.bottles); return{result:g+' glasses',chart:Charts.bar([g],['glasses']),extra:'A 750 ml bottle holds 25.4 oz — five 5-oz glasses is the standard restaurant pour; home pours drift larger, plan 4'};}, steps: function(v){ var g=Math.floor(25.4/v.pour*v.bottles); return['Step 1: Total ounces = '+v.bottles+' × 25.4 = '+(v.bottles*25.4).toFixed(1),'Step 2: ÷ '+v.pour+' oz per glass = '+(v.bottles*25.4/v.pour).toFixed(1),'Step 3: Floor for full pours = '+g+' glasses','For parties: budget half a bottle per wine-drinking guest for a 2-3 hour evening'];} }`,
`{ id: 'baking-scale', name: 'Recipe Scaling Calculator', desc: 'Scale any recipe proportionally from the flour weight', kw: 'recipe scaling calculator baker percentages flour scale baking', inputs: [{id:'base',label:'Original Flour (g)',type:'number',def:500},{id:'new',label:'New Flour (g)',type:'number',def:750},{id:'water',label:'Original Water (g)',type:'number',def:325}], calc: function(v){ if(v.base<=0) return{result:'Base flour must be positive',chart:'',extra:''}; var f=v.new/v.base; var nw=v.water*f; return{result:'New water: '+nw.toFixed(0)+' g',chart:Charts.bar([v.water,nw],['Original','Scaled']),extra:'Scale factor '+f.toFixed(3)+' — multiply every ingredient by it | Baking time barely changes with size; temperature stays put'};}, steps: function(v){ var f=v.new/v.base; return['Step 1: Factor = '+v.new+' ÷ '+v.base+' = '+f.toFixed(3),'Step 2: Water = '+v.water+' × '+f.toFixed(3)+' = '+(v.water*f).toFixed(0)+' g','Step 3: Apply the same factor to salt, starter, and every other ingredient','Baker percentages make this automatic: flour is always 100%'];} }`,
`{ id: 'sourdough-hydration', name: 'Sourdough Hydration Calculator', desc: 'Dough hydration percent from flour and water', kw: 'sourdough hydration calculator dough water flour percent', inputs: [{id:'water',label:'Water (g)',type:'number',def:350},{id:'flour',label:'Flour (g)',type:'number',def:500}], calc: function(v){ if(v.flour<=0) return{result:'Flour must be positive',chart:'',extra:''}; var h=v.water/v.flour*100; return{result:'Hydration: '+h.toFixed(0)+'%',chart:Charts.gauge(h,110),extra:'70% is the all-purpose sweet spot — whole grain absorbs more, so the same number feels drier in a white loaf than a rye one'};}, steps: function(v){ var h=v.water/v.flour*100; return['Formula: Hydration = water ÷ flour × 100','Step 1: '+v.water+' ÷ '+v.flour+' = '+(v.water/v.flour).toFixed(3),'Step 2: × 100 = '+h.toFixed(0)+'%','Count starter flour and water separately for precision — most recipes fold it in roughly'];} }`,
`{ id: 'lawn-fertilizer', name: 'Lawn Fertilizer Calculator', desc: 'Product weight to hit a nitrogen rate', kw: 'lawn fertilizer calculator nitrogen rate lb per 1000 sq ft product', inputs: [{id:'area',label:'Lawn Area (sq ft)',type:'number',def:5000},{id:'rate',label:'Nitrogen Rate (lb per 1000 sq ft)',type:'number',def:1},{id:'npct',label:'Product N % (e.g. 29 for 29-0-4)',type:'number',def:29}], calc: function(v){ if(v.area<=0||v.npct<=0) return{result:'Enter positive values',chart:'',extra:''}; var nLb=v.area/1000*v.rate; var product=nLb/(v.npct/100); return{result:'Product: '+product.toFixed(1)+' lb',chart:Charts.bar([nLb,product-nLb],['Pure N','Filler']),extra:'Pure nitrogen needed: '+nLb.toFixed(2)+' lb | Calibrate the spreader — half-speed in two perpendicular passes beats one fast pass for even colour'};}, steps: function(v){ var nLb=v.area/1000*v.rate; var product=nLb/(v.npct/100); return['Step 1: N needed = '+v.area+' ÷ 1000 × '+v.rate+' = '+nLb.toFixed(2)+' lb N','Step 2: Product = N ÷ N% = '+nLb.toFixed(2)+' ÷ '+(v.npct/100)+' = '+product.toFixed(1)+' lb','Soluble N feeds fast for 4-6 weeks; slow-release stretches the same rate over 8-10'];} }`,
`{ id: 'candle-wax', name: 'Candle Wax Calculator', desc: 'Wax weight for a batch of container candles', kw: 'candle wax calculator container ounces batch soy', inputs: [{id:'jars',label:'Number of Jars',type:'number',def:12},{id:'oz',label:'Jar Size (oz)',type:'number',def:8}], calc: function(v){ if(v.jars<=0||v.oz<=0) return{result:'Enter positive values',chart:'',extra:''}; var wax=v.jars*v.oz*0.86; return{result:'Wax: '+wax.toFixed(1)+' oz',chart:Charts.bar([wax],['wax oz']),extra:'Fill containers to about 85-90% — wax is ~86% the density of water | Fragrance load 6-10% is by wax weight, add it on top'};}, steps: function(v){ var wax=v.jars*v.oz*0.86; return['Step 1: Total container volume = '+v.jars+' × '+v.oz+' oz = '+(v.jars*v.oz),'Step 2: × 0.86 (wax density vs water) = '+wax.toFixed(1)+' oz wax','Melt point and pour temp differ by wax type — soy around 85 °C melt, pour near 70-80 °C'];} }`,
`{ id: 'knit-gauge', name: 'Knitting Cast-On Calculator', desc: 'Stitches to cast on from gauge and width', kw: 'knitting cast on calculator gauge stitches per inch width', inputs: [{id:'width',label:'Finished Width (inches)',type:'number',def:20},{id:'spi',label:'Gauge (stitches per inch)',type:'number',def:5}], calc: function(v){ if(v.width<=0||v.spi<=0) return{result:'Enter positive values',chart:'',extra:''}; var st=Math.round(v.width*v.spi); return{result:'Cast on '+st+' stitches',chart:Charts.bar([st],['stitches']),extra:'Always knit a 4-inch swatch and wash it — gauge lies until blocked | Add 2 edge stitches if your pattern does not include selvedges'};}, steps: function(v){ var st=Math.round(v.width*v.spi); return['Formula: Stitches = width × gauge','Step 1: '+v.width+' in × '+v.spi+' sts/in = '+st+' stitches','Re-measure gauge mid-project — tension drifts with mood and yarn batch'];} }`,
`{ id: 'quilt-fabric', name: 'Quilt Backing Calculator', desc: 'Yardage for a quilt backing with seams', kw: 'quilt backing calculator yardage fabric width seam allowance', inputs: [{id:'w',label:'Quilt Width (inches)',type:'number',def:60},{id:'h',label:'Quilt Height (inches)',type:'number',def:80},{id:'fw',label:'Fabric Width (inches)',type:'number',def:42}], calc: function(v){ if(Math.min(v.w,v.h,v.fw)<=0) return{result:'Enter positive values',chart:'',extra:''}; var needW=v.w+8, needH=v.h+8; var panels=Math.ceil(needW/(v.fw-1)); var len=panels*needH/36; return{result:len.toFixed(2)+' yards',chart:Charts.bar([panels],['panels']),extra:'Backing should overhang 4 inches per side | Join panels with a 1/2 inch seam, pressed open, and remove the selvedges first'};}, steps: function(v){ var needW=v.w+8, needH=v.h+8; var panels=Math.ceil(needW/(v.fw-1)); var len=panels*needH/36; return['Step 1: Backing size = '+(v.w+8)+' × '+(v.h+8)+' in (4 in overhang each side)','Step 2: Panels across = ceil('+needW+' ÷ '+(v.fw-1)+') = '+panels,'Step 3: Length = '+panels+' × '+needH+' in ÷ 36 = '+len.toFixed(2)+' yards'];} }`
];
T['parenting-family'] = [
`{ id: 'baby-milestones', name: 'Baby Milestones Guide', desc: 'Typical milestones reached by a given age', kw: 'baby milestones calculator month development typical age', inputs: [{id:'months',label:'Baby Age (months)',type:'number',def:9}], calc: function(v){ var m=v.months; if(m<0||m>36) return{result:'Enter an age from 0 to 36 months',chart:'',extra:''}; var list=[]; if(m>=2) list.push('social smile'); if(m>=4) list.push('rolls over, laughs'); if(m>=6) list.push('sits, babbles'); if(m>=9) list.push('crawls, stranger wariness'); if(m>=12) list.push('walks, first words'); if(m>=18) list.push('runs, 10+ words'); if(m>=24) list.push('2-word phrases, kicks ball'); if(m>=30) list.push('jumps, dresses with help'); if(m>=36) list.push('pedals tricycle, 3-word sentences'); return{result:'By '+m+' months, typically: '+(list.length?list.join('; '):'newborn reflexes and feeding'),chart:Charts.gauge(m,36),extra:'Ranges are wide — a skill arriving a month or two late alone is not a delay | Persistent asymmetry, loss of skills, or no babble by 9 months deserves a pediatric check'};}, steps: function(v){ return['Step 1: Entered age '+v.months+' months','Step 2: Milestones are windows, not deadlines — most lists show the age when 75% of children can do the skill','Step 3: Compare with the typical list above and with your own pediatrician\\u2019s screening at well visits','Track progress over weeks, not days'];} }`,
`{ id: 'child-support-split', name: 'Child Support Split Calculator', desc: 'Income-proportional share of a base support amount', kw: 'child support split calculator income share percentage parents', inputs: [{id:'mine',label:'Your Monthly Income ($)',type:'number',def:5000},{id:'other',label:'Other Parent Income ($)',type:'number',def:3000},{id:'base',label:'Base Support Need ($/mo)',type:'number',def:1200}], calc: function(v){ var tot=v.mine+v.other; if(tot<=0) return{result:'Incomes must be positive',chart:'',extra:''}; var share=v.base*v.mine/tot; return{result:'Your share: $'+share.toFixed(0)+' ('+(v.mine/tot*100).toFixed(0)+'%)',chart:Charts.bar([share,v.base-share],['Your share','Other parent']),extra:'This proportional model mirrors how most state guidelines start — actual orders add healthcare, childcare, and parenting-time adjustments'};}, steps: function(v){ var tot=v.mine+v.other; var share=v.base*v.mine/tot; return['Step 1: Combined income = $'+tot.toLocaleString(),'Step 2: Your share = '+v.mine+' ÷ '+tot+' = '+(v.mine/tot*100).toFixed(0)+'%','Step 3: × base need $'+v.base+' = $'+share.toFixed(0)+' per month','Courts use statutory worksheets — this estimates the proportional logic, not the legal order'];} }`,
`{ id: 'family-tree-generation', name: 'Ancestor Count Calculator', desc: 'Ancestors at each generation back', kw: 'family tree ancestor count calculator generations genealogy doubling', inputs: [{id:'gen',label:'Generations Back',type:'number',def:5}], calc: function(v){ if(v.gen<0||v.gen>20) return{result:'Enter generations from 0 to 20',chart:'',extra:''}; var count=Math.pow(2,v.gen); var total=Math.pow(2,v.gen+1)-2; return{result:'Ancestors at generation '+v.gen+': '+count,chart:Charts.bar([count,total],['this gen','all gens']),extra:'Total across all generations back to here: '+total+' | Pedigree collapse means real numbers fall below the doubling — cousins marrying cousins is universal in deep trees'};}, steps: function(v){ var count=Math.pow(2,v.gen); return['Formula: ancestors = 2^generation','Step 1: 2^'+v.gen+' = '+count,'Each person has 2 parents, 4 grandparents, 8 great-grandparents — doubling each step back'];} }`
];
T['education'] = [
`{ id: 'assignment-split', name: 'Grade Weighting Calculator', desc: 'Current course grade from weighted components', kw: 'grade weighting calculator current grade needed final exam', inputs: [{id:'score',label:'Current Score (%)',type:'number',def:90},{id:'worth',label:'Component Weight (%)',type:'number',def:40}], calc: function(v){ if(v.score<0||v.worth<0||v.worth>100) return{result:'Enter valid score and weight',chart:'',extra:''}; var contrib=v.score*v.worth/100; var remaining=100-v.worth; var needFinal=v.worth<100?(72-contrib)/(remaining/100):0; return{result:'Contribution: '+contrib.toFixed(1)+' points',chart:Charts.bar([contrib,100-contrib],['Earned','Still possible']),extra:'These points are locked in | To finish with 72 overall you would need about '+Math.max(0,needFinal).toFixed(1)+'% of the remaining '+remaining+'%'};}, steps: function(v){ var contrib=v.score*v.worth/100; return['Formula: contribution = score × weight','Step 1: '+v.score+'% × '+(v.worth/100)+' = '+contrib.toFixed(1)+' points','Step 2: Remaining weight = '+(100-v.worth)+'% of the course','Weighted grading means early low scores are recoverable if their weight was small'];} }`,
`{ id: 'citation-count', name: 'H-Index Calculator', desc: 'h-index from a citation count list', kw: 'h index calculator citations researcher impact publication', inputs: [{id:'cites',label:'Citations per paper (comma separated)',type:'text',def:'10,8,5,3,1'}], calc: function(v){ var c=v.cites.split(',').map(Number).filter(function(x){return !isNaN(x);}); c.sort(function(a,b){return b-a;}); var h=0; for(var i=0;i<c.length;i++){ if(c[i]>=i+1) h=i+1; else break; } return{result:'h-index: '+h,charchart:'',chart:Charts.bar(c.slice(0,8),c.slice(0,8).map(function(_,i){return '#'+(i+1);})),extra:h+' papers have at least '+h+' citations each | The h-index rewards sustained output — one blockbuster paper cannot push it up alone'};}, steps: function(v){ var c=v.cites.split(',').map(Number).filter(function(x){return !isNaN(x);}); c.sort(function(a,b){return b-a;}); return['Step 1: Sort citations descending: '+c.join(', '),'Step 2: Find the largest h where the h-th paper has at least h citations','Step 3: Compare each position with its rank — the last position that clears it is the h-index'];} }`,
`{ id: 'essay-length', name: 'Reading Time Calculator', desc: 'Minutes to read or present a word count', kw: 'reading time calculator words per minute speech presentation length', inputs: [{id:'words',label:'Word Count',type:'number',def:750},{id:'wpm',label:'Speed (words per minute)',type:'number',def:150}], calc: function(v){ if(v.words<=0||v.wpm<=0) return{result:'Enter positive values',chart:'',extra:''}; var min=v.words/v.wpm; return{result:min.toFixed(1)+' minutes',chart:Charts.bar([min],['minutes']),extra:'Silent reading averages 200-250 wpm; speaking pace is 120-150 wpm — a 750-word speech runs about 5 minutes'};}, steps: function(v){ var min=v.words/v.wpm; return['Formula: minutes = words ÷ wpm','Step 1: '+v.words+' ÷ '+v.wpm+' = '+min.toFixed(2),'Step 2: Add pauses — presentations run 10-20% longer than the raw count'];} }`
];
T['career-freelance'] = [
`{ id: 'vacation-days', name: 'Vacation Accrual Calculator', desc: 'Days banked at an annual rate over months worked', kw: 'vacation accrual calculator pto days earned months worked', inputs: [{id:'rate',label:'Annual PTO Days',type:'number',def:15},{id:'months',label:'Months Worked',type:'number',def:8}], calc: function(v){ if(v.rate<0||v.months<0) return{result:'Enter non-negative values',chart:'',extra:''}; var days=v.rate*v.months/12; return{result:'Accrued: '+days.toFixed(1)+' days',chart:Charts.bar([days,v.rate-days],['Earned','Remaining']),extra:v.rate+' days/year ≈ '+Math.round(v.rate*8)+' hours | Many plans front-load on Jan 1; others accrue per paycheck — check which yours is before a long trip'};}, steps: function(v){ var days=v.rate*v.months/12; return['Formula: accrued = annual days × months ÷ 12','Step 1: '+v.rate+' × '+(v.months/12)+' = '+days.toFixed(1)+' days','Hours vs days matters for partial-day requests — HR systems track one or the other'];} }`,
`{ id: 'timesheet-hours', name: 'Timesheet Decimal Converter', desc: 'Convert hh:mm entries to decimal hours', kw: 'timesheet decimal hours calculator hh mm payroll convert', inputs: [{id:'times',label:'Time entries (comma separated hh:mm)',type:'text',def:'8:30,7:45,8:00'}], calc: function(v){ var parts=v.times.split(',').map(function(s){var m=s.trim().match(/^(\\d+):(\\d+)$/); return m?+m[1]+ +m[2]/60:NaN;}); if(parts.some(isNaN)) return{result:'Use hh:mm format, e.g. 8:30,7:45',chart:'',extra:''}; var tot=parts.reduce(function(a,b){return a+b;},0); return{result:'Total: '+tot.toFixed(2)+' hours',chart:Charts.bar(parts,parts.map(function(_,i){return 'D'+(i+1);})),extra:'Payroll wants decimals: 8:30 becomes 8.5, never 8.30 — that 0.30 reads as 18 minutes and shortchecks your pay'};}, steps: function(v){ var parts=v.times.split(',').map(function(s){var m=s.trim().match(/^(\\d+):(\\d+)$/); return m?+m[1]+ +m[2]/60:NaN;}); var tot=parts.reduce(function(a,b){return a+b;},0); return['Step 1: Convert each: '+parts.map(function(p){return p.toFixed(2);}).join(' + '),'Step 2: Sum = '+tot.toFixed(2)+' decimal hours','Minutes ÷ 60 is the whole trick: 15 min = 0.25, 45 min = 0.75'];} }`,
`{ id: 'overtime-rate', name: 'Overtime Pay Calculator', desc: 'Pay at time-and-a-half or double time', kw: 'overtime pay calculator time and a half double time hourly', inputs: [{id:'rate',label:'Base Hourly Rate ($)',type:'number',def:20},{id:'hours',label:'Overtime Hours',type:'number',def:10},{id:'mult',label:'Multiplier (1.5 or 2)',type:'number',def:1.5}], calc: function(v){ if(v.rate<=0||v.hours<0) return{result:'Enter valid values',chart:'',extra:''}; var pay=v.rate*v.mult*v.hours; return{result:'Overtime Pay: $'+pay.toFixed(2),chart:Charts.bar([v.rate*v.hours,pay-v.rate*v.hours],['Base value','Premium']),extra:'OT rate: $'+(v.rate*v.mult).toFixed(2)+'/h | US FLSA requires 1.5x past 40 h/week for non-exempt workers — some states add daily rules'};}, steps: function(v){ var pay=v.rate*v.mult*v.hours; return['Formula: pay = rate × multiplier × hours','Step 1: '+v.rate+' × '+v.mult+' = $'+(v.rate*v.mult).toFixed(2)+'/h OT rate','Step 2: × '+v.hours+' h = $'+pay.toFixed(2),'Salaried non-exempt workers earn OT too — the regular rate includes nondiscretionary bonuses'];} }`,
`{ id: 'shift-differential', name: 'Shift Differential Calculator', desc: 'Premium pay for nights or weekends', kw: 'shift differential calculator night shift premium weekend pay', inputs: [{id:'base',label:'Base Rate ($/h)',type:'number',def:25},{id:'diff',label:'Differential (%)',type:'number',def:15},{id:'hours',label:'Differential Hours',type:'number',def:8}], calc: function(v){ if(v.base<=0||v.diff<0||v.hours<0) return{result:'Enter valid values',chart:'',extra:''}; var rate=v.base*(1+v.diff/100); var extra=rate-v.base; return{result:'Premium Rate: $'+rate.toFixed(2)+'/h',chart:Charts.bar([v.base*v.hours,extra*v.hours],['Base pay','Differential']),extra:'Per shift: +$'+(extra*v.hours).toFixed(2)+' | Over a year of 160 night shifts, a 15% differential adds '+(extra*v.hours*160).toFixed(0)+' dollars — real money worth negotiating'};}, steps: function(v){ var rate=v.base*(1+v.diff/100); var extra=rate-v.base; return['Step 1: Premium rate = '+v.base+' × '+(1+v.diff/100)+' = $'+rate.toFixed(2)+'/h','Step 2: Uplift = $'+extra.toFixed(2)+'/h × '+v.hours+' h = $'+(extra*v.hours).toFixed(2)+' per shift','Differentials typically run 10-15% for nights, more for weekends or hazardous duty'];} }`
];
T['business'] = [
`{ id: 'customer-ltv', name: 'Customer Lifetime Value Calculator', desc: 'Revenue per customer from ARPU, margin, and churn', kw: 'customer lifetime value calculator ltv arpu churn margin saas', inputs: [{id:'arpu',label:'Monthly Revenue per Customer ($)',type:'number',def:50},{id:'margin',label:'Gross Margin (%)',type:'number',def:70},{id:'churn',label:'Monthly Churn (%)',type:'number',def:5}], calc: function(v){ if(v.arpu<=0||v.churn<=0) return{result:'Revenue and churn must be positive',chart:'',extra:''}; var ltv=v.arpu*(v.margin/100)/(v.churn/100); var life=1/(v.churn/100); return{result:'LTV: $'+ltv.toFixed(0),chart:Charts.bar([ltv,v.arpu*(1-v.margin/100)/(v.churn/100)],['Gross LTV','Cost portion']),extra:'Average lifetime: '+life.toFixed(1)+' months | Compare with CAC — a healthy SaaS keeps LTV:CAC above 3:1'};}, steps: function(v){ var ltv=v.arpu*(v.margin/100)/(v.churn/100); return['Formula: LTV = ARPU × margin ÷ churn','Step 1: Gross profit per month = '+v.arpu+' × '+(v.margin/100)+' = $'+(v.arpu*v.margin/100).toFixed(2),'Step 2: ÷ churn '+(v.churn/100)+' = $'+ltv.toFixed(0)+' lifetime gross profit','Churn compounds: cutting it from 5% to 4% lifts lifetime from 20 to 25 months'];} }`,
`{ id: 'csat-score', name: 'CSAT Score Calculator', desc: 'Customer satisfaction percent from survey counts', kw: 'csat calculator customer satisfaction score survey percent', inputs: [{id:'good',label:'Satisfied Responses (4-5)',type:'number',def:180},{id:'total',label:'Total Responses',type:'number',def:200}], calc: function(v){ if(v.total<=0||v.good<0||v.good>v.total) return{result:'Enter valid counts',chart:'',extra:''}; var csat=v.good/v.total*100; return{result:'CSAT: '+csat.toFixed(1)+'%',chart:Charts.gauge(csat,100),extra:'Only 4-5 ratings count as satisfied | CSAT measures the transaction, NPS measures the relationship — they move differently'};}, steps: function(v){ var csat=v.good/v.total*100; return['Formula: CSAT = satisfied ÷ total × 100','Step 1: '+v.good+' ÷ '+v.total+' = '+(v.good/v.total).toFixed(3),'Step 2: × 100 = '+csat.toFixed(1)+'%','Segment by channel — chat and phone CSAT usually diverge from email'];} }`,
`{ id: 'conversion-funnel', name: 'Conversion Funnel Calculator', desc: 'Step-to-step and overall conversion rates', kw: 'conversion funnel calculator step rate drop off marketing', inputs: [{id:'s1',label:'Visitors',type:'number',def:1000},{id:'s2',label:'Added to Cart',type:'number',def:300},{id:'s3',label:'Checked Out',type:'number',def:60}], calc: function(v){ if(v.s1<=0) return{result:'Enter a positive visitor count',chart:'',extra:''}; var r1=v.s2/v.s1*100, r2=v.s3/v.s2*100, overall=v.s3/v.s1*100; return{result:'Overall: '+overall.toFixed(1)+'%',chart:Charts.bar([v.s1,v.s2,v.s3],['Visit','Cart','Purchase']),extra:'Step rates: '+(r1).toFixed(0)+'% then '+(r2).toFixed(0)+'% | The biggest drop-off is your leverage — a relative gain there beats the same effort anywhere else'};}, steps: function(v){ var r1=v.s2/v.s1*100, r2=v.s3/v.s2*100; return['Step 1: Visit → Cart: '+v.s2+' ÷ '+v.s1+' = '+r1.toFixed(1)+'%','Step 2: Cart → Purchase: '+v.s3+' ÷ '+v.s2+' = '+r2.toFixed(1)+'%','Step 3: Overall = '+r1.toFixed(1)+'% × '+r2.toFixed(1)+'% ÷ 100 = '+(r1*r2/100).toFixed(1)+'%','Funnel stages multiply — small wins at each step compound'];} }`,
`{ id: 'ab-test-significance', name: 'A/B Test Significance Calculator', desc: 'Z-score for a two-variant conversion test', kw: 'ab test significance calculator z score conversion split test', inputs: [{id:'na',label:'Variant A Visitors',type:'number',def:1000},{id:'ca',label:'Variant A Conversions',type:'number',def:50},{id:'nb',label:'Variant B Visitors',type:'number',def:1000},{id:'cb',label:'Variant B Conversions',type:'number',def:65}], calc: function(v){ if(v.na<=0||v.nb<=0) return{result:'Visitor counts must be positive',chart:'',extra:''}; var p1=v.ca/v.na, p2=v.cb/v.nb; var p=(v.ca+v.cb)/(v.na+v.nb); var se=Math.sqrt(p*(1-p)*(1/v.na+1/v.nb)); if(se===0) return{result:'No variance — check your inputs',chart:'',extra:''}; var z=(p2-p1)/se; var sig=Math.abs(z)>=1.96?'significant at 95%':Math.abs(z)>=1.64?'significant at 90%':'not significant'; return{result:'z = '+z.toFixed(2)+' ('+sig+')',chart:Charts.bar([p1*100,p2*100],['A %','B %']),extra:'A converts '+(p1*100).toFixed(2)+'%, B '+(p2*100).toFixed(2)+'% | Stop tests at the planned sample size — peeking early inflates false positives'};}, steps: function(v){ var p1=v.ca/v.na, p2=v.cb/v.nb; var p=(v.ca+v.cb)/(v.na+v.nb); var se=Math.sqrt(p*(1-p)*(1/v.na+1/v.nb)); var z=(p2-p1)/se; return['Step 1: Rates — A: '+(p1*100).toFixed(2)+'%, B: '+(p2*100).toFixed(2)+'%','Step 2: Pooled p = '+(v.ca+v.cb)+' ÷ '+(v.na+v.nb)+' = '+p.toFixed(4),'Step 3: SE = √(p(1−p)(1/nA+1/nB)) = '+se.toFixed(5),'Step 4: z = (pB − pA) ÷ SE = '+z.toFixed(3)+' — |z| ≥ 1.96 means 95% confidence'];} }`,
`{ id: 'project-bid', name: 'Project Bid Calculator', desc: 'Bid price from cost, contingency, and margin', kw: 'project bid calculator price margin contingency contractor estimate', inputs: [{id:'cost',label:'Direct Cost ($)',type:'number',def:50000},{id:'cont',label:'Contingency (%)',type:'number',def:10},{id:'margin',label:'Profit Margin (%)',type:'number',def:20}], calc: function(v){ if(v.cost<=0) return{result:'Cost must be positive',chart:'',extra:''}; var withCont=v.cost*(1+v.cont/100); var bid=withCont/(1-v.margin/100); return{result:'Bid: $'+bid.toFixed(0),chart:Charts.bar([v.cost,withCont-v.cost,bid-withCont],['Cost','Contingency','Margin']),extra:'Margin on price, not cost: dividing by (1 − margin) is correct — multiplying cost by 1.2 underprices every job'};}, steps: function(v){ var withCont=v.cost*(1+v.cont/100); var bid=withCont/(1-v.margin/100); return['Step 1: Cost + contingency = $'+v.cost.toLocaleString()+' × '+(1+v.cont/100)+' = $'+withCont.toLocaleString(),'Step 2: Bid = $'+withCont.toLocaleString()+' ÷ (1 − '+(v.margin/100)+') = $'+bid.toLocaleString(),'The division matters: a 20% margin on price equals a 25% markup on cost'];} }`,
`{ id: 'retainer-value', name: 'Retainer Value Calculator', desc: 'Contract value with a term discount applied', kw: 'retainer value calculator monthly contract discount annual', inputs: [{id:'monthly',label:'Monthly Fee ($)',type:'number',def:5000},{id:'months',label:'Term (months)',type:'number',def:12},{id:'disc',label:'Prepay Discount (%)',type:'number',def:10}], calc: function(v){ if(v.monthly<=0||v.months<=0) return{result:'Enter positive values',chart:'',extra:''}; var gross=v.monthly*v.months; var net=gross*(1-v.disc/100); return{result:'Contract Value: $'+net.toFixed(0),chart:Charts.bar([gross,gross-net],['List','Discount']),extra:'Effective monthly: $'+(net/v.months).toFixed(0)+' | The discount buys cash flow and commitment — cap it below your financing cost plus churn risk'};}, steps: function(v){ var gross=v.monthly*v.months; var net=gross*(1-v.disc/100); return['Step 1: List value = $'+v.monthly+' × '+v.months+' = $'+gross.toLocaleString(),'Step 2: Apply '+v.disc+'% prepay discount → $'+net.toLocaleString(),'Discounts should be traded, not given: tie them to longer terms or upfront payment'];} }`
];
T['utilities'] = [
`{ id: 'qr-content-size', name: 'QR Version Finder', desc: 'Smallest QR version that fits your byte payload', kw: 'qr code version calculator byte capacity payload ecc', inputs: [{id:'bytes',label:'Payload Size (bytes)',type:'number',def:500},{id:'ecc',label:'ECC (0=L, 1=M, 2=Q, 3=H)',type:'number',def:1}], calc: function(v){ if(v.bytes<=0) return{result:'Payload must be positive',chart:'',extra:''}; var capM=[17,32,53,78,106,134,154,192,230,271,321,367,425,458,520,586,644,718,792,858,929,1003,1091,1171,1273,1367,1465,1528,1628,1732,1840,1952,2068,2188,2303,2431,2563,2699,2809,2953]; var caps=[capM, capM.map(function(c){return Math.round(c*1.35);}), capM.map(function(c){return Math.round(c*0.77);}), capM.map(function(c){return Math.round(c*0.58);})]; var capsArr=caps[Math.min(3,Math.max(0,v.ecc))]; var ver=capsArr.findIndex(function(c){return c>=v.bytes;}); if(ver<0) return{result:'Too large even for version 40 — split the payload',chart:'',extra:''}; return{result:'Version '+(ver+1)+' ('+capsArr[ver]+' bytes at ECC '+(v.ecc===0?'L':v.ecc===1?'M':v.ecc===2?'Q':'H')+')',chart:Charts.gauge(ver+1,40),extra:'More error correction means less capacity — URL shorteners exist because 300 bytes of link is a big QR | Version 1-4 scans fastest from a distance'};}, steps: function(v){ return['Step 1: QR versions run 1 (21×21 modules) to 40 (177×177)','Step 2: Capacity depends on payload mode and ECC level — byte mode with ECC M fits 14 bytes at v1 and 1853 at v40','Step 3: Entered payload '+v.bytes+' bytes picks the smallest version whose table capacity covers it','Lower ECC = more capacity but a harder-to-scan code if damaged'];} }`,
`{ id: 'timestamp-convert', name: 'Unix Timestamp Converter', desc: 'Epoch seconds to readable UTC date', kw: 'unix timestamp converter epoch utc date time', inputs: [{id:'ts',label:'Unix Timestamp (seconds)',type:'number',def:1700000000}], calc: function(v){ if(!isFinite(v.ts)) return{result:'Enter a valid number',chart:'',extra:''}; var d=new Date(v.ts*1000); if(isNaN(d.getTime())) return{result:'Timestamp out of range',chart:'',extra:''}; var pad=function(n){return (n<10?'0':'')+n;}; var s=d.getUTCFullYear()+'-'+pad(d.getUTCMonth()+1)+'-'+pad(d.getUTCDate())+' '+pad(d.getUTCHours())+':'+pad(d.getUTCMinutes())+':'+pad(d.getUTCSeconds())+' UTC'; return{result:s,chart:Charts.bar([v.ts],['epoch']),extra:'Day of week: '+['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][d.getUTCDay()]+' | Unix time counts seconds since 1970-01-01 UTC, ignoring leap seconds'};}, steps: function(v){ var d=new Date(v.ts*1000); return['Step 1: Unix time = seconds since 1970-01-01 00:00:00 UTC','Step 2: '+v.ts+' × 1000 ms → '+(isNaN(d.getTime())?'out of range':d.toISOString()),'Step 3: Displayed in UTC — convert to your zone by adding your UTC offset','Milliseconds timestamps divide by 1000 first'];} }`
];

const QA_ROWS = [
  ['engineering', 'hydraulic-press', { f1: 200, a1: 1, a2: 10 }, 2000, 1, 'F1*area ratio'],
  ['engineering', 'radiation-shielding', { i0: 100, hvl: 2, x: 6 }, 12.5, 0.2, '100*0.5^3'],
  ['engineering', 'steam-consumption', { flow: 100, hfg: 2257 }, 62.69, 0.3, '100*2257/3600 kW'],
  ['engineering', 'noise-level', { l1: 85, l2: 88 }, 89.76, 0.2, '10log10(10^8.5+10^8.8)'],
  ['construction', 'rafter-length', { run: 12, rise: 5 }, 13, 0.05, 'sqrt(144+25)'],
  ['construction', 'shingle-squares', { area: 2400, waste: 10 }, 26.4, 0.2, '24*1.1 squares'],
  ['construction', 'drywall-sheets', { area: 800, sheet: 32, waste: 10 }, 28, 0.5, 'ceil(25*1.1)'],
  ['construction', 'tile-boxes', { area: 200, box: 20, waste: 10 }, 11, 0.5, 'ceil(10*1.1)'],
  ['everyday', 'sunrise-sunset-length', { lat: 40, decl: 23.44 }, 14.85, 0.15, 'summer solstice 40N'],
  ['everyday', 'pomodoro-planner', { sessions: 8, work: 25, brk: 5 }, 240, 1, '8*30 min'],
  ['everyday', 'gift-wrap', { l: 40, w: 30, h: 15 }, 6300, 10, '2(w+h)(l+2h) sq cm'],
  ['everyday', 'moving-truck', { rooms: 3, cf: 150 }, 450, 1, '3*150 cu ft'],
  ['everyday', 'jet-lag', { zones: 7, dir: 1 }, 7, 0.5, '7 eastward days'],
  ['everyday', 'heat-pump-savings', { load: 12000, rate: 0.15, cop: 3 }, 1200, 5, '12000*0.15*(1-1/3)'],
  ['lifestyle', 'french-press-ratio', { water: 500, ratio: 15 }, 33.33, 0.2, '500/15 g'],
  ['lifestyle', 'cocktail-dilution', { vol: 100, abv: 40, dil: 25 }, 32, 0.3, '40/1.25'],
  ['lifestyle', 'wine-servings', { bottles: 3, pour: 5 }, 15, 0.5, '3*25.4/5'],
  ['lifestyle', 'baking-scale', { base: 500, new: 750, water: 325 }, 487.5, 1, '325*1.5'],
  ['lifestyle', 'sourdough-hydration', { water: 350, flour: 500 }, 70, 0.5, '350/500'],
  ['lifestyle', 'lawn-fertilizer', { area: 5000, rate: 1, npct: 29 }, 17.24, 0.3, '5/0.29 lb'],
  ['lifestyle', 'candle-wax', { jars: 12, oz: 8 }, 82.56, 0.5, '12*8*0.86'],
  ['lifestyle', 'knit-gauge', { width: 20, spi: 5 }, 100, 0.5, '20*5 stitches'],
  ['lifestyle', 'quilt-fabric', { w: 60, h: 80, fw: 42 }, 4.89, 0.1, '2*88/36 yards'],
  ['parenting-family', 'baby-milestones', { months: 9 }, 9, 0.5, 'age echo'],
  ['parenting-family', 'child-support-split', { mine: 5000, other: 3000, base: 1200 }, 750, 1, '1200*5/8'],
  ['parenting-family', 'family-tree-generation', { gen: 5 }, 32, 0.5, '2^5'],
  ['education', 'assignment-split', { score: 90, worth: 40 }, 36, 0.3, '90*0.4'],
  ['education', 'citation-count', { cites: '10,8,5,3,1' }, 3, 0.5, 'h-index of 10,8,5,3,1'],
  ['education', 'essay-length', { words: 750, wpm: 150 }, 5, 0.1, '750/150 min'],
  ['career-freelance', 'vacation-days', { rate: 15, months: 8 }, 10, 0.2, '15*8/12'],
  ['career-freelance', 'timesheet-hours', { times: '8:30,7:45,8:00' }, 24.25, 0.05, '8.5+7.75+8'],
  ['career-freelance', 'overtime-rate', { rate: 20, hours: 10, mult: 1.5 }, 300, 0.5, '20*1.5*10'],
  ['career-freelance', 'shift-differential', { base: 25, diff: 15, hours: 8 }, 28.75, 0.2, '25*1.15'],
  ['business', 'customer-ltv', { arpu: 50, margin: 70, churn: 5 }, 700, 2, '50*0.7/0.05'],
  ['business', 'csat-score', { good: 180, total: 200 }, 90, 0.5, '180/200'],
  ['business', 'conversion-funnel', { s1: 1000, s2: 300, s3: 60 }, 6, 0.2, '60/1000 %'],
  ['business', 'ab-test-significance', { na: 1000, ca: 50, nb: 1000, cb: 65 }, 2.04, 0.05, 'two-proportion z'],
  ['business', 'project-bid', { cost: 50000, cont: 10, margin: 20 }, 66000, 10, '50000*1.1/0.8'],
  ['business', 'retainer-value', { monthly: 5000, months: 12, disc: 10 }, 54000, 10, '60000*0.9'],
  ['utilities', 'qr-content-size', { bytes: 500, ecc: 1 }, 20, 0.5, 'version 20 covers 500 bytes'],
  ['utilities', 'timestamp-convert', { ts: 1700000000 }, 14, 0.5, '2023-11-14 UTC day']
];

const check = process.argv.includes('--check');
for (const file of Object.keys(T)) {
  const fp = path.join(ROOT, 'js', 'data', file + '.js');
  let src = fs.readFileSync(fp, 'utf8');
  const ids = T[file].map(c => c.match(/id: '([^']+)'/)[1]);
  const present = ids.filter(id => src.includes("id: '" + id + "'"));
  if (present.length) { console.error('[ABORT] ' + file + ' already contains: ' + present.join(', ')); process.exit(1); }
  const anchor = src.lastIndexOf('\r\n];');
  if (anchor < 0) { console.error('[ABORT] no CRLF ]; tail in ' + file); process.exit(1); }
  const before = src.slice(0, anchor);
  const sep = /,\s*$/.test(before) ? '\r\n\r\n' : ',\r\n\r\n';
  const block = T[file].map(c => '  ' + c).join(',\r\n\r\n');
  const out = before + sep + block + src.slice(anchor);
  if (!check) {
    try { new Function(out); } catch (e) { console.error('[ABORT] ' + file + ' would not parse: ' + e.message); process.exit(1); }
    fs.writeFileSync(fp, out);
  }
  console.log('[ok] ' + file + ': +' + ids.length + ' tools');
}
const tfp = path.join(ROOT, 'tests', 'unit', 'formula-qa-full.test.js');
let tsrc = fs.readFileSync(tfp, 'utf8');
const firstRow = "['engineering', 'hydraulic-press'";
if (tsrc.includes(firstRow)) { console.log('[skip] QA rows already present'); }
else {
  const start = tsrc.indexOf('const CASES = [');
  const close = tsrc.indexOf('\n];', start);
  if (start < 0 || close < 0) { console.error('[ABORT] CASES array not found'); process.exit(1); }
  tsrc = tsrc.slice(0, close) + '\n' + QA_ROWS.map(r => '  ' + JSON.stringify(r).replace(/"([a-zA-Z0-9_]+)":/g, '$1: ').replace(/,'/g, ", '").replace(/',/g, "', ").replace(/\{/g, '{ ').replace(/\}/g, ' }') + ',').join('\n') + tsrc.slice(close);
  if (!check) fs.writeFileSync(tfp, tsrc);
  console.log('[ok] +' + QA_ROWS.length + ' QA rows');
}
console.log((check ? '[DRY RUN] ' : '') + 'done: 41 tools across 9 files');
