// Batch A3-F2a: 26 tools (math 5, science 5, health 8, tech-digital 8). Usage: node scripts/a3-f2a.cjs [--check]
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..');

const T = {};
T['math'] = [
`{ id: 'completing-square', name: 'Completing the Square Calculator', desc: 'Rewrite a quadratic in vertex form and solve it', kw: 'completing the square calculator vertex form quadratic solver', inputs: [{id:'a',label:'Coefficient of x-squared',type:'number',def:1},{id:'b',label:'Coefficient of x',type:'number',def:6},{id:'c',label:'Constant term',type:'number',def:5}], calc: function(v){ if(v.a===0) return{result:'Coefficient a must not be zero',chart:'',extra:''}; var h=-v.b/(2*v.a), k=v.c-v.b*v.b/(4*v.a); var disc=v.b*v.b-4*v.a*v.c; if(disc<0) return{result:'Vertex form: '+v.a+'(x'+(h>=0?' + ':' − ')+Math.abs(h).toFixed(2)+')^2 + '+k.toFixed(2)+' — no real roots (discriminant '+disc.toFixed(2)+' < 0)',chart:Charts.gauge(Math.abs(disc),50),extra:'The parabola never crosses the x-axis'}; var r1=(-v.b+Math.sqrt(disc))/(2*v.a), r2=(-v.b-Math.sqrt(disc))/(2*v.a); return{result:'Roots: x = '+r1.toFixed(2).replace(/\\.00$/,'')+' or x = '+r2.toFixed(2).replace(/\\.00$/,''),chart:Charts.bar([r1,r2],['Root 1','Root 2']),extra:'Vertex form: '+v.a+'(x − '+h.toFixed(2)+')^2 + '+k.toFixed(2)+' | Vertex at ('+h.toFixed(2)+', '+k.toFixed(2)+')'};}, steps: function(v){ var h=-v.b/(2*v.a); var k=v.c-v.b*v.b/(4*v.a); var disc=v.b*v.b-4*v.a*v.c; var out=['Step 1: Half of b/a, squared: ('+(-v.b/(2*v.a)).toFixed(2)+')^2 = '+(v.b*v.b/(4*v.a*v.a)).toFixed(2),'Step 2: Vertex form: '+v.a+'(x − '+h.toFixed(2)+')^2 + '+k.toFixed(2)]; if(disc>=0){var r1=(-v.b+Math.sqrt(disc))/(2*v.a), r2=(-v.b-Math.sqrt(disc))/(2*v.a); out.push('Step 3: Set equal to zero and solve: x = '+r1.toFixed(2)+' or x = '+r2.toFixed(2));} else out.push('Step 3: Discriminant is negative, so there are no real roots'); return out;} }`,
`{ id: 'partial-fractions', name: 'Partial Fraction Calculator', desc: 'Split 1/(px+q)(rx+s) into A and B terms', kw: 'partial fraction decomposition calculator algebra rational expression', inputs: [{id:'p',label:'p (first factor px+q)',type:'number',def:1},{id:'q',label:'q',type:'number',def:-1},{id:'r',label:'r (second factor rx+s)',type:'number',def:1},{id:'s',label:'s',type:'number',def:1}], calc: function(v){ var det=v.p*v.s-v.q*v.r; if(det===0) return{result:'Factors are proportional — decomposition not unique',chart:'',extra:''}; var A=v.s/det, B=-v.q/det; return{result:'A = '+A.toFixed(4).replace(/\\.?0+$/,'')+', B = '+B.toFixed(4).replace(/\\.?0+$/,''),chart:Charts.bar([A,B],['A','B']),extra:'Result: '+A.toFixed(4).replace(/\\.?0+$/,'')+'/('+v.p+'x+'+v.q+') + '+B.toFixed(4).replace(/\\.?0+$/,'')+'/('+v.r+'x+'+v.s+') | Check: combine back over the common denominator'};}, steps: function(v){ var det=v.p*v.s-v.q*v.r; var A=v.s/det, B=-v.q/det; return['Step 1: Write A/(px+q) + B/(rx+s) = 1/((px+q)(rx+s))','Step 2: Multiply both sides by the denominator: A(rx+s) + B(px+q) = 1','Step 3: Match coefficients — solve the 2x2 system','Step 4: A = s/(ps−qr) = '+A.toFixed(4)+', B = −q/(ps−qr) = '+B.toFixed(4)];} }`,
`{ id: 'direct-variation', name: 'Direct Variation Calculator', desc: 'Solve y = kx for y, k, or x', kw: 'direct variation calculator y kx constant of proportionality', inputs: [{id:'mode',label:'Solve for (1=y, 2=k, 3=x)',type:'number',def:1},{id:'a',label:'Known value 1',type:'number',def:3},{id:'b',label:'Known value 2',type:'number',def:4}], calc: function(v){ var out; if(v.mode===1) out={result:'y = '+(v.a*v.b).toFixed(2).replace(/\\.00$/,''),chart:Charts.bar([v.a*v.b],['y']),extra:'With k = '+v.a+' and x = '+v.b+', y scales straight-line through the origin'}; else if(v.mode===2) out={result:'k = '+(v.a/v.b).toFixed(4).replace(/\\.?0+$/,''),chart:Charts.bar([v.a/v.b],['k']),extra:'From y = '+v.a+' at x = '+v.b+' — the ratio y/x stays constant'}; else out={result:'x = '+(v.a/v.b).toFixed(4).replace(/\\.?0+$/,''),chart:Charts.bar([v.a/v.b],['x']),extra:'From y = '+v.a+' with k = '+v.b}; return out;}, steps: function(v){ var names={1:'y = k × x',2:'k = y ÷ x',3:'x = y ÷ k'}; var res=v.mode===1?v.a*v.b:v.a/v.b; return['Formula: '+names[v.mode],'Step 1: Substitute the two known values','Step 2: '+res.toFixed(4).replace(/\\.00$/,''),'Direct variation means doubling one quantity doubles the other — the graph is a line through the origin'];} }`,
`{ id: 'inverse-variation', name: 'Inverse Variation Calculator', desc: 'Solve y = k/x for y, k, or x', kw: 'inverse variation calculator y equals k over x constant', inputs: [{id:'mode',label:'Solve for (1=y, 2=k, 3=x)',type:'number',def:1},{id:'a',label:'Known value 1',type:'number',def:12},{id:'b',label:'Known value 2',type:'number',def:4}], calc: function(v){ var out; if(v.mode===1) out={result:'y = '+(v.a/v.b).toFixed(4).replace(/\\.?0+$/,''),chart:Charts.bar([v.a/v.b],['y']),extra:'With k = '+v.a+' and x = '+v.b}; else if(v.mode===2) out={result:'k = '+(v.a*v.b).toFixed(2).replace(/\\.00$/,''),chart:Charts.bar([v.a*v.b],['k']),extra:'From y = '+v.a+' at x = '+v.b+' — the product y·x stays constant'}; else out={result:'x = '+(v.a/v.b).toFixed(4).replace(/\\.?0+$/,''),chart:Charts.bar([v.a/v.b],['x']),extra:'From y = '+v.a+' with k = '+v.b}; return out;}, steps: function(v){ var names={1:'y = k ÷ x',2:'k = y × x',3:'x = k ÷ y'}; var res=v.mode===2?v.a*v.b:v.a/v.b; return['Formula: '+names[v.mode],'Step 1: Substitute the two known values','Step 2: '+res.toFixed(4).replace(/\\.?0+$/,''),'Inverse variation: halving one quantity doubles the other — pressure vs volume is the classic example'];} }`,
`{ id: 'spherical-cap', name: 'Spherical Cap Volume Calculator', desc: 'Volume and surface area of a spherical cap', kw: 'spherical cap calculator volume dome segment surface area', inputs: [{id:'R',label:'Sphere Radius',type:'number',def:5},{id:'h',label:'Cap Height',type:'number',def:2}], calc: function(v){ if(v.R<=0||v.h<=0||v.h>2*v.R) return{result:'Cap height must be between 0 and the full diameter',chart:'',extra:''}; var vol=Math.PI*v.h*v.h*(3*v.R-v.h)/3; var area=2*Math.PI*v.R*v.h; return{result:'Cap Volume: '+vol.toFixed(2),chart:Charts.bar([vol,(4/3)*Math.PI*Math.pow(v.R,3)],['Cap volume','Full sphere']),extra:'Curved surface area: '+area.toFixed(2)+' | The cap is '+((vol/((4/3)*Math.PI*Math.pow(v.R,3)))*100).toFixed(1)+'% of the full sphere volume'};}, steps: function(v){ var vol=Math.PI*v.h*v.h*(3*v.R-v.h)/3; return['Formula: V = πh^2(3R − h)/3','Step 1: h^2 = '+Math.pow(v.h,2),'Step 2: 3R − h = '+(3*v.R-v.h),'Step 3: V = π × '+Math.pow(v.h,2)+' × '+(3*v.R-v.h)+' ÷ 3 = '+vol.toFixed(2),'Setting h = R gives a hemisphere; h = 2R gives the whole sphere'];} }`
];
T['science'] = [
`{ id: 'angular-momentum', name: 'Angular Momentum Calculator', desc: 'Rotational momentum L = m·v·r for a point mass', kw: 'angular momentum calculator mvr rotational physics', inputs: [{id:'m',label:'Mass (kg)',type:'number',def:2},{id:'v',label:'Tangential Velocity (m/s)',type:'number',def:3},{id:'r',label:'Radius (m)',type:'number',def:4}], calc: function(v){ if(v.m<0||v.r<0) return{result:'Mass and radius must be non-negative',chart:'',extra:''}; var L=v.m*v.v*v.r; return{result:'Angular Momentum: '+L.toFixed(2)+' kg·m²/s',chart:Charts.gauge(L,100),extra:'Rotational inertia resists changes to L — in a closed system angular momentum is conserved, so pulling mass inward (smaller r) spins the object faster'};}, steps: function(v){ var L=v.m*v.v*v.r; return['Formula: L = m × v × r','Step 1: '+v.m+' × '+v.v+' × '+v.r,'Step 2: L = '+L.toFixed(2)+' kg·m²/s','A figure skater pulling in the arms keeps L constant by increasing v as r falls'];} }`,
`{ id: 'bullet-drop', name: 'Bullet Drop Calculator', desc: 'Gravity drop over a horizontal shot distance', kw: 'bullet drop calculator trajectory gravity shooting', inputs: [{id:'d',label:'Horizontal Distance (m)',type:'number',def:100},{id:'v',label:'Muzzle Velocity (m/s)',type:'number',def:400}], calc: function(v){ if(v.v<=0||v.d<0) return{result:'Velocity must be positive',chart:'',extra:''}; var t=v.d/v.v; var drop=0.5*9.81*t*t; return{result:'Drop: '+(drop*100).toFixed(1)+' cm over '+v.d+' m',chart:Charts.bar([drop*100],['drop cm']),extra:'Time of flight: '+t.toFixed(3)+' s — drop grows with the square of time, so doubling distance roughly quadruples it'};}, steps: function(v){ var t=v.d/v.v; var drop=0.5*9.81*t*t; return['Step 1: Time of flight t = distance ÷ velocity = '+v.d+' ÷ '+v.v+' = '+t.toFixed(4)+' s','Step 2: Drop = ½gt² = 0.5 × 9.81 × '+Math.pow(t,2).toFixed(5)+' = '+(drop*100).toFixed(1)+' cm','This is pure gravity drop from the bore line — real trajectories also involve drag and sight height'];} }`,
`{ id: 'redshift', name: 'Redshift Calculator', desc: 'Recession velocity from spectral redshift z', kw: 'redshift calculator doppler spectral shift recession velocity astronomy', inputs: [{id:'rest',label:'Rest Wavelength (nm)',type:'number',def:500},{id:'obs',label:'Observed Wavelength (nm)',type:'number',def:505}], calc: function(v){ if(v.rest<=0) return{result:'Rest wavelength must be positive',chart:'',extra:''}; var z=(v.obs-v.rest)/v.rest; var c=299792.458; var vel=c*z; return{result:'Redshift z = '+z.toFixed(4),chart:Charts.bar([z,0.1],['z','0.1 ref']),extra:'Recession velocity ≈ '+vel.toFixed(0)+' km/s (low-z approximation: v = cz) | Observed is '+(v.obs>v.rest?'redshifted':'blueshifted')+' by '+Math.abs(v.obs-v.rest).toFixed(2)+' nm'};}, steps: function(v){ var z=(v.obs-v.rest)/v.rest; return['Formula: z = (λ_observed − λ_rest) ÷ λ_rest','Step 1: ('+v.obs+' − '+v.rest+') ÷ '+v.rest+' = '+z.toFixed(4),'Step 2: v ≈ cz = 299792.458 × '+z.toFixed(4)+' ≈ '+(299792.458*z).toFixed(0)+' km/s','At z above about 0.1 the relativistic and cosmological versions must be used instead'];} }`,
`{ id: 'buffer-ph', name: 'Buffer pH Calculator', desc: 'Henderson-Hasselbalch buffer pH from pKa and ratio', kw: 'buffer ph calculator henderson hasselbalch pKa conjugate base acid', inputs: [{id:'pka',label:'pKa of Acid',type:'number',def:4.76},{id:'ratio',label:'[Base] / [Acid] Ratio',type:'number',def:1}], calc: function(v){ if(v.ratio<=0) return{result:'Ratio must be positive',chart:'',extra:''}; var pH=v.pka+Math.log10(v.ratio); return{result:'Buffer pH: '+pH.toFixed(2),chart:Charts.gauge(pH,14),extra:'A ratio of 1 gives pH = pKa | Buffer capacity is highest within ±1 pH unit of the pKa'};}, steps: function(v){ var pH=v.pka+Math.log10(v.ratio); return['Formula: pH = pKa + log10([A−]/[HA])','Step 1: log10('+v.ratio+') = '+Math.log10(v.ratio).toFixed(4),'Step 2: pH = '+v.pka+' + '+Math.log10(v.ratio).toFixed(4)+' = '+pH.toFixed(2),'Ten-fold more base than acid pushes pH one unit above pKa'];} }`,
`{ id: 'machine-efficiency', name: 'Machine Efficiency Calculator', desc: 'Percent of input energy that becomes useful output', kw: 'machine efficiency calculator mechanical output input energy', inputs: [{id:'out',label:'Useful Output (W or J)',type:'number',def:75},{id:'inp',label:'Total Input (W or J)',type:'number',def:100}], calc: function(v){ if(v.inp<=0) return{result:'Input must be positive',chart:'',extra:''}; var e=v.out/v.inp*100; return{result:'Efficiency: '+e.toFixed(1)+'%',chart:Charts.bar([v.out,v.inp-v.out],['Useful','Lost']),extra:'Energy lost: '+(100-e).toFixed(1)+'% — usually heat and friction; no real machine reaches 100%'};}, steps: function(v){ var e=v.out/v.inp*100; return['Formula: Efficiency = output ÷ input × 100','Step 1: '+v.out+' ÷ '+v.inp+' = '+(v.out/v.inp).toFixed(4),'Step 2: × 100 = '+e.toFixed(1)+'%','Compare machines of the same type — a 90% efficient motor versus an 80% one wastes half as much per unit of work'];} }`
];
T['health'] = [
`{ id: 'bmr-mifflin', name: 'Mifflin-St Jeor BMR Calculator', desc: 'Basal metabolic rate by the current standard equation', kw: 'mifflin st jeor bmr calculator basal metabolic rate', inputs: [{id:'w',label:'Weight (kg)',type:'number',def:70},{id:'h',label:'Height (cm)',type:'number',def:170},{id:'age',label:'Age (years)',type:'number',def:30},{id:'sex',label:'Sex (1=male, 0=female)',type:'number',def:1}], calc: function(v){ if(v.w<=0||v.h<=0||v.age<=0) return{result:'Enter positive weight, height, and age',chart:'',extra:''}; var bmr=10*v.w+6.25*v.h-5*v.age+(v.sex===1?5:-161); return{result:'BMR: '+bmr.toFixed(0)+' kcal/day',chart:Charts.bar([bmr,bmr*1.55],['BMR','TDEE (moderate)']),extra:'Multiply by activity 1.2–1.9 for daily needs — at moderate activity about '+(bmr*1.55).toFixed(0)+' kcal/day'};}, steps: function(v){ var bmr=10*v.w+6.25*v.h-5*v.age+(v.sex===1?5:-161); return['Formula (male): 10w + 6.25h − 5·age + 5 | (female): − 161 instead of + 5','Step 1: 10 × '+v.w+' = '+(10*v.w),'Step 2: 6.25 × '+v.h+' = '+(6.25*v.h),'Step 3: Sum with age and sex terms = '+bmr.toFixed(0)+' kcal/day','Mifflin-St Jeor is the equation the Academy of Nutrition and Dietetics considers most accurate for healthy adults'];} }`,
`{ id: 'tdee-macro', name: 'TDEE and Macro Calculator', desc: 'Daily calorie burn plus protein, carb, and fat targets', kw: 'tdee calculator macro split protein carb fat daily calories', inputs: [{id:'w',label:'Weight (kg)',type:'number',def:70},{id:'h',label:'Height (cm)',type:'number',def:170},{id:'age',label:'Age',type:'number',def:30},{id:'sex',label:'Sex (1=male, 0=female)',type:'number',def:1},{id:'act',label:'Activity Multiplier (1.2–1.9)',type:'number',def:1.55},{id:'pct',label:'Protein % of Calories',type:'number',def:30}], calc: function(v){ if(v.w<=0||v.act<1) return{result:'Enter valid body data and an activity multiplier of at least 1.2',chart:'',extra:''}; var bmr=10*v.w+6.25*v.h-5*v.age+(v.sex===1?5:-161); var tdee=bmr*v.act; var pk=v.tdee||v.pct; var p=tdee*(v.pct/100)/4; var f=0.3; var fat=tdee*f/9; var carb=tdee*(1-v.pct/100-f)/4; return{result:'TDEE: '+tdee.toFixed(0)+' kcal',chart:Charts.bar([p*4,carb*4,fat*9],['Protein','Carb','Fat']),extra:'Protein '+p.toFixed(0)+' g | Carbs '+carb.toFixed(0)+' g | Fat '+fat.toFixed(0)+' g — fat held at 30% for hormone health; adjust protein first for goals'};}, steps: function(v){ var bmr=10*v.w+6.25*v.h-5*v.age+(v.sex===1?5:-161); var tdee=bmr*v.act; return['Step 1: BMR (Mifflin-St Jeor) = '+bmr.toFixed(0),'Step 2: TDEE = BMR × activity = '+bmr.toFixed(0)+' × '+v.act+' = '+tdee.toFixed(0)+' kcal','Step 3: Protein '+v.pct+'% → '+(tdee*v.pct/100/4).toFixed(0)+' g, fat 30% → '+(tdee*0.3/9).toFixed(0)+' g, carbs fill the rest','Cut 300–500 kcal for loss; add 200–300 for lean gain'];} }`,
`{ id: 'gfr-estimate', name: 'eGFR Calculator (CKD-EPI 2021)', desc: 'Kidney filtration rate from creatinine, age, and sex', kw: 'egfr calculator ckd-epi 2021 creatinine kidney function gfr', inputs: [{id:'scr',label:'Serum Creatinine (mg/dL)',type:'number',def:1.0},{id:'age',label:'Age (years)',type:'number',def:40},{id:'sex',label:'Sex (1=female, 0=male)',type:'number',def:0}], calc: function(v){ if(v.scr<=0||v.age<=0) return{result:'Enter valid creatinine and age',chart:'',extra:''}; var fem=v.sex===1; var a=fem?-0.323:-0.302; var k=fem?0.7:0.9; var kap=fem?1.012:1; var e=142*Math.pow(v.scr/k,a)*Math.pow(0.9938,v.age)*kap; var stage=e>=90?'G1 normal':e>=60?'G2 mild':e>=45?'G3a mild-moderate':e>=30?'G3b moderate-severe':e>=15?'G4 severe':'G5 kidney failure'; return{result:'eGFR: '+e.toFixed(1)+' mL/min/1.73m²',chart:Charts.gauge(e,120),extra:'CKD stage '+stage+' | Below 60 for 3+ months indicates chronic kidney disease — confirm with repeat testing'};}, steps: function(v){ var fem=v.sex===1; var a=fem?-0.323:-0.302; var k=fem?0.7:0.9; var e=142*Math.pow(v.scr/k,a)*Math.pow(0.9938,v.age); return['Formula (CKD-EPI 2021, race-free): 142 × (Scr/k)^a × 0.9938^age × 1.012 if female','Step 1: Scr/k = '+v.scr+' ÷ '+k+' = '+(v.scr/k).toFixed(4),'Step 2: Raise to power a = '+a+' → '+Math.pow(v.scr/k,a).toFixed(4),'Step 3: Age factor 0.9938^'+v.age+' = '+Math.pow(0.9938,v.age).toFixed(4),'Step 4: eGFR = 142 × '+Math.pow(v.scr/k,a).toFixed(4)+' × '+Math.pow(0.9938,v.age).toFixed(4)+' = '+e.toFixed(1)];} }`,
`{ id: 'chw', name: 'Adjusted Body Weight Calculator', desc: 'Amputee-adjusted weight using percent of limb loss', kw: 'adjusted body weight calculator amputee limb loss percentage', inputs: [{id:'w',label:'Measured Weight (kg)',type:'number',def:80},{id:'amp',label:'Amputation (% of body weight)',type:'number',def:6}], calc: function(v){ if(v.w<=0||v.amp<0||v.amp>=100) return{result:'Enter a positive weight and an amputation percent below 100',chart:'',extra:''}; var adj=v.w/(1-v.amp/100); return{result:'Adjusted Weight: '+adj.toFixed(1)+' kg',chart:Charts.bar([v.w,adj-v.w],['Measured','Missing']),extra:'Estimated full-body weight — common values: hand 0.7%, forearm 2.3%, whole arm 5%, foot 1.5%, lower leg 5.9%, whole leg 16%'};}, steps: function(v){ var adj=v.w/(1-v.amp/100); return['Formula: Adjusted weight = measured ÷ (1 − amputation %)','Step 1: 1 − '+(v.amp/100)+' = '+(1-v.amp/100),'Step 2: '+v.w+' ÷ '+(1-v.amp/100)+' = '+adj.toFixed(1)+' kg','Use the adjusted weight for BMI and calorie calculations — the missing limb is real mass the scale never sees'];} }`,
`{ id: 'gcs', name: 'Glasgow Coma Scale Calculator', desc: 'Eye, verbal, and motor response scoring', kw: 'glasgow coma scale calculator gcs eye verbal motor trauma score', inputs: [{id:'e',label:'Eye response (1-4)',type:'number',def:4},{id:'v',label:'Verbal response (1-5)',type:'number',def:5},{id:'m',label:'Motor response (1-6)',type:'number',def:6}], calc: function(v){ if(v.e<1||v.e>4||v.v<1||v.v>5||v.m<1||v.m>6) return{result:'Scores must be E 1-4, V 1-5, M 1-6',chart:'',extra:''}; var g=v.e+v.v+v.m; var band=g>=13?'mild injury':g>=9?'moderate injury':'severe injury'; return{result:'GCS: '+g+' ('+band+')',chart:Charts.gauge(g,15),extra:'Components: E'+v.e+' + V'+v.v+' + M'+v.m+' | Intubated patients score V1 — record it as GCS E_M_V (e.g. 4_1_6) so components are not lost'};}, steps: function(v){ var g=v.e+v.v+v.m; return['Step 1: Eye (4 opens spontaneously, 3 to voice, 2 to pain, 1 none) = '+v.e,'Step 2: Verbal (5 oriented ... 1 none) = '+v.v,'Step 3: Motor (6 obeys commands ... 1 none) = '+v.m,'Total: '+v.e+' + '+v.v+' + '+v.m+' = '+g+' — report the three components, not just the sum'];} }`,
`{ id: 'apgar', name: 'APGAR Score Calculator', desc: 'Newborn condition at 1 and 5 minutes after birth', kw: 'apgar score calculator newborn appearance pulse grimace activity respiration', inputs: [{id:'a',label:'Appearance/color (0-2)',type:'number',def:2},{id:'p',label:'Pulse (0-2)',type:'number',def:2},{id:'g',label:'Grimace/reflex (0-2)',type:'number',def:2},{id:'act',label:'Activity/tone (0-2)',type:'number',def:2},{id:'r',label:'Respiration (0-2)',type:'number',def:2}], calc: function(v){ var vals=[v.a,v.p,v.g,v.act,v.r]; if(vals.some(function(x){return x<0||x>2;})) return{result:'Each sign scores 0, 1, or 2',chart:'',extra:''}; var s=vals.reduce(function(x,y){return x+y;},0); var band=s>=7?'reassuring':s>=4?'moderately abnormal':'low — needs attention'; return{result:'APGAR: '+s+'/10 ('+band+')',chart:Charts.gauge(s,10),extra:'Signs: Appearance '+v.a+', Pulse '+v.p+', Grimace '+v.g+', Activity '+v.act+', Respiration '+v.r+' | Scored at 1 and 5 minutes; 5-minute score guides resuscitation decisions'};}, steps: function(v){ var s=[v.a,v.p,v.g,v.act,v.r].reduce(function(x,y){return x+y;},0); return['Step 1: Score each of the five signs 0-2','Step 2: Add them: '+[v.a,v.p,v.g,v.act,v.r].join(' + ')+' = '+s,'7-10 is reassuring, 4-6 moderately abnormal, 0-3 low','A low 1-minute score prompts support; the 5-minute score tracks response'];} }`,
`{ id: 'vaccination-schedule', name: 'Vaccination Due Calculator', desc: 'Routine CDC child vaccines due at a given age', kw: 'vaccination schedule calculator child immunization due cdc', inputs: [{id:'months',label:'Child Age (months)',type:'number',def:6}], calc: function(v){ var m=v.months; var list=[]; if(m>=1) list.push('HepB (1-2mo dose)'); if(m>=2) list.push('DTaP, IPV, Hib, PCV, Rotavirus (2mo)'); if(m>=4) list.push('DTaP, IPV, Hib, PCV, Rotavirus (4mo)'); if(m>=6) list.push('HepB, DTaP, IPV, Hib, PCV, Rotavirus, Influenza (6mo)'); if(m>=12) list.push('MMR, Varicella, HepA, PCV booster (12-15mo)'); if(m>=15) list.push('DTaP booster (15-18mo)'); if(m>=48) list.push('DTaP/IPV/MMR/Varicella boosters (4-6yr)'); if(!list.length) return{result:'Birth dose: HepB within 24 hours of birth',chart:'',extra:''}; var doses=list.join(' | '); return{result:'Due now ('+m+' mo): '+doses.slice(0,60)+(doses.length>60?'...':''),chart:Charts.bar([Math.min(m,72)],['age in months']),extra:'Full due list at '+m+' months: '+doses+' | Catch-up schedules differ — a clinician applies minimum intervals for missed doses'};}, steps: function(v){ return['Step 1: Enter age in months ('+v.months+' entered)','Step 2: The CDC routine schedule assigns vaccine series to age windows','Step 3: This list shows every series due at or before the entered age that is normally completed by then','Always confirm against the current CDC schedule and state requirements — timing rules change'];} }`,
`{ id: 'pediatric-dose', name: 'Pediatric Dose Calculator', desc: 'Weight-based mg dose with a per-kg rate', kw: 'pediatric dose calculator mg per kg child weight medication', inputs: [{id:'w',label:'Child Weight (kg)',type:'number',def:20},{id:'mgkg',label:'Dose Rate (mg/kg)',type:'number',def:15},{id:'max',label:'Adult Maximum Dose (mg)',type:'number',def:1000}], calc: function(v){ if(v.w<=0||v.mgkg<=0) return{result:'Weight and dose rate must be positive',chart:'',extra:''}; var dose=v.w*v.mgkg; var capped=dose>v.max; var final=capped?v.max:dose; return{result:'Dose: '+final.toFixed(0)+' mg'+(capped?' (capped at adult max)':''),chart:Charts.bar([Math.min(dose,v.max),Math.max(0,dose-v.max)],['Given','Exceeds cap']),extra:'Calculation: '+v.w+' kg × '+v.mgkg+' mg/kg = '+dose.toFixed(0)+' mg'+(capped?' — the adult ceiling applies':'')+' | Always verify the rate against the specific drug protocol'};}, steps: function(v){ var dose=v.w*v.mgkg; var capped=dose>v.max; return['Step 1: mg dose = weight × rate = '+v.w+' × '+v.mgkg+' = '+dose.toFixed(0)+' mg',capped?'Step 2: This exceeds the adult maximum of '+v.max+' mg, so the cap applies':'Step 2: This is below the adult maximum of '+v.max+' mg, so the full amount applies','Weight-based dosing is the backbone of pediatrics — double-check units (mg vs mcg) and rounding rules for the drug in question'];} }`
];
T['tech-digital'] = [
`{ id: 'cidr-convert', name: 'CIDR to Subnet Calculator', desc: 'Mask, host count, and broadcast details for a CIDR block', kw: 'cidr calculator subnet mask hosts broadcast ipv4 network', inputs: [{id:'prefix',label:'CIDR Prefix (0-32)',type:'number',def:24},{id:'octet',label:'Network Octet Check (e.g. 10.0.1.x -> enter 1)',type:'number',def:1}], calc: function(v){ if(v.prefix<0||v.prefix>32) return{result:'Prefix must be between 0 and 32',chart:'',extra:''}; var total=Math.pow(2,32-v.prefix); var usable=total-2; if(v.prefix>=31) usable=total; var maskBits=32-v.prefix; var maskOct=[]; for(var i=0;i<4;i++){var bits=Math.max(0,Math.min(8,maskBits-i*8)); var val=bits===0?0:256-Math.pow(2,8-bits); maskOct.push(val);} return{result:'/'+v.prefix+' = '+maskOct.join('.')+' ('+usable+' usable hosts)',chart:Charts.gauge(v.prefix,32),extra:'Total addresses: '+total.toLocaleString()+' | /'+(v.prefix>=31?'no broadcast reserved for point-to-point links':'network + broadcast use 2, leaving '+usable.toLocaleString())} ;}, steps: function(v){ var total=Math.pow(2,32-v.prefix); return['Step 1: Host bits = 32 − '+v.prefix+' = '+(32-v.prefix),'Step 2: Total addresses = 2^'+(32-v.prefix)+' = '+total.toLocaleString(),'Step 3: Usable = '+Math.max(0,total-2).toLocaleString()+' (minus network and broadcast)','Step 4: Mask = 32-bit value with '+v.prefix+' ones followed by zeros'];} }`,
`{ id: 'gpu-comparison-perf', name: 'GPU Value Comparison', desc: 'Frames per second per dollar and per watt', kw: 'gpu comparison calculator fps per dollar performance watt gaming value', inputs: [{id:'fps',label:'Benchmark FPS',type:'number',def:90},{id:'price',label:'Card Price ($)',type:'number',def:500},{id:'watt',label:'Board Power (W)',type:'number',def:250}], calc: function(v){ if(v.price<=0||v.watt<=0||v.fps<0) return{result:'Enter positive price and power',chart:'',extra:''}; var fpd=v.fps/v.price; var fpw=v.fps/v.watt; return{result:fpd.toFixed(3)+' FPS per $',chart:Charts.bar([fpd*1000,fpw*10],['FPS/$ ×1000','FPS/W ×10']),extra:'Performance per watt: '+fpw.toFixed(3)+' FPS/W | Over 3 years at $0.15/kWh the card burns about $'+(v.watt*24*365*3/1000*0.15).toFixed(0)+' of electricity — factor it into total cost'};}, steps: function(v){ var fpd=v.fps/v.price; var fpw=v.fps/v.watt; return['Step 1: FPS per dollar = '+v.fps+' ÷ $'+v.price+' = '+fpd.toFixed(4),'Step 2: FPS per watt = '+v.fps+' ÷ '+v.watt+' W = '+fpw.toFixed(4),'Step 3: Compare both — a cheap card that draws more power can cost more per frame over its life','Use the same resolution and game settings for every card in the comparison'];} }`,
`{ id: 'data-center-pue', name: 'Data Center PUE Calculator', desc: 'Power usage effectiveness from facility and IT load', kw: 'pue calculator data center power usage effectiveness efficiency', inputs: [{id:'total',label:'Total Facility Power (kW)',type:'number',def:130},{id:'it',label:'IT Equipment Power (kW)',type:'number',def:100}], calc: function(v){ if(v.it<=0||v.total<=0) return{result:'Both values must be positive',chart:'',extra:''}; var pue=v.total/v.it; var band=pue<=1.2?'excellent':pue<=1.4?'good':pue<=1.8?'average':'poor'; return{result:'PUE: '+pue.toFixed(2)+' ('+band+')',chart:Charts.gauge(pue,3),extra:'Overhead: '+((pue-1)*100).toFixed(0)+'% of IT power goes to cooling, UPS losses, and lighting — every 0.1 reduction saves roughly '+(v.it*0.1*8760/1000).toFixed(0)+' MWh per year at this scale'};}, steps: function(v){ var pue=v.total/v.it; return['Formula: PUE = Total facility power ÷ IT equipment power','Step 1: '+v.total+' kW ÷ '+v.it+' kW = '+pue.toFixed(3),'Step 2: Overhead = (PUE − 1) × 100 = '+((pue-1)*100).toFixed(0)+'%','PUE of 1.0 is the theoretical floor — hyperscale operators reach 1.1, older enterprise halls often sit at 2.0'];} }`,
`{ id: 'screen-ppi', name: 'Screen PPI Calculator', desc: 'Pixels per inch from resolution and diagonal', kw: 'ppi calculator pixels per inch screen density resolution diagonal', inputs: [{id:'w',label:'Width (px)',type:'number',def:1920},{id:'h',label:'Height (px)',type:'number',def:1080},{id:'d',label:'Diagonal (inches)',type:'number',def:24}], calc: function(v){ if(v.d<=0||v.w<=0||v.h<=0) return{result:'Enter positive dimensions',chart:'',extra:''}; var dp=Math.sqrt(v.w*v.w+v.h*v.h); var ppi=dp/v.d; return{result:'PPI: '+ppi.toFixed(1),chart:Charts.bar([ppi,300],['this screen','retina-ish 300']),extra:'Total pixels: '+(v.w*v.h).toLocaleString()+' | Pixel pitch '+((25.4/ppi)).toFixed(3)+' mm — under about 40 cm viewing distance, 90+ PPI hides individual pixels'};}, steps: function(v){ var dp=Math.sqrt(v.w*v.w+v.h*v.h); var ppi=dp/v.d; return['Step 1: Diagonal in pixels = √(w² + h²) = √('+(v.w*v.w)+' + '+(v.h*v.h)+') = '+dp.toFixed(1),'Step 2: PPI = '+dp.toFixed(1)+' ÷ '+v.d+' in = '+ppi.toFixed(1),'Compare PPI at your real viewing distance — phones need 300+, laptops 150+, TVs look fine under 100'];} }`,
`{ id: 'hash-rate', name: 'Mining Yield Calculator', desc: 'Expected coin yield from network share of hashrate', kw: 'hashrate calculator mining yield bitcoin crypto block reward', inputs: [{id:'hr',label:'Your Hashrate (TH/s)',type:'number',def:100},{id:'net',label:'Network Hashrate (EH/s)',type:'number',def:500},{id:'reward',label:'Block Reward (coins)',type:'number',def:3.125},{id:'price',label:'Coin Price ($)',type:'number',def:60000}], calc: function(v){ if(v.net<=0||v.hr<=0) return{result:'Enter positive hashrates',chart:'',extra:''}; var share=v.hr*1e12/(v.net*1e18); var blocksPerDay=144; var coins=share*blocksPerDay*v.reward; return{result:coins.toFixed(8)+' coins/day',chart:Charts.bar([coins*v.price],['$ per day']),extra:'Network share: '+(share*100).toExponential(2)+'% | ≈ $'+(coins*v.price).toFixed(2)+'/day before power costs — subtract your kWh rate × rig watts × 24 ÷ 1000 × price'};}, steps: function(v){ var share=v.hr*1e12/(v.net*1e18); var coins=share*144*v.reward; return['Step 1: Your share = '+v.hr+' TH/s ÷ '+(v.net*1000)+' TH/s network = '+(share*100).toExponential(3)+'%','Step 2: Blocks per day ≈ 144 (Bitcoin 10-minute target)','Step 3: Coins/day = share × 144 × reward = '+coins.toFixed(8),'Variance is enormous for small miners — most pool solo; consider pool payouts for smooth income'];} }`,
`{ id: 'storage-array', name: 'RAID Usable Capacity Calculator', desc: 'Usable and fault-tolerant capacity for common RAID levels', kw: 'raid calculator usable capacity raid 5 raid 10 storage array', inputs: [{id:'n',label:'Number of Disks',type:'number',def:5},{id:'tb',label:'Disk Size (TB)',type:'number',def:8},{id:'raid',label:'RAID level (0, 1, 5, 6, 10)',type:'number',def:5}], calc: function(v){ if(v.n<2||v.tb<=0) return{result:'Need at least 2 disks of positive size',chart:'',extra:''}; var usable; var tol; if(v.raid===0){usable=v.n*v.tb;tol=0;} else if(v.raid===1){usable=v.tb;tol=Math.floor(v.n/2);} else if(v.raid===5){if(v.n<3) return{result:'RAID 5 needs at least 3 disks',chart:'',extra:''}; usable=(v.n-1)*v.tb;tol=1;} else if(v.raid===6){if(v.n<4) return{result:'RAID 6 needs at least 4 disks',chart:'',extra:''}; usable=(v.n-2)*v.tb;tol=2;} else if(v.raid===10){if(v.n%2) return{result:'RAID 10 needs an even disk count',chart:'',extra:''}; usable=v.n/2*v.tb;tol=Math.floor(v.n/2);} else return{result:'Supported levels: 0, 1, 5, 6, 10',chart:'',extra:''}; return{result:'Usable: '+usable.toFixed(0)+' TB',chart:Charts.bar([v.n*v.tb,usable],['Raw','Usable']),extra:'Fault tolerance: '+tol+' disk'+(tol===1?'':'s')+' | Raw capacity '+(v.n*v.tb).toFixed(0)+' TB, efficiency '+((usable/(v.n*v.tb))*100).toFixed(0)+'%'};}, steps: function(v){ return['Step 1: Raw = '+v.n+' × '+v.tb+' TB = '+(v.n*v.tb).toFixed(0)+' TB','Step 2: RAID '+v.raid+' reserves parity or mirrors per its rule','Step 3: Usable formula — RAID 0: n×d, RAID 1: 1×d, RAID 5: (n−1)×d, RAID 6: (n−2)×d, RAID 10: (n/2)×d','Rebuild time matters: large drives can take a day to rebuild, during which a second failure is survivable only in RAID 6'];} }`,
`{ id: 'docker-resource', name: 'Container Density Calculator', desc: 'How many containers fit given RAM and CPU budgets', kw: 'docker container density calculator ram cpu limit kubernetes pods per node', inputs: [{id:'ram',label:'Host RAM (GB)',type:'number',def:16},{id:'cpu',label:'Host vCPUs',type:'number',def:8},{id:'cram',label:'RAM per Container (GB)',type:'number',def:1},{id:'ccpu',label:'vCPU per Container',type:'number',def:0.5},{id:'over',label:'Reserve for OS (%)',type:'number',def:20}], calc: function(v){ if(v.cram<=0||v.ccpu<=0) return{result:'Per-container limits must be positive',chart:'',extra:''}; var ramAv=v.ram*(1-v.over/100); var byRam=Math.floor(ramAv/v.cram); var byCpu=Math.floor(v.cpu/v.ccpu); var n=Math.min(byRam,byCpu); var lim=byRam<byCpu?'RAM':'CPU'; return{result:n+' containers (limited by '+lim+')',chart:Charts.bar([byRam,byCpu],['RAM limit','CPU limit']),extra:'Usable RAM: '+ramAv.toFixed(1)+' GB after the OS reserve | Leave headroom for bursts — running at 100% of the estimate invites OOM kills'};}, steps: function(v){ var ramAv=v.ram*(1-v.over/100); var byRam=Math.floor(ramAv/v.cram); var byCpu=Math.floor(v.cpu/v.ccpu); return['Step 1: Usable RAM = '+v.ram+' × '+(1-v.over/100)+' = '+ramAv.toFixed(1)+' GB','Step 2: RAM-bound count = floor('+ramAv.toFixed(1)+' ÷ '+v.cram+') = '+byRam,'Step 3: CPU-bound count = floor('+v.cpu+' ÷ '+v.ccpu+') = '+byCpu,'Step 4: The smaller of the two wins — '+Math.min(byRam,byCpu)+' containers'];} }`,
`{ id: 'load-test-users', name: 'Load Test VU Calculator', desc: 'Virtual users needed to hit a target request rate', kw: 'load test virtual users calculator vu target rps response time', inputs: [{id:'rps',label:'Target Requests/sec',type:'number',def:500},{id:'rt',label:'Avg Response Time (s)',type:'number',def:0.4},{id:'think',label:'Think Time (s)',type:'number',def:0}], calc: function(v){ if(v.rps<=0||v.rt<0) return{result:'Enter a positive RPS target',chart:'',extra:''}; var vu=v.rps*(v.rt+v.think); return{result:Math.ceil(vu)+' virtual users',chart:Charts.bar([v.rt,v.think],['Response','Think']),extra:'Little-s law: VUs = RPS × (response + think time) | Ramp gradually — jumping straight to peak hides queueing clues in your metrics'};}, steps: function(v){ var vu=v.rps*(v.rt+v.think); return['Formula (Little-s law): VU = RPS × (response time + think time)','Step 1: ('+v.rt+' + '+v.think+') = '+(v.rt+v.think)+' s per iteration','Step 2: '+v.rps+' × '+(v.rt+v.think)+' = '+vu.toFixed(1)+' → ceil to '+Math.ceil(vu),'If actual RPS falls short, the system is queueing — raise VUs only after fixing server-side saturation'];} }`
];

const QA_ROWS = [
  ['math', 'completing-square', { a: 1, b: 6, c: 5 }, -1, 1, 'x2+6x+5 roots'],
  ['math', 'partial-fractions', { p: 1, q: -1, r: 1, s: 1 }, 0.5, 0.01, 'A = 1/2 for 1/(x2-1)'],
  ['math', 'direct-variation', { mode: 1, a: 3, b: 4 }, 12, 1, 'y = 3 x 4'],
  ['math', 'inverse-variation', { mode: 1, a: 12, b: 4 }, 3, 1, 'y = 12/4'],
  ['math', 'spherical-cap', { R: 5, h: 2 }, 54.45, 0.1, 'pi*4*13/3'],
  ['science', 'angular-momentum', { m: 2, v: 3, r: 4 }, 24, 1, 'm*v*r'],
  ['science', 'bullet-drop', { d: 100, v: 400 }, 30.7, 0.5, '0.5*g*(d/v)^2 in cm'],
  ['science', 'redshift', { rest: 500, obs: 505 }, 0.01, 0.001, 'z = 5/500'],
  ['science', 'buffer-ph', { pka: 4.76, ratio: 1 }, 4.76, 0.01, 'pH = pKa at ratio 1'],
  ['science', 'machine-efficiency', { out: 75, inp: 100 }, 75, 1, '75/100'],
  ['health', 'bmr-mifflin', { w: 70, h: 170, age: 30, sex: 1 }, 1617.5, 1, '10*70+6.25*170-150+5'],
  ['health', 'tdee-macro', { w: 70, h: 170, age: 30, sex: 1, act: 1.55, pct: 30 }, 2507, 2, '1617.5*1.55'],
  ['health', 'gfr-estimate', { scr: 1.0, age: 40, sex: 0 }, 110.6, 1, 'CKD-EPI 2021 male'],
  ['health', 'chw', { w: 80, amp: 6 }, 85.1, 0.3, '80/0.94'],
  ['health', 'gcs', { e: 4, v: 5, m: 6 }, 15, 0.5, 'E4+V5+M6'],
  ['health', 'apgar', { a: 2, p: 2, g: 2, act: 2, r: 2 }, 10, 0.5, '5 signs x 2'],
  ['health', 'vaccination-schedule', { months: 6 }, 6, 1, 'age echo in months'],
  ['health', 'pediatric-dose', { w: 20, mgkg: 15, max: 1000 }, 300, 1, '20*15'],
  ['tech-digital', 'cidr-convert', { prefix: 24, octet: 1 }, 254, 1, '/24 usable hosts'],
  ['tech-digital', 'gpu-comparison-perf', { fps: 90, price: 500, watt: 250 }, 0.18, 0.01, '90/500 fps per dollar'],
  ['tech-digital', 'data-center-pue', { total: 130, it: 100 }, 1.3, 0.01, '130/100'],
  ['tech-digital', 'screen-ppi', { w: 1920, h: 1080, d: 24 }, 91.79, 0.2, '2202.9/24'],
  ['tech-digital', 'hash-rate', { hr: 100, net: 500, reward: 3.125, price: 60000 }, 0.00009, 0.000005, 'share*144*3.125'],
  ['tech-digital', 'storage-array', { n: 5, tb: 8, raid: 5 }, 32, 0.5, '(5-1)*8 TB'],
  ['tech-digital', 'docker-resource', { ram: 16, cpu: 8, cram: 1, ccpu: 0.5, over: 20 }, 12, 0.5, 'floor(12.8/1)'],
  ['tech-digital', 'load-test-users', { rps: 500, rt: 0.4, think: 0 }, 200, 1, '500*0.4 VUs']
];

// ---- insertion logic (CRLF-safe, idempotent) ----
const check = process.argv.includes('--check');
for (const file of Object.keys(T)) {
  const fp = path.join(ROOT, 'js', 'data', file + '.js');
  let src = fs.readFileSync(fp, 'utf8');
  const ids = T[file].map(c => c.match(/id: '([^']+)'/)[1]);
  const present = ids.filter(id => src.includes("id: '" + id + "'"));
  if (present.length) { console.error('[ABORT] ' + file + ' already contains: ' + present.join(', ')); process.exit(1); }
  const anchor = src.lastIndexOf('\r\n];');
  if (anchor < 0) { console.error('[ABORT] no CRLF ]; tail in ' + file); process.exit(1); }
  const before = src.slice(0, anchor);
  const sep = /,\s*$/.test(before) ? '\r\n\r\n' : ',\r\n\r\n';
  const block = T[file].map(c => '  ' + c).join(',\r\n\r\n');
  const out = before + sep + block + src.slice(anchor);
  if (!check) {
    try { new Function(out); } catch (e) { console.error('[ABORT] ' + file + ' would not parse: ' + e.message); process.exit(1); }
    fs.writeFileSync(fp, out);
  }
  console.log('[ok] ' + file + ': +' + ids.length + ' tools');
}
// QA rows
const tfp = path.join(ROOT, 'tests', 'unit', 'formula-qa-full.test.js');
let tsrc = fs.readFileSync(tfp, 'utf8');
const firstRow = "['math', 'completing-square'";
if (tsrc.includes(firstRow)) { console.log('[skip] QA rows already present'); }
else {
  const start = tsrc.indexOf('const CASES = [');
  const close = tsrc.indexOf('\n];', start);
  if (start < 0 || close < 0) { console.error('[ABORT] CASES array not found'); process.exit(1); }
  tsrc = tsrc.slice(0, close) + '\n' + QA_ROWS.map(r => '  ' + JSON.stringify(r).replace(/"([a-zA-Z0-9_]+)":/g, '$1: ').replace(/,'/g, ", '").replace(/',/g, "', ").replace(/\{/g, '{ ').replace(/\}/g, ' }') + ',').join('\n') + tsrc.slice(close);
  if (!check) fs.writeFileSync(tfp, tsrc);
  console.log('[ok] +' + QA_ROWS.length + ' QA rows');
}
console.log((check ? '[DRY RUN] ' : '') + 'done');
