// ============================================================
// COUNT CONSISTENCY TEST — the registry is the single source of
// truth. Every hardcoded count in user-facing files (footer, meta
// description, JSON-LD numberOfItems, intros, SEO content) must
// match the actual registry count, or pages fight each other and
// marketing copy lies.
//
// Mirrors scripts/sync-counts.cjs patterns so CI always catches
// drift even when the sync script is skipped.
// ============================================================
import { describe, it, expect, beforeAll } from 'vitest';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..', '..');

// 1. Registry count (require-based, exactly like sync-counts.cjs)
function registryCount() {
  const dir = path.join(ROOT, 'js', 'data');
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.js'));
  return files.reduce((sum, f) => {
    const mod = require(path.join(dir, f));
    return sum + (Array.isArray(mod) ? mod.length : 0);
  }, 0);
}

const FILES = [
  'index.html',
  'about.html',
  'og-image.html',
  'js/data.js',
  'js/tool-intros.js',
  'js/seo-content.js',
  'js/seo-premium.js',
];

// Same broad pattern family as sync-counts.cjs (catches 5XX+ / 5XX
// next to calculator/tool words AND schema numberOfItems).
const COUNT_RES = [
  /\b5\d{2}\+?\s*(calculators?|tools?|free\s+[\w\s]*?online\s+calculators?|calculators?[,;\s]|tools?[,;\s])/gi,
  /"numberOfItems":\s*"5\d{2}\+?"/g,
];

let count;
beforeAll(() => {
  count = registryCount();
});

describe('calculator count consistency (registry = source of truth)', () => {
  for (const rel of FILES) {
    it(`${rel} has no stale count references`, () => {
      const abs = path.join(ROOT, rel);
      expect(fs.existsSync(abs), `${rel} should exist`).toBe(true);
      const content = fs.readFileSync(abs, 'utf8');
      const stale = [];
      for (const re of COUNT_RES) {
        let m;
        const r = new RegExp(re.source, re.flags);
        while ((m = r.exec(content)) !== null) {
          const numMatch = m[0].match(/5\d{2}/);
          const num = numMatch ? parseInt(numMatch[0], 10) : NaN;
          if (num !== count) stale.push(`${num} ("${m[0].trim().slice(0, 50)}")`);
        }
      }
      expect(stale, `${rel} stale counts`).toEqual([]);
    });
  }

  it('footer copy advertises exactly the registry count', () => {
    const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
    // Footer paragraph hardcoded in index.html (also regenerated by sync)
    const footerMatch = html.match(/(\d{3})\+?\s+free\s+online\s+calculators/);
    if (footerMatch) {
      expect(parseInt(footerMatch[1], 10)).toBe(count);
    }
  });

  it('homepage hero + search placeholder use getCalculatorCount() dynamically', () => {
    const app = fs.readFileSync(path.join(ROOT, 'js', 'app.js'), 'utf8');
    // Hero + search placeholder must derive from getCalculatorCount(), which
    // prefers the build-time SITE_CONFIG.totalCalculators (synced from the
    // registry by sync-counts.cjs) and falls back to ALL_TOOLS.length — never
    // a hardcoded number. This keeps counts correct on lazy-loaded calculator
    // pages where ALL_TOOLS is only partially hydrated.
    expect(app).toMatch(/getCalculatorCount\(\) \+ '\+<\/span>/); // hero h1 highlight
    expect(app).toMatch(/"Search ' \+ getCalculatorCount\(\) \+ '\+ calculators/); // placeholder
    // The helper itself must prefer the build-time total over ALL_TOOLS.
    expect(app).toMatch(/window\.SITE_CONFIG && window\.SITE_CONFIG\.totalCalculators/);
  });
});
